CREATE TABLE FictionalLocation(WorkID VARCHAR(200), Location VARCHAR(200));
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M1', 'New York');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M2', 'Iraq');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M2', 'Texas');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M3', 'Texas');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M4', 'Zubrowka');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M5', 'Britain');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M6', 'Alabama');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M7', 'Britain');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M8', 'New York');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M9', 'Pennsylvania');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M10', 'New York');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M11', 'Belgium');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M12', 'Missouri');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M13', 'Oregon');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M13', 'California');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M14', 'Indiana');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M15', 'The Woods');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M16', 'Los Angeles');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M17', 'Los Angeles');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M18', 'San Fransokyo');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M19', 'Cheesebridge');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M20', 'Berk');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M21', 'Ireland');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M22', 'Japan');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M23', 'Poland');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M24', 'Russia');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M25', 'Georgia');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M26', 'Timbuktu');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M27', 'Argentina');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M28', 'Hong Kong');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M28', 'Moscow');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M29', 'Chicago');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M30', 'Vietnam');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M31', 'Brazil');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M32', 'Congo');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M33', 'Canandaigua');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M34', 'Poland');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M35', 'Poland');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M36', 'Mexico');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M37', 'North Dakota');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M38', 'Britain');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M39', 'Israel');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M40', 'Britain');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M41', 'China');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M42', 'Switzerland');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M43', 'United States');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M44', 'Britain');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M45', 'New Orleans');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M46', 'New Jersey');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M47', 'Indian Ocean');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M48', 'Texas');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M49', 'Space');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M50', 'Los Angeles');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M51', 'Nebraska');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M51', 'South Dakota');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M51', 'Wyoming');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M52', 'Britain');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M53', 'New York');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M54', 'New York');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M54', 'San Francisco');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M55', 'Oklahoma');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M56', 'France');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M57', 'Arendelle');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M58', 'Earth');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M59', 'United States');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M60', 'Belgium');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M61', 'Japan');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M62', 'London');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M63', 'South Africa');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M64', 'Indian Ocean');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M65', 'Middle Earth');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M66', 'Afghanistan');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M67', 'New York');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M68', 'New York');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M69', 'United States');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M70', 'Norway');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M71', 'Netherlands');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M72', 'Texas');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M72', 'Space');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M73', 'Britain');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M74', 'Lego Universe');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M76', 'United States');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M76', 'Australia');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M76', 'Europe');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M77', 'New York');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M78', 'Middle Earth');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M79', 'California');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M79', 'Germany');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M79', 'Japan');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M80', 'Nova Empire');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M81', 'A Faraway Land');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M81', 'The Moors');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M82', 'Washington D.C.');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M83', 'San Francisco');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M84', 'New York');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M84', 'China');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M84', 'Russia');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M84', 'Washington D.C.');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M84', 'Paris');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('M84', 'Vietnam');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('S1', 'New York');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('S2', 'Washington D.C.');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('S3', 'New York');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('S4', 'New York');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('S5', 'Ireland');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('S6', 'London');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('S7', 'New York');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('S8', 'Agrabah');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('S9', 'New York');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('S10', 'Chicago');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('S11', 'Ireland');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('S12', 'St. Louis');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('S13', 'Ilyria');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('S14', 'Germany');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('S16', 'Oklahoma');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('S18', 'Britain');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('S19', 'Philadelphia');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('S20', 'New York');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('S21', 'Philadelphia');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('S23', 'New York');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('S24', 'Iowa');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('S25', 'Germany');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('S26', 'New York');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('S27', 'New York');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('T1', 'Los Angeles');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('T2', 'Pasadena');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('T3', 'New York');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('T4', 'New York');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('T5', 'Palo Alto');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('T6', 'Washington D.C.');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('T7', 'New Mexico');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('T8', 'Britain');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('T9', 'Westeros');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('T10', 'Washington D.C.');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('T11', 'New York');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('T12', 'New Orleans');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('T13', 'New York');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('T14', 'New York');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('T15', 'Los Angeles');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('T16', 'Los Angeles');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('T17', 'New York');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('T17', 'New York');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('T19', 'Minnesota');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('T20', 'New Orleans');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('T21', 'Texas');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('T22', 'Britain');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('T23', 'New Orleans');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('T24', 'Britain');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('T25', 'New York');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('T26', 'United States');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('T27', 'Washington D.C.');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('T28', 'Britain');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('T36', 'New York');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('T37', 'Britain');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('T38', 'Los Angeles');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('T39', 'Chicago');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('T40', 'New York');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('T41', 'New York');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('T42', 'Chicago');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('T43', 'Indiana');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('T44', 'New York');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('T45', 'Chicago');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('T47', 'Missouri');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('T48', 'Washington D.C.');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('T49', 'Washington D.C.');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('T50', 'London');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('T51', 'New York');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('T53', 'Texas');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('T53', 'New York');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('T54', 'Portland');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('T55', 'New York');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('T56', 'Sonoma');
INSERT INTO FictionalLocation (WorkID, Location) VALUES ('T57', 'Los Angeles');