CREATE TABLE FilmedIn(WorkID VARCHAR(200), Location VARCHAR(200));
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M1', 'New York');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M2', 'Los Angeles');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M2', 'Morocco');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M3', 'Texas');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M4', 'Germany');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M5', 'Britain');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M6', 'Georgia (state)');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M6', 'Alabama');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M7', 'Britain');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M8', 'Los Angeles');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M9', 'Pennsylvania');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M10', 'New York');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M11', 'Belgium');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M12', 'Missouri');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M13', 'Oregon');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M13', 'California');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M14', 'Massachusetts');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M15', 'London');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M16', 'Los Angeles');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M17', 'Los Angeles');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M23', 'Poland');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M24', 'Russia');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M25', 'Georgia');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M26', 'Mauritania');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M27', 'Argentina');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M28', 'Hong Kong');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M28', 'Moscow');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M29', 'Chicago');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M30', 'Vietnam');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M31', 'France');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M31', 'Brazil');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M32', 'Congo');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M33', 'Canandaigua');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M34', 'Poland');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M35', 'Poland');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M36', 'Mexico');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M37', 'North Dakota');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M38', 'Britain');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M39', 'Israel');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M40', 'Britain');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M41', 'France');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M41', 'China');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M42', 'Switzerland');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M43', 'United States');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M44', 'Britain');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M45', 'New Orleans');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M46', 'Boston');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M46', 'Worcester');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M47', 'Mediterranean Sea');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M48', 'Louisiana');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M49', 'Britain');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M49', 'Arizona');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M50', 'Los Angeles');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M50', 'Shanghai');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M51', 'Nebraska');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M51', 'Montana');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M51', 'Wyoming');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M51', 'South Dakota');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M52', 'Britain');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M53', 'New Jersey');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M53', 'New York');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M54', 'New York');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M54', 'San Francisco');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M55', 'Oklahoma');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M55', 'Los Angeles');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M56', 'United States');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M62', 'Southern California');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M63', 'South Africa');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M64', 'Mexico');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M65', 'New Zealand');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M66', 'New Mexico');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M67', 'New York');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M68', 'Sydney');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M69', 'United States');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M70', 'Canada');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M71', 'Netherlands');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M72', 'Canada');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M73', 'Britain');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M75', 'United States');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M76', 'Australia');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M77', 'Europe');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M77', 'New York');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M78', 'New Zealand');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M79', 'Australia');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M80', 'London');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M81', 'London');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M82', 'Los Angeles');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M82', 'Cleveland');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M82', 'Washington D.C.');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M83', 'Canada');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('M84', 'Canada');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('S1', 'New York');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('S2', 'New York');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('S3', 'New York');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('S4', 'New York');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('S5', 'New York');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('S6', 'New York');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('S7', 'New York');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('S8', 'New York');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('S9', 'New York');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('S10', 'New York');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('S11', 'New York');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('S12', 'New York');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('S13', 'New York');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('S14', 'New York');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('S15', 'New York');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('S16', 'New York');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('S17', 'New York');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('S18', 'New York');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('S19', 'New York');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('S20', 'New York');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('S21', 'New York');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('S22', 'New York');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('S23', 'New York');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('S24', 'New York');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('S25', 'New York');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('S26', 'New York');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('S27', 'New York');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('T1', 'Los Angeles');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('T2', 'Burbank');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('T3', 'New York');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('T4', 'New York');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('T5', 'Palo Alto');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('T6', 'Baltimore');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('T7', 'New Mexico');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('T8', 'Britain');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('T9', 'Britain');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('T9', 'Iceland');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('T9', 'Croatia');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('T9', 'Spain');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('T9', 'Morocco');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('T9', 'United States');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('T10', 'Baltimore');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('T10', 'Maryland');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('T11', 'Los Angeles');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('T12', 'New Orleans');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('T13', 'New York');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('T14', 'New York');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('T15', 'Los Angeles');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('T16', 'Los Angeles');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('T17', 'New York');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('T18', 'New York');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('T19', 'Canada');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('T20', 'New Orleans');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('T21', 'Louisiana');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('T22', 'Britain');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('T23', 'New Orleans');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('T24', 'Belgium');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('T25', 'New York');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('T26', 'Virginia');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('T27', 'New York');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('T28', 'Britain');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('T29', 'Georgia (state)');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('T30', 'Worldwide');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('T31', 'Los Angeles');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('T32', 'New York');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('T33', 'United States');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('T34', 'United States');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('T35', 'Los Angeles');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('T36', 'Los Angeles');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('T36', 'New York');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('T37', 'Britain');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('T38', 'Britain');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('T39', 'Los Angeles');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('T40', 'New York');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('T41', 'New York');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('T42', 'Los Angeles');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('T43', 'Los Angeles');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('T44', 'Los Angeles');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('T45', 'New York');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('T47', 'Missouri');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('T48', 'North Carolina');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('T49', 'Los Angeles');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('T50', 'Britain');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('T51', 'Britain');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('T53', 'Los Angeles');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('T54', 'Portland');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('T55', 'Los Angeles');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('T56', 'Los Angeles');
INSERT INTO FilmedIn (WorkID, Location) VALUES ('T57', 'Los Angeles');