CREATE TABLE Honor(AwardID VARCHAR(200) PRIMARY KEY, AwardName VARCHAR(1000) NULL, YearGiven INT NULL, NominatedWon VARCHAR(50) NULL, ShowName VARCHAR(50) NULL, WorkID VARCHAR(50) NULL, PersonName VARCHAR(100) NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E1', 'Outstanding Comedy Series', 2014, 'Won', 'Emmys', 'T1', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E2', 'Outstanding Comedy Series', 2014, 'Nominated', 'Emmys', 'T2', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E3', 'Outstanding Comedy Series', 2014, 'Nominated', 'Emmys', 'T3', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E4', 'Outstanding Comedy Series', 2014, 'Nominated', 'Emmys', 'T4', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E5', 'Outstanding Comedy Series', 2014, 'Nominated', 'Emmys', 'T5', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E6', 'Outstanding Comedy Series', 2014, 'Nominated', 'Emmys', 'T6', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E7', 'Outstanding Drama Series', 2014, 'Won', 'Emmys', 'T7', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E8', 'Outstanding Drama Series', 2014, 'Nominated', 'Emmys', 'T8', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E9', 'Outstanding Drama Series', 2014, 'Nominated', 'Emmys', 'T9', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E10', 'Outstanding Drama Series', 2014, 'Nominated', 'Emmys', 'T10', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E11', 'Outstanding Drama Series', 2014, 'Nominated', 'Emmys', 'T11', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E12', 'Outstanding Drama Series', 2014, 'Nominated', 'Emmys', 'T12', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E13', 'Outstanding Variety Series', 2014, 'Won', 'Emmys', 'T13', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E14', 'Outstanding Variety Series', 2014, 'Nominated', 'Emmys', 'T14', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E15', 'Outstanding Variety Series', 2014, 'Nominated', 'Emmys', 'T15', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E16', 'Outstanding Variety Series', 2014, 'Nominated', 'Emmys', 'T16', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E17', 'Outstanding Variety Series', 2014, 'Nominated', 'Emmys', 'T17', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E18', 'Outstanding Variety Series', 2014, 'Nominated', 'Emmys', 'T18', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E19', 'Outstanding Miniseries', 2014, 'Won', 'Emmys', 'T19', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E20', 'Outstanding Miniseries', 2014, 'Nominated', 'Emmys', 'T20', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E21', 'Outstanding Miniseries', 2014, 'Nominated', 'Emmys', 'T21', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E22', 'Outstanding Miniseries', 2014, 'Nominated', 'Emmys', 'T22', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E23', 'Outstanding Miniseries', 2014, 'Nominated', 'Emmys', 'T23', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E24', 'Outstanding Miniseries', 2014, 'Nominated', 'Emmys', 'T24', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E25', 'Outstanding Television Movie', 2014, 'Won', 'Emmys', 'T25', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E26', 'Outstanding Television Movie', 2014, 'Nominated', 'Emmys', 'T26', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E27', 'Outstanding Television Movie', 2014, 'Nominated', 'Emmys', 'T27', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E28', 'Outstanding Television Movie', 2014, 'Nominated', 'Emmys', 'T28', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E29', 'Outstanding Television Movie', 2014, 'Nominated', 'Emmys', 'T29', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E30', 'Outstanding Reality - Competition Program', 2014, 'Won', 'Emmys', 'T30', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E31', 'Outstanding Reality - Competition Program', 2014, 'Nominated', 'Emmys', 'T31', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E32', 'Outstanding Reality - Competition Program', 2014, 'Nominated', 'Emmys', 'T32', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E33', 'Outstanding Reality - Competition Program', 2014, 'Nominated', 'Emmys', 'T33', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E34', 'Outstanding Reality - Competition Program', 2014, 'Nominated', 'Emmys', 'T34', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E35', 'Outstanding Reality - Competition Program', 2014, 'Nominated', 'Emmys', 'T35', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E36', 'Outstanding Lead Actor in a Comedy Series', 2014, 'Won', 'Emmys', 'T2', 'Jim Parsons');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E37', 'Outstanding Lead Actor in a Comedy Series', 2014, 'Nominated', 'Emmys', 'T3', 'Louis C.K.');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E38', 'Outstanding Lead Actor in a Comedy Series', 2014, 'Nominated', 'Emmys', 'T36', 'Don Cheadle');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E39', 'Outstanding Lead Actor in a Comedy Series', 2014, 'Nominated', 'Emmys', 'T37', 'Ricky Gervais');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E40', 'Outstanding Lead Actor in a Comedy Series', 2014, 'Nominated', 'Emmys', 'T38', 'Matt LeBlanc');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E41', 'Outstanding Lead Actor in a Comedy Series', 2014, 'Nominated', 'Emmys', 'T39', 'William H. Macy');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E42', 'Outstanding Lead Actress in a Comedy Series', 2014, 'Won', 'Emmys', 'T6', 'Julia Louis-Dreyfus');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E43', 'Outstanding Lead Actress in a Comedy Series', 2014, 'Nominated', 'Emmys', 'T40', 'Lena Dunham');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E44', 'Outstanding Lead Actress in a Comedy Series', 2014, 'Nominated', 'Emmys', 'T41', 'Edie Falco');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E45', 'Outstanding Lead Actress in a Comedy Series', 2014, 'Nominated', 'Emmys', 'T42', 'Melissa McCarthy');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E46', 'Outstanding Lead Actress in a Comedy Series', 2014, 'Nominated', 'Emmys', 'T43', 'Amy Poehler');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E47', 'Outstanding Lead Actress in a Comedy Series', 2014, 'Nominated', 'Emmys', 'T4', 'Taylor Schilling');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E48', 'Outstanding Lead Actor in a Drama Series', 2014, 'Won', 'Emmys', 'T7', 'Bryan Cranston');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E49', 'Outstanding Lead Actor in a Drama Series', 2014, 'Nominated', 'Emmys', 'T44', 'Jeff Daniels');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E50', 'Outstanding Lead Actor in a Drama Series', 2014, 'Nominated', 'Emmys', 'T11', 'Jon Ham');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E51', 'Outstanding Lead Actor in a Drama Series', 2014, 'Nominated', 'Emmys', 'T12', 'Woody Harrelson');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E52', 'Outstanding Lead Actor in a Drama Series', 2014, 'Nominated', 'Emmys', 'T12', 'Matthew McConaughey');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E53', 'Outstanding Lead Actor in a Drama Series', 2014, 'Nominated', 'Emmys', 'T10', 'Kevin Spacey');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E54', 'Outstanding Lead Actress in a Drama Series', 2014, 'Won', 'Emmys', 'T45', 'Julianna Margulies');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E55', 'Outstanding Lead Actress in a Drama Series', 2014, 'Nominated', 'Emmys', 'T47', 'Lizzy Caplan');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E56', 'Outstanding Lead Actress in a Drama Series', 2014, 'Nominated', 'Emmys', 'T8', 'Michelle Dockery');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E57', 'Outstanding Lead Actress in a Drama Series', 2014, 'Nominated', 'Emmys', 'T49', 'Kerry Washington');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E58', 'Outstanding Lead Actress in a Drama Series', 2014, 'Nominated', 'Emmys', 'T10', 'Robin Wright');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E59', 'Outstanding Lead Actress in a Drama Series', 2014, 'Nominated', 'Emmys', 'T48', 'Claire Danes');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E60', 'Outstanding Lead Actor in a Miniseries or Movie', 2014, 'Won', 'Emmys', 'T28', 'Benedict Cumberbatch');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E61', 'Outstanding Lead Actor in a Miniseries or Movie', 2014, 'Nominated', 'Emmys', 'T50', 'Chiwetel Ejiofor');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E62', 'Outstanding Lead Actor in a Miniseries or Movie', 2014, 'Nominated', 'Emmys', 'T22', 'Idris Elba');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E63', 'Outstanding Lead Actor in a Miniseries or Movie', 2014, 'Nominated', 'Emmys', 'T19', 'Martin Freeman');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E64', 'Outstanding Lead Actor in a Miniseries or Movie', 2014, 'Nominated', 'Emmys', 'T25', 'Mark Ruffalo');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E65', 'Outstanding Lead Actor in a Miniseries or Movie', 2014, 'Nominated', 'Emmys', 'T19', 'Billy Bob Thornton');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E66', 'Outstanding Lead Actress in a Miniseries or Movie', 2014, 'Won', 'Emmys', 'T20', 'Jessica Lange');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E67', 'Outstanding Lead Actress in a Miniseries or Movie', 2014, 'Nominated', 'Emmys', 'T51', 'Helena Bonham Carter');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E68', 'Outstanding Lead Actress in a Miniseries or Movie', 2014, 'Nominated', 'Emmys', 'T52', 'Minnie Driver');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E69', 'Outstanding Lead Actress in a Miniseries or Movie', 2014, 'Nominated', 'Emmys', 'T20', 'Sarah Paulson');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E70', 'Outstanding Lead Actress in a Miniseries or Movie', 2014, 'Nominated', 'Emmys', 'T29', 'Cecily Tyson');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E71', 'Outstanding Lead Actress in a Miniseries or Movie', 2014, 'Nominated', 'Emmys', 'T53', 'Kristen Wiig');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E72', 'Outstanding Supporting Actor in a Comedy Series', 2014, 'Won', 'Emmys', 'T1', 'Ty Burrell');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E73', 'Outstanding Supporting Actor in a Comedy Series', 2014, 'Nominated', 'Emmys', 'T54', 'Fred Armisen');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E74', 'Outstanding Supporting Actor in a Comedy Series', 2014, 'Nominated', 'Emmys', 'T55', 'Andre Braugher');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E75', 'Outstanding Supporting Actor in a Comedy Series', 2014, 'Nominated', 'Emmys', 'T40', 'Adam Driver');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E76', 'Outstanding Supporting Actor in a Comedy Series', 2014, 'Nominated', 'Emmys', 'T1', 'Jesse Tyler Ferguson');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E77', 'Outstanding Supporting Actor in a Comedy Series', 2014, 'Nominated', 'Emmys', 'T6', 'Tony Hale');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E78', 'Outstanding Supporting Actress in a Comedy Series', 2014, 'Won', 'Emmys', 'T56', 'Allison Janney');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E79', 'Outstanding Supporting Actress in a Comedy Series', 2014, 'Nominated', 'Emmys', 'T2', 'Mayim Bialik');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E80', 'Outstanding Supporting Actress in a Comedy Series', 2014, 'Nominated', 'Emmys', 'T1', 'Julie Bowen');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E81', 'Outstanding Supporting Actress in a Comedy Series', 2014, 'Nominated', 'Emmys', 'T6', 'Anna Chlumsky');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E82', 'Outstanding Supporting Actress in a Comedy Series', 2014, 'Nominated', 'Emmys', 'T17', 'Kate McKinnon');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E83', 'Outstanding Supporting Actress in a Comedy Series', 2014, 'Nominated', 'Emmys', 'T4', 'Kate Mulgrew');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E84', 'Outstanding Supporting Actor in a Drama Series', 2014, 'Won', 'Emmys', 'T7', 'Aaron Paul');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E85', 'Outstanding Supporting Actor in a Drama Series', 2014, 'Nominated', 'Emmys', 'T8', 'Jim Carter');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E86', 'Outstanding Supporting Actor in a Drama Series', 2014, 'Nominated', 'Emmys', 'T45', 'Josh Charles');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E87', 'Outstanding Supporting Actor in a Drama Series', 2014, 'Nominated', 'Emmys', 'T9', 'Peter Dinklage');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E88', 'Outstanding Supporting Actor in a Drama Series', 2014, 'Nominated', 'Emmys', 'T48', 'Mandy Patinkin');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E89', 'Outstanding Supporting Actor in a Drama Series', 2014, 'Nominated', 'Emmys', 'T57', 'Jon Voight');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E90', 'Outstanding Supporting Actress in a Drama Series', 2014, 'Won', 'Emmys', 'T7', 'Anna Gunn');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E91', 'Outstanding Supporting Actress in a Drama Series', 2014, 'Nominated', 'Emmys', 'T45', 'Christine Baranski');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E92', 'Outstanding Supporting Actress in a Drama Series', 2014, 'Nominated', 'Emmys', 'T8', 'Joanne Froggatt');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E93', 'Outstanding Supporting Actress in a Drama Series', 2014, 'Nominated', 'Emmys', 'T9', 'Lena Headey');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E94', 'Outstanding Supporting Actress in a Drama Series', 2014, 'Nominated', 'Emmys', 'T11', 'Christina Hendricks');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E95', 'Outstanding Supporting Actress in a Drama Series', 2014, 'Nominated', 'Emmys', 'T8', 'Maggie Smith');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E96', 'Outstanding Supporting Actor in a Miniseries or Movie', 2014, 'Won', 'Emmys', 'T28', 'Martin Freeman');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E97', 'Outstanding Supporting Actor in a Miniseries or Movie', 2014, 'Nominated', 'Emmys', 'T25', 'Matt Bomer');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E98', 'Outstanding Supporting Actor in a Miniseries or Movie', 2014, 'Nominated', 'Emmys', 'T28', 'Colin Hanks');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E99', 'Outstanding Supporting Actor in a Miniseries or Movie', 2014, 'Nominated', 'Emmys', 'T25', 'Joe Mantello');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E100', 'Outstanding Supporting Actor in a Miniseries or Movie', 2014, 'Nominated', 'Emmys', 'T25', 'Alfred Molina');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E101', 'Outstanding Supporting Actor in a Miniseries or Movie', 2014, 'Nominated', 'Emmys', 'T25', 'Jim Parsons');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E102', 'Outstanding Supporting Actress in a Miniseries or Movie', 2014, 'Won', 'Emmys', 'T20', 'Kathy Bates');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E103', 'Outstanding Supporting Actress in a Miniseries or Movie', 2014, 'Nominated', 'Emmys', 'T20', 'Angela Bassett');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E104', 'Outstanding Supporting Actress in a Miniseries or Movie', 2014, 'Nominated', 'Emmys', 'T58', 'Ellen Burstyn');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E105', 'Outstanding Supporting Actress in a Miniseries or Movie', 2014, 'Nominated', 'Emmys', 'T20', 'Frances Conroy');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E106', 'Outstanding Supporting Actress in a Miniseries or Movie', 2014, 'Nominated', 'Emmys', 'T25', 'Julia Roberts');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('E107', 'Outstanding Supporting Actress in a Miniseries or Movie', 2014, 'Nominated', 'Emmys', 'T28', 'Allison Tolman');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N1', 'Best Play', 2014, 'Won', 'Tonys', 'S2', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N2', 'Best Play', 2014, 'Nominated', 'Tonys', 'S1', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N3', 'Best Play', 2014, 'Nominated', 'Tonys', 'S3', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N4', 'Best Play', 2014, 'Nominated', 'Tonys', 'S4', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N5', 'Best Play', 2014, 'Nominated', 'Tonys', 'S5', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N6', 'Best Musical', 2014, 'Won', 'Tonys', 'S6', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N7', 'Best Musical', 2014, 'Nominated', 'Tonys', 'S7', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N8', 'Best Musical', 2014, 'Nominated', 'Tonys', 'S8', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N9', 'Best Musical', 2014, 'Nominated', 'Tonys', 'S9', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N10', 'Best Revival of a Play', 2014, 'Won', 'Tonys', 'S10', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N11', 'Best Revival of a Play', 2014, 'Nominated', 'Tonys', 'S11', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N12', 'Best Revival of a Play', 2014, 'Nominated', 'Tonys', 'S12', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N13', 'Best Revival of a Play', 2014, 'Nominated', 'Tonys', 'S13', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N14', 'Best Revival of a Musical', 2014, 'Won', 'Tonys', 'S14', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N15', 'Best Revival of a Musical', 2014, 'Nominated', 'Tonys', 'S15', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N16', 'Best Revival of a Musical', 2014, 'Nominated', 'Tonys', 'S16', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N17', 'Best Performance by a Leading Actor in a Play', 2014, 'Won', 'Tonys', 'S2', 'Bryan Cranston');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N18', 'Best Performance by a Leading Actor in a Play', 2014, 'Nominated', 'Tonys', 'S13', 'Samuel Barnett');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N19', 'Best Performance by a Leading Actor in a Play', 2014, 'Nominated', 'Tonys', 'S17', 'Chris O''Dowd');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N20', 'Best Performance by a Leading Actor in a Play', 2014, 'Nominated', 'Tonys', 'S18', 'Mark Rylance');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N21', 'Best Performance by a Leading Actor in a Play', 2014, 'Nominated', 'Tonys', 'S1', 'Tony Shalhoub');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N22', 'Best Performance by a Leading Actress in a Play', 2014, 'Won', 'Tonys', 'S19', 'Audra McDonald');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N23', 'Best Performance by a Leading Actress in a Play', 2014, 'Nominated', 'Tonys', 'S4', 'Tyne Daly');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N24', 'Best Performance by a Leading Actress in a Play', 2014, 'Nominated', 'Tonys', 'S10', 'LaTanya Richardson');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N25', 'Best Performance by a Leading Actress in a Play', 2014, 'Nominated', 'Tonys', 'S12', 'Cherry Jones');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N26', 'Best Performance by a Leading Actress in a Play', 2014, 'Nominated', 'Tonys', 'S20', 'Estelle Parsons');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N27', 'Best Performance by a Leading Actor in a Musical', 2014, 'Won', 'Tonys', 'S14', 'Neil Patrick Harris');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N28', 'Best Performance by a Leading Actor in a Musical', 2014, 'Nominated', 'Tonys', 'S15', 'Ramin Karimloo');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N29', 'Best Performance by a Leading Actor in a Musical', 2014, 'Nominated', 'Tonys', 'S21', 'Andy Karl');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N30', 'Best Performance by a Leading Actor in a Musical', 2014, 'Nominated', 'Tonys', 'S6', 'Jefferson Mays');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N31', 'Best Performance by a Leading Actor in a Musical', 2014, 'Nominated', 'Tonys', 'S6', 'Bryce Pinkham');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N32', 'Best Performance by a Leading Actress in a Musical', 2014, 'Won', 'Tonys', 'S9', 'Jessie Mueller');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N33', 'Best Performance by a Leading Actress in a Musical', 2014, 'Nominated', 'Tonys', 'S22', 'Mary Bridget Davies');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N34', 'Best Performance by a Leading Actress in a Musical', 2014, 'Nominated', 'Tonys', 'S16', 'Sutton Foster');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N35', 'Best Performance by a Leading Actress in a Musical', 2014, 'Nominated', 'Tonys', 'S23', 'Idina Menzel');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N36', 'Best Performance by a Leading Actress in a Musical', 2014, 'Nominated', 'Tonys', 'S24', 'Kelli O''Hara');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N37', 'Best Performance by a Featured Actor in a Play', 2014, 'Won', 'Tonys', 'S13', 'Mark Rylance');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N38', 'Best Performance by a Featured Actor in a Play', 2014, 'Nominated', 'Tonys', 'S3', 'Reed Birney');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N39', 'Best Performance by a Featured Actor in a Play', 2014, 'Nominated', 'Tonys', 'S13', 'Paul Chahidi');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N40', 'Best Performance by a Featured Actor in a Play', 2014, 'Nominated', 'Tonys', 'S13', 'Stephen Fry');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N41', 'Best Performance by a Featured Actor in a Play', 2014, 'Nominated', 'Tonys', 'S12', 'Brian J. Smith');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N42', 'Best Performance by a Featured Actress in a Play', 2014, 'Won', 'Tonys', 'S10', 'Sophie Okonedo');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N43', 'Best Performance by a Featured Actress in a Play', 2014, 'Nominated', 'Tonys', 'S11', 'Sarah Greene');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N44', 'Best Performance by a Featured Actress in a Play', 2014, 'Nominated', 'Tonys', 'S12', 'Celia Keenan-Bolger');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N45', 'Best Performance by a Featured Actress in a Play', 2014, 'Nominated', 'Tonys', 'S10', 'Anika Noni Rose');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N46', 'Best Performance by a Featured Actress in a Play', 2014, 'Nominated', 'Tonys', 'S3', 'Mare Winningham');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N47', 'Best Performance by a Featured Actor in a Musical', 2014, 'Won', 'Tonys', 'S8', 'James Monroe Iglehart');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N48', 'Best Performance by a Featured Actor in a Musical', 2014, 'Nominated', 'Tonys', 'S25', 'Danny Burstein');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N49', 'Best Performance by a Featured Actor in a Musical', 2014, 'Nominated', 'Tonys', 'S26', 'Nick Cordero');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N50', 'Best Performance by a Featured Actor in a Musical', 2014, 'Nominated', 'Tonys', 'S16', 'Joshua Henry');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N51', 'Best Performance by a Featured Actor in a Musical', 2014, 'Nominated', 'Tonys', 'S9', 'Jarrod Spector');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N52', 'Best Performance by a Featured Actress in a Musical', 2014, 'Won', 'Tonys', 'S14', 'Lena Hall');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N53', 'Best Performance by a Featured Actress in a Musical', 2014, 'Nominated', 'Tonys', 'S25', 'Linda Emond');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N54', 'Best Performance by a Featured Actress in a Musical', 2014, 'Nominated', 'Tonys', 'S9', 'Anika Larsen');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N55', 'Best Performance by a Featured Actress in a Musical', 2014, 'Nominated', 'Tonys', 'S7', 'Adriane Lenox');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N56', 'Best Performance by a Featured Actress in a Musical', 2014, 'Nominated', 'Tonys', 'S6', 'Lauren Worsham');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N57', 'Best Book of a Musical', 2014, 'Won', 'Tonys', 'S6', 'Robert L. Freedman');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N58', 'Best Book of a Musical', 2014, 'Nominated', 'Tonys', 'S8', 'Chad Beguelin');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N59', 'Best Book of a Musical', 2014, 'Nominated', 'Tonys', 'S9', 'Douglas McGrath');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N60', 'Best Book of a Musical', 2014, 'Nominated', 'Tonys', 'S26', 'Woody Allen');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N61', 'Best Original Score', 2014, 'Won', 'Tonys', 'S24', 'Jason Robert Brown');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N62', 'Best Original Score', 2014, 'Nominated', 'Tonys', 'S8', 'Alan Menken');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N63', 'Best Original Score', 2014, 'Nominated', 'Tonys', 'S8', 'Howard Ashman');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N64', 'Best Original Score', 2014, 'Nominated', 'Tonys', 'S8', 'Tim Rice');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N65', 'Best Original Score', 2014, 'Nominated', 'Tonys', 'S8', 'Chad Beguelin');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N66', 'Best Original Score', 2014, 'Nominated', 'Tonys', 'S6', 'Steven Lutvak');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N67', 'Best Original Score', 2014, 'Nominated', 'Tonys', 'S6', 'Robert L. Freedman');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N68', 'Best Original Score', 2014, 'Nominated', 'Tonys', 'S23', 'Tom Kitt');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('N69', 'Best Original Score', 2014, 'Nominated', 'Tonys', 'S23', 'Brian Yorkey');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G1', 'Record of the Year', 2014, 'Won', 'Grammys', 'U1', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G2', 'Record of the Year', 2014, 'Nominated', 'Grammys', 'U2', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G3', 'Record of the Year', 2014, 'Nominated', 'Grammys', 'U3', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G4', 'Record of the Year', 2014, 'Nominated', 'Grammys', 'U4', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G5', 'Record of the Year', 2014, 'Nominated', 'Grammys', 'U5', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G6', 'Album of the Year', 2014, 'Won', 'Grammys', 'U6', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G7', 'Album of the Year', 2014, 'Nominated', 'Grammys', 'U7', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G8', 'Album of the Year', 2014, 'Nominated', 'Grammys', 'U8', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G9', 'Album of the Year', 2014, 'Nominated', 'Grammys', 'U9', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G10', 'Album of the Year', 2014, 'Nominated', 'Grammys', 'U10', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G11', 'Song of the Year', 2014, 'Won', 'Grammys', 'U1', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G12', 'Song of the Year', 2014, 'Nominated', 'Grammys', 'U5', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G13', 'Song of the Year', 2014, 'Nominated', 'Grammys', 'U3', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G14', 'Song of the Year', 2014, 'Nominated', 'Grammys', 'U4', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G15', 'Song of the Year', 2014, 'Nominated', 'Grammys', 'U11', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G16', 'Best New Artist', 2014, 'Won', 'Grammys', 'P4', 'Sam Smith');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G17', 'Best New Artist', 2014, 'Nominated', 'Grammys', 'P5', 'Iggy Azalea');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G18', 'Best New Artist', 2014, 'Nominated', 'Grammys', 'P287', 'Bastille');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G19', 'Best New Artist', 2014, 'Nominated', 'Grammys', 'P100', 'Brandy Clark');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G20', 'Best New Artist', 2014, 'Nominated', 'Grammys', 'P288', 'HAIM');
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G21', 'Best Pop Solo Performance', 2014, 'Won', 'Grammys', 'U12', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G22', 'Best Pop Solo Performance', 2014, 'Nominated', 'Grammys', 'U13', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G23', 'Best Pop Solo Performance', 2014, 'Nominated', 'Grammys', 'U3', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G24', 'Best Pop Solo Performance', 2014, 'Nominated', 'Grammys', 'U1', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G25', 'Best Pop Solo Performance', 2014, 'Nominated', 'Grammys', 'U4', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G26', 'Best Pop Duo/Group Performance', 2014, 'Won', 'Grammys', 'U14', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G27', 'Best Pop Duo/Group Performance', 2014, 'Nominated', 'Grammys', 'U2', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G28', 'Best Pop Duo/Group Performance', 2014, 'Nominated', 'Grammys', 'U15', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G29', 'Best Pop Duo/Group Performance', 2014, 'Nominated', 'Grammys', 'U16', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G30', 'Best Pop Duo/Group Performance', 2014, 'Nominated', 'Grammys', 'U17', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G31', 'Best Pop Vocal Album', 2014, 'Won', 'Grammys', 'U9', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G32', 'Best Pop Vocal Album', 2014, 'Nominated', 'Grammys', 'U18', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G33', 'Best Pop Vocal Album', 2014, 'Nominated', 'Grammys', 'U19', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G34', 'Best Pop Vocal Album', 2014, 'Nominated', 'Grammys', 'U20', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G35', 'Best Pop Vocal Album', 2014, 'Nominated', 'Grammys', 'U21', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G36', 'Best Pop Vocal Album', 2014, 'Nominated', 'Grammys', 'U8', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G37', 'Best Traditional Pop Vocal Album', 2014, 'Won', 'Grammys', 'U22', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G38', 'Best Traditional Pop Vocal Album', 2014, 'Nominated', 'Grammys', 'U23', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G39', 'Best Traditional Pop Vocal Album', 2014, 'Nominated', 'Grammys', 'U24', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G40', 'Best Traditional Pop Vocal Album', 2014, 'Nominated', 'Grammys', 'U25', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G41', 'Best Traditional Pop Vocal Album', 2014, 'Nominated', 'Grammys', 'U26', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G42', 'Best Dance Recording', 2014, 'Won', 'Grammys', 'U27', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G43', 'Best Dance Recording', 2014, 'Nominated', 'Grammys', 'U28', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G44', 'Best Dance Recording', 2014, 'Nominated', 'Grammys', 'U29', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G45', 'Best Dance Recording', 2014, 'Nominated', 'Grammys', 'U30', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G46', 'Best Dance Recording', 2014, 'Nominated', 'Grammys', 'U31', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G47', 'Best Dance/Electric Album', 2014, 'Won', 'Grammys', 'U32', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G48', 'Best Dance/Electric Album', 2014, 'Nominated', 'Grammys', 'U33', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G49', 'Best Dance/Electric Album', 2014, 'Nominated', 'Grammys', 'U34', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G50', 'Best Dance/Electric Album', 2014, 'Nominated', 'Grammys', 'U35', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G51', 'Best Dance/Electric Album', 2014, 'Nominated', 'Grammys', 'U36', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G52', 'Best Contemporary Instrumental Album', 2014, 'Won', 'Grammys', 'U37', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G53', 'Best Contemporary Instrumental Album', 2014, 'Nominated', 'Grammys', 'U38', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G54', 'Best Contemporary Instrumental Album', 2014, 'Nominated', 'Grammys', 'U39', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G55', 'Best Contemporary Instrumental Album', 2014, 'Nominated', 'Grammys', 'U40', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G56', 'Best Contemporary Instrumental Album', 2014, 'Nominated', 'Grammys', 'U41', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G57', 'Best Rock Performance', 2014, 'Won', 'Grammys', 'U42', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G58', 'Best Rock Performance', 2014, 'Nominated', 'Grammys', 'U43', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G59', 'Best Rock Performance', 2014, 'Nominated', 'Grammys', 'U44', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G60', 'Best Rock Performance', 2014, 'Nominated', 'Grammys', 'U45', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G61', 'Best Rock Performance', 2014, 'Nominated', 'Grammys', 'U46', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G62', 'Best Metal Performance', 2014, 'Won', 'Grammys', 'U47', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G63', 'Best Metal Performance', 2014, 'Nominated', 'Grammys', 'U48', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G64', 'Best Metal Performance', 2014, 'Nominated', 'Grammys', 'U49', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G65', 'Best Metal Performance', 2014, 'Nominated', 'Grammys', 'U50', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G66', 'Best Metal Performance', 2014, 'Nominated', 'Grammys', 'U51', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G67', 'Best Rock Song', 2014, 'Won', 'Grammys', 'U52', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G68', 'Best Rock Song', 2014, 'Nominated', 'Grammys', 'U45', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G69', 'Best Rock Song', 2014, 'Nominated', 'Grammys', 'U53', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G70', 'Best Rock Song', 2014, 'Nominated', 'Grammys', 'U43', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G71', 'Best Rock Song', 2014, 'Nominated', 'Grammys', 'U42', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G72', 'Best Rock Album', 2014, 'Won', 'Grammys', 'U6', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G73', 'Best Rock Album', 2014, 'Nominated', 'Grammys', 'U54', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G74', 'Best Rock Album', 2014, 'Nominated', 'Grammys', 'U55', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G75', 'Best Rock Album', 2014, 'Nominated', 'Grammys', 'U56', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G76', 'Best Rock Album', 2014, 'Nominated', 'Grammys', 'U57', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G77', 'Best Alternative Music Album', 2014, 'Won', 'Grammys', 'U58', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G78', 'Best Alternative Music Album', 2014, 'Nominated', 'Grammys', 'U59', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G79', 'Best Alternative Music Album', 2014, 'Nominated', 'Grammys', 'U60', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G80', 'Best Alternative Music Album', 2014, 'Nominated', 'Grammys', 'U61', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G81', 'Best Alternative Music Album', 2014, 'Nominated', 'Grammys', 'U42', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G82', 'Best R&B Performance', 2014, 'Won', 'Grammys', 'U62', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G83', 'Best R&B Performance', 2014, 'Nominated', 'Grammys', 'U64', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G84', 'Best R&B Performance', 2014, 'Nominated', 'Grammys', 'U95', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G85', 'Best R&B Performance', 2014, 'Nominated', 'Grammys', 'U96', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G86', 'Best R&B Performance', 2014, 'Nominated', 'Grammys', 'U63', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G87', 'Best Traditional R&B Performance', 2014, 'Won', 'Grammys', 'U97', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G88', 'Best Traditional R&B Performance', 2014, 'Nominated', 'Grammys', 'U98', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G89', 'Best Traditional R&B Performance', 2014, 'Nominated', 'Grammys', 'U99', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G90', 'Best Traditional R&B Performance', 2014, 'Nominated', 'Grammys', 'U100', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G91', 'Best Traditional R&B Performance', 2014, 'Nominated', 'Grammys', 'U101', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G92', 'Best R&B Song', 2014, 'Won', 'Grammys', 'U62', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G93', 'Best R&B Song', 2014, 'Nominated', 'Grammys', 'U63', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G94', 'Best R&B Song', 2014, 'Nominated', 'Grammys', 'U64', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G95', 'Best R&B Song', 2014, 'Nominated', 'Grammys', 'U65', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G96', 'Best R&B Song', 2014, 'Nominated', 'Grammys', 'U66', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G97', 'Best Urban Contemporary Album', 2014, 'Won', 'Grammys', 'U10', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G98', 'Best Urban Contemporary Album', 2014, 'Nominated', 'Grammys', 'U67', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G99', 'Best Urban Contemporary Album', 2014, 'Nominated', 'Grammys', 'U7', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G100', 'Best Urban Contemporary Album', 2014, 'Nominated', 'Grammys', 'U102', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G101', 'Best Urban Contemporary Album', 2014, 'Nominated', 'Grammys', 'U68', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G102', 'Best R&B Album', 2014, 'Won', 'Grammys', 'U69', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G103', 'Best R&B Album', 2014, 'Nominated', 'Grammys', 'U70', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G104', 'Best R&B Album', 2014, 'Nominated', 'Grammys', 'U71', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G105', 'Best R&B Album', 2014, 'Nominated', 'Grammys', 'U72', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G106', 'Best R&B Album', 2014, 'Nominated', 'Grammys', 'U73', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G107', 'Best Rap Performance', 2014, 'Won', 'Grammys', 'U74', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G108', 'Best Rap Performance', 2014, 'Nominated', 'Grammys', 'U103', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G109', 'Best Rap Performance', 2014, 'Nominated', 'Grammys', 'U104', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G110', 'Best Rap Performance', 2014, 'Nominated', 'Grammys', 'U105', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G111', 'Best Rap Performance', 2014, 'Nominated', 'Grammys', 'U106', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G112', 'Best Rap/Sung Collaboration', 2014, 'Won', 'Grammys', 'U107', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G113', 'Best Rap/Sung Collaboration', 2014, 'Nominated', 'Grammys', 'U108', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G114', 'Best Rap/Sung Collaboration', 2014, 'Nominated', 'Grammys', 'U109', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G115', 'Best Rap/Sung Collaboration', 2014, 'Nominated', 'Grammys', 'U110', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G116', 'Best Rap/Sung Collaboration', 2014, 'Nominated', 'Grammys', 'U76', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G117', 'Best Rap Song', 2014, 'Won', 'Grammys', 'U74', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G118', 'Best Rap Song', 2014, 'Nominated', 'Grammys', 'U75', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G119', 'Best Rap Song', 2014, 'Nominated', 'Grammys', 'U76', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G120', 'Best Rap Song', 2014, 'Nominated', 'Grammys', 'U77', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G121', 'Best Rap Song', 2014, 'Nominated', 'Grammys', 'U78', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G122', 'Best Rap Album', 2014, 'Won', 'Grammys', 'U79', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G123', 'Best Rap Album', 2014, 'Nominated', 'Grammys', 'U80', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G124', 'Best Rap Album', 2014, 'Nominated', 'Grammys', 'U81', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G125', 'Best Rap Album', 2014, 'Nominated', 'Grammys', 'U82', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G126', 'Best Rap Album', 2014, 'Nominated', 'Grammys', 'U83', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G127', 'Best Rap Album', 2014, 'Nominated', 'Grammys', 'U84', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G128', 'Best Country Solo Performance', 2014, 'Won', 'Grammys', 'U111', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G129', 'Best Country Solo Performance', 2014, 'Nominated', 'Grammys', 'U88', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G130', 'Best Country Solo Performance', 2014, 'Nominated', 'Grammys', 'U112', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G131', 'Best Country Solo Performance', 2014, 'Nominated', 'Grammys', 'U87', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G132', 'Best Country Solo Performance', 2014, 'Nominated', 'Grammys', 'U113', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G133', 'Best Country Duo/Group Performance', 2014, 'Won', 'Grammys', 'U114', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G134', 'Best Country Duo/Group Performance', 2014, 'Nominated', 'Grammys', 'U115', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G135', 'Best Country Duo/Group Performance', 2014, 'Nominated', 'Grammys', 'U116', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G136', 'Best Country Duo/Group Performance', 2014, 'Nominated', 'Grammys', 'U89', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G137', 'Best Country Duo/Group Performance', 2014, 'Nominated', 'Grammys', 'U117', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G138', 'Best Country Song', 2014, 'Won', 'Grammys', 'U85', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G139', 'Best Country Song', 2014, 'Nominated', 'Grammys', 'U86', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G140', 'Best Country Song', 2014, 'Nominated', 'Grammys', 'U87', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G141', 'Best Country Song', 2014, 'Nominated', 'Grammys', 'U88', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G142', 'Best Country Song', 2014, 'Nominated', 'Grammys', 'U89', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G143', 'Best Country Album', 2014, 'Won', 'Grammys', 'U90', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G144', 'Best Country Album', 2014, 'Nominated', 'Grammys', 'U91', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G145', 'Best Country Album', 2014, 'Nominated', 'Grammys', 'U92', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G146', 'Best Country Album', 2014, 'Nominated', 'Grammys', 'U93', NULL);
INSERT INTO Honor (AwardID, AwardName, YearGiven, NominatedWon, ShowName, WorkID, PersonName) VALUES ('G147', 'Best Country Album', 2014, 'Nominated', 'Grammys', 'U94', NULL);