CREATE TABLE Locations(WorkID VARCHAR(200), Location VARCHAR(500), FilmedOrFiction VARCHAR(50), Latitude REAL NULL, Longitude REAL NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M1', 'New York', 'Filmed', 40.760411, -73.9874575);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M2', 'Los Angeles', 'Filmed', 34.0211224, -118.3964665);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M2', 'Morocco', 'Filmed', 31.791702, -7.09262);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M3', 'Texas', 'Filmed', 29.7221099, -95.3896395);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M4', 'Germany', 'Filmed', 51.1506269, 14.968707);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M5', 'Britain', 'Filmed', 51.9965946, -0.7430945);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M6', 'Georgia (state)', 'Filmed', 33.7496117, -84.3883653);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M6', 'Alabama', 'Filmed', 32.4055203, -87.0184779);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M7', 'Britain', 'Filmed', 52.205337, 0.121817);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M8', 'Los Angeles', 'Filmed', 34.3916641, -118.542586);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M9', 'Pennsylvania', 'Filmed', 40.4406248, -79.9958864);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M10', 'New York', 'Filmed', 40.8447819, -73.8648268);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M11', 'Belgium', 'Filmed', 50.5838832, 5.4996297);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M12', 'Missouri', 'Filmed', 37.3058839, -89.5181476);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M13', 'Oregon', 'Filmed', 42.86765839, -122.1689836);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M13', 'Washington', 'Filmed', 45.6387281, -122.6614861);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M14', 'Massachusetts', 'Filmed', 41.9555556, -70.6647222);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M15', 'London', 'Filmed', 51.1287719, 1.3233915);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M16', 'Los Angeles', 'Filmed', 34.0980352, -118.3176632);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M17', 'Los Angeles', 'Filmed', 34.1834293, -117.2674959);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M23', 'Poland', 'Filmed', 51.7592485, 19.4559833);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M24', 'Russia', 'Filmed', 67.933333, 32.916667);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M25', 'Georgia', 'Filmed', 41.9442736, 42.0458091);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M26', 'Mauritania', 'Filmed', 17.2990071, -7.0216191);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M27', 'Argentina', 'Filmed', -26.0730798, -65.976052);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M28', 'Hong Kong', 'Filmed', 22.3001365, 114.1724524);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M28', 'Moscow', 'Filmed', 55.755826, 37.6173);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M29', 'Chicago', 'Filmed', 41.8781136, -87.6297982);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M30', 'Vietnam', 'Filmed', 14.058324, 108.277199);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M31', 'France', 'Filmed', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M31', 'Brazil', 'Filmed', -19.4959312, -41.0713439);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M32', 'Congo', 'Filmed', -0.0649884, 29.5107708);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M33', 'Canandaigua', 'Filmed', 42.887535, -77.2816984);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M34', 'Poland', 'Filmed', 51.919438, 19.145136);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M35', 'Poland', 'Filmed', 51.90546027, 19.08608449);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M36', 'Mexico', 'Filmed', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M37', 'North Dakota', 'Filmed', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M38', 'Britain', 'Filmed', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M39', 'Israel', 'Filmed', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M40', 'Britain', 'Filmed', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M41', 'France', 'Filmed', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M41', 'China', 'Filmed', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M42', 'Switzerland', 'Filmed', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M43', 'United States', 'Filmed', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M44', 'Britain', 'Filmed', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M45', 'New Orleans', 'Filmed', 29.9584426, -90.0644107);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M45', 'Louisiana', 'Filmed', 29.9512044, -90.1520889);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M46', 'Salem', 'Filmed', 42.5230427, -70.8961265);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M46', 'Worcester', 'Filmed', 42.2731, -71.802);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M47', 'Malta', 'Filmed', 35.889167, 14.529444);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M48', 'Louisiana', 'Filmed', 29.9510658, -90.0715323);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M49', 'Britain', 'Filmed', 51.4071242, -0.4628129);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M49', 'Arizona', 'Filmed', 36.9388464, -111.4847167);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M50', 'Los Angeles', 'Filmed', 34.0553468, -118.2499213);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M50', 'Shanghai', 'Filmed', 31.297803, 121.514516);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M51', 'Nebraska', 'Filmed', 40.810556, -96.680278);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M51', 'Montana', 'Filmed', 45.7832856, -108.5006904);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M51', 'Wyoming', 'Filmed', 43.0759678, -107.2902839);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M51', 'South Dakota', 'Filmed', 43.8889257, -103.4793019);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M52', 'Britain', 'Filmed', 54.6483191, -5.6891603);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M53', 'New Jersey', 'Filmed', 40.9731536, -73.9615262);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M53', 'New York', 'Filmed', 40.757719, -73.96609);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M54', 'New York', 'Filmed', 40.7663786, -73.9696834);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M54', 'San Francisco', 'Filmed', 37.769531, -122.4493727);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M55', 'Oklahoma', 'Filmed', 36.7473114, -95.9808179);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M55', 'Los Angeles', 'Filmed', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M56', 'Greece', 'Filmed', 36.8870432, 22.2329977);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M62', 'Southern California', 'Filmed', 33.8076345, -117.9221928);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M63', 'South Africa', 'Filmed', -29.75, 29.25);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M64', 'Mexico', 'Filmed', 32.3392824, -117.0522882);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M65', 'New Zealand', 'Filmed', -41.3185667, 174.8134826);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M66', 'New Mexico', 'Filmed', 35.1486276, -106.5898172);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M67', 'New York', 'Filmed', 40.7299739, -74.0005241);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M68', 'Sydney', 'Filmed', -33.8943803, 151.2329905);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M69', 'United States', 'Filmed', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M70', 'Canada', 'Filmed', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M71', 'Netherlands', 'Filmed', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M72', 'Canada', 'Filmed', 51.0486151, -114.0708459);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M73', 'Britain', 'Filmed', 50.335656, -4.202409);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M75', 'United States', 'Filmed', 34.0522342, -118.2436849);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M76', 'Australia', 'Filmed', -25.274398, 133.775136);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M77', 'New York', 'Filmed', 40.7308228, -73.997332);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M78', 'New Zealand', 'Filmed', -37.8720905, 175.6829096);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M79', 'Australia', 'Filmed', -33.8935457, 151.2268194);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M80', 'London', 'Filmed', 51.3817001, -0.5923196);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M81', 'London', 'Filmed', 51.810419, -0.5622214);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M82', 'Los Angeles', 'Filmed', 33.9015371, -118.3839484);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M82', 'Cleveland', 'Filmed', 41.5020605, -81.6983857);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M82', 'Washington D.C.', 'Filmed', 38.9071923, -77.0368707);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M83', 'Canada', 'Filmed', 49.2460339, -122.543159);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M84', 'Canada', 'Filmed', 45.404236, -74.0379599);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('S1', 'New York', 'Filmed', 40.7735954, -73.9840268);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('S2', 'New York', 'Filmed', 40.7630755, -73.9846348);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('S3', 'New York', 'Filmed', 40.760379, -73.986725);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('S4', 'New York', 'Filmed', 40.7591625, -73.988378);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('S5', 'New York', 'Filmed', 40.760379, -73.986725);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('S6', 'New York', 'Filmed', 40.761038, -73.987015);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('S7', 'New York', 'Filmed', 40.760411, -73.9874575);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('S8', 'New York', 'Filmed', 40.7576308, -73.990748);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('S9', 'New York', 'Filmed', 40.7588055, -73.9914472);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('S10', 'New York', 'Filmed', 40.760411, -73.9874575);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('S11', 'New York', 'Filmed', 40.761637, -73.98844);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('S12', 'New York', 'Filmed', 40.7591625, -73.988378);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('S13', 'New York', 'Filmed', 40.7585393, -73.988826);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('S14', 'New York', 'Filmed', 40.7585393, -73.988826);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('S15', 'New York', 'Filmed', 40.7522456, -73.9766439);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('S16', 'New York', 'Filmed', 40.7576308, -73.990748);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('S17', 'New York', 'Filmed', 40.761637, -73.98844);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('S18', 'New York', 'Filmed', 40.7585393, -73.988826);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('S19', 'New York', 'Filmed', 40.759011, -73.9844722);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('S20', 'New York', 'Filmed', 40.7591625, -73.988378);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('S21', 'New York', 'Filmed', 40.759011, -73.9844722);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('S22', 'New York', 'Filmed', 40.7591625, -73.988378);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('S23', 'New York', 'Filmed', 40.7609826, -73.9907693);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('S24', 'New York', 'Filmed', 40.7591625, -73.988378);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('S25', 'New York', 'Filmed', 40.7621174, -73.9779698);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('S26', 'New York', 'Filmed', 40.7585393, -73.988826);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('S27', 'New York', 'Filmed', 40.7576308, -73.990748);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T1', 'Los Angeles', 'Filmed', 34.036837, -118.409972);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T2', 'Burbank', 'Filmed', 34.1498296, -118.3405987);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T3', 'New York', 'Filmed', 40.830347, -73.949329);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T4', 'New York', 'Filmed', 40.7566549, -73.9245605);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T4', 'New York', 'Filmed', 41.0533431, -73.9756478);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T5', 'Los Angeles', 'Filmed', 34.0672279, -118.1667405);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T5', 'Carson', 'Filmed', 33.8631209, -118.254227);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T6', 'Baltimore', 'Filmed', 39.2903848, -76.6121893);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T7', 'New Mexico', 'Filmed', 35.1261047, -106.5365641);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T8', 'Britain', 'Filmed', 51.3265901, -1.360666);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T9', 'Britain', 'Filmed', 54.604221, -5.9110601);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T9', 'Iceland', 'Filmed', 64.4333333, -15.5);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T9', 'Croatia', 'Filmed', 43.6289935, 16.0510869);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T9', 'Spain', 'Filmed', 37.3845491, -5.9912846);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T9', 'Morocco', 'Filmed', 30.9335436, -6.937016);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T9', 'Scotland', 'Filmed', 56.185096, -4.050264);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T10', 'Baltimore', 'Filmed', 39.319783, -76.609043);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T11', 'Los Angeles', 'Filmed', 34.0555136, -118.2608743);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T12', 'New Orleans', 'Filmed', 29.9420901, -90.1868973);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T13', 'New York', 'Filmed', 40.7677429, -73.990731);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T14', 'New York', 'Filmed', 40.7670735, -73.9940902);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T15', 'Los Angeles', 'Filmed', 34.10111, -118.339822);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T16', 'Los Angeles', 'Filmed', 34.0760139, -118.3584537);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T17', 'New York', 'Filmed', 40.7589426, -73.9793564);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T18', 'New York', 'Filmed', 40.7589426, -73.9793564);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T19', 'Canada', 'Filmed', 51.0486151, -114.0708459);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T20', 'New Orleans', 'Filmed', 29.9510658, -90.0715323);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T21', 'Louisiana', 'Filmed', 30.1010323, -90.9928773);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T22', 'Britain', 'Filmed', 51.5063728, -0.0887011);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T23', 'New Orleans', 'Filmed', 29.9198733, -90.1244821);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T24', 'Belgium', 'Filmed', 51.2050129, 3.2230223);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T25', 'New York', 'Filmed', 40.7372987, -73.9946445);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T26', 'Virginia', 'Filmed', 37.5325498, -77.4287644);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T27', 'New York', 'Filmed', 40.739868, -73.9837494);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T28', 'Britain', 'Filmed', 51.5264284, -0.1369005);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T29', 'Georgia (state)', 'Filmed', 33.7489954, -84.3879824);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T30', 'Worldwide', 'Filmed', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T31', 'Los Angeles', 'Filmed', 34.0760139, -118.3584537);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T32', 'New York', 'Filmed', 40.7351297, -73.9944837);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T33', 'United States', 'Filmed', 34.0734289, -118.378875);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T34', 'United States', 'Filmed', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T35', 'Los Angeles', 'Filmed', 34.1397694, -118.3505779);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T36', 'Los Angeles', 'Filmed', 34.0416839, -118.263076);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T36', 'New York', 'Filmed', 40.7585256, -73.9717856);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T37', 'Britain', 'Filmed', 51.360163, 1.432038);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T38', 'Britain', 'Filmed', 51.4183389, -0.2206288);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T39', 'Chicago', 'Filmed', 41.852949, -87.7098029);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T39', 'Los Angeles', 'Filmed', 34.152129, -118.3365819);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T40', 'New York', 'Filmed', 40.7319419, -73.956172);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T41', 'New York', 'Filmed', 40.7566549, -73.9245605);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T42', 'Los Angeles', 'Filmed', 34.0522342, -118.2436849);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T43', 'Pasadena', 'Filmed', 34.1483868, -118.1442855);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T43', 'Los Angeles', 'Filmed', 34.1446003, -118.392351);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T44', 'Los Angeles', 'Filmed', 34.0972964, -118.3219312);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T45', 'New York', 'Filmed', 40.7294018, -73.9065883);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T47', 'California', 'Filmed', 34.0177659, -118.4015528);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T48', 'North Carolina', 'Filmed', 35.2270869, -80.8431267);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T49', 'California', 'Filmed', 34.1285895, -118.1143535);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T49', 'Los Angeles', 'Filmed', 34.0972964, -118.3219312);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T50', 'Britain', 'Filmed', 52.532549, -2.4212077);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T51', 'Britain', 'Filmed', 51.4876272, -0.2671732);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T53', 'Los Angeles', 'Filmed', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T54', 'Portland', 'Filmed', 45.5230622, -122.6764816);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T55', 'Los Angeles', 'Filmed', 34.1446003, -118.392351);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T56', 'Los Angeles', 'Filmed', 34.1498296, -118.3405987);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T57', 'Los Angeles', 'Filmed', 34.0177659, -118.4015528);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M1', 'New York', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M2', 'Iraq', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M2', 'Texas', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M3', 'Texas', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M4', 'Zubrowka', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M5', 'Britain', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M6', 'Alabama', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M7', 'Britain', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M8', 'New York', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M9', 'Pennsylvania', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M10', 'New York', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M11', 'Belgium', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M12', 'Missouri', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M13', 'Oregon', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M13', 'California', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M14', 'Indiana', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M15', 'The Woods', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M16', 'Los Angeles', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M17', 'Los Angeles', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M18', 'San Fransokyo', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M19', 'Cheesebridge', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M20', 'Berk', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M21', 'Ireland', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M22', 'Japan', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M23', 'Poland', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M24', 'Russia', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M25', 'Georgia', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M26', 'Timbuktu', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M27', 'Argentina', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M28', 'Hong Kong', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M28', 'Moscow', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M29', 'Chicago', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M30', 'Vietnam', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M31', 'Brazil', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M32', 'Congo', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M33', 'Canandaigua', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M34', 'Poland', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M35', 'Poland', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M36', 'Mexico', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M37', 'North Dakota', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M38', 'Britain', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M39', 'Israel', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M40', 'Britain', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M41', 'China', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M42', 'Switzerland', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M43', 'United States', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M44', 'Britain', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M45', 'New Orleans', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M46', 'New Jersey', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M47', 'Indian Ocean', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M48', 'Texas', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M49', 'Space', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M50', 'Los Angeles', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M51', 'Nebraska', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M51', 'South Dakota', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M51', 'Wyoming', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M52', 'Britain', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M53', 'New York', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M54', 'New York', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M54', 'San Francisco', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M55', 'Oklahoma', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M56', 'France', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M57', 'Arendelle', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M58', 'Earth', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M59', 'United States', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M60', 'Belgium', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M61', 'Japan', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M62', 'London', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M63', 'South Africa', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M64', 'Indian Ocean', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M65', 'Middle Earth', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M66', 'Afghanistan', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M67', 'New York', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M68', 'New York', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M69', 'United States', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M70', 'Norway', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M71', 'Netherlands', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M72', 'Texas', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M72', 'Space', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M73', 'Britain', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M74', 'Lego Universe', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M76', 'United States', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M76', 'Australia', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M76', 'Europe', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M77', 'New York', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M78', 'Middle Earth', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M79', 'California', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M79', 'Germany', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M79', 'Japan', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M80', 'Nova Empire', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M81', 'A Faraway Land', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M81', 'The Moors', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M82', 'Washington D.C.', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M83', 'San Francisco', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M84', 'New York', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M84', 'China', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M84', 'Russia', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M84', 'Washington D.C.', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M84', 'Paris', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('M84', 'Vietnam', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('S1', 'New York', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('S2', 'Washington D.C.', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('S3', 'New York', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('S4', 'New York', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('S5', 'Ireland', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('S6', 'London', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('S7', 'New York', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('S8', 'Agrabah', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('S9', 'New York', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('S10', 'Chicago', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('S11', 'Ireland', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('S12', 'St. Louis', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('S13', 'Ilyria', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('S14', 'Germany', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('S16', 'Oklahoma', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('S18', 'Britain', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('S19', 'Philadelphia', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('S20', 'New York', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('S21', 'Philadelphia', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('S23', 'New York', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('S24', 'Iowa', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('S25', 'Germany', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('S26', 'New York', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('S27', 'New York', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T1', 'Los Angeles', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T2', 'Pasadena', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T3', 'New York', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T4', 'New York', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T5', 'Palo Alto', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T6', 'Washington D.C.', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T7', 'New Mexico', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T8', 'Britain', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T9', 'Westeros', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T10', 'Washington D.C.', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T11', 'New York', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T12', 'New Orleans', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T13', 'New York', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T14', 'New York', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T15', 'Los Angeles', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T16', 'Los Angeles', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T17', 'New York', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T17', 'New York', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T19', 'Minnesota', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T20', 'New Orleans', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T21', 'Texas', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T22', 'Britain', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T23', 'New Orleans', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T24', 'Britain', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T25', 'New York', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T26', 'United States', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T27', 'Washington D.C.', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T28', 'Britain', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T36', 'New York', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T37', 'Britain', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T38', 'Los Angeles', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T39', 'Chicago', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T40', 'New York', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T41', 'New York', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T42', 'Chicago', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T43', 'Indiana', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T44', 'New York', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T45', 'Chicago', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T47', 'Missouri', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T48', 'Washington D.C.', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T49', 'Washington D.C.', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T50', 'London', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T51', 'New York', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T53', 'Texas', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T53', 'New York', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T54', 'Portland', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T55', 'New York', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T56', 'Sonoma', 'Fiction', NULL, NULL);
INSERT INTO Locations (WorkID, Location, FilmedOrFiction, Latitude, Longitude) VALUES ('T57', 'Los Angeles', 'Fiction', NULL, NULL);