CREATE TABLE Music( WorkID VARCHAR(50), Title VARCHAR(2000) NULL, Artist VARCHAR(100), isSingle VARCHAR(3) NOT NULL, EligibilityYear INT NULL, Genre VARCHAR(100) NULL, ReleaseYear INT NULL);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U1', 'Stay with Me (Darkchild Version)', 'Sam Smith', 'Yes', 2015, 'Pop', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U2', 'Fancy', 'Iggy Azalea', 'Yes', 2015, 'Pop', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U2', 'Fancy', 'Charli XCX', 'Yes', 2015, 'Pop', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U3', 'Chandelier', 'Sia', 'Yes', 2015, 'Pop', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U4', 'Shake It Off', 'Taylor Swift', 'Yes', 2015, 'Pop', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U5', 'All About That Bass', 'Meghan Trainor', 'Yes', 2015, 'Pop', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U6', 'Morning Phase', 'Beck', 'No', 2015, 'Rock', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U7', 'Beyonce', 'Beyonce', 'No', 2015, 'R&B', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U8', 'x', 'Ed Sheeran', 'No', 2015, 'Pop', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U9', 'In the Lonely Hour', 'Sam Smith', 'No', 2015, 'Pop', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U10', 'G I R L', 'Pharrell Williams', 'No', 2015, 'R&B', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U11', 'Take Me to Church', 'Andrew Hozier-Byrne', 'Yes', 2015, 'Rock', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U12', 'Happy (Live)', 'Pharrell Williams', 'Yes', 2015, 'Pop', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U13', 'All of Me (Live)', 'John Legend', 'Yes', 2015, 'R&B', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U14', 'Say Something', 'A Great Big World', 'Yes', 2015, 'Pop', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U14', 'Say Something', 'Christina Aguilera', 'Yes', 2015, 'Pop', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U15', 'A Sky Full of Stars', 'Coldplay', 'Yes', 2015, 'Pop', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U16', 'Bang Bang', 'Jessie J', 'Yes', 2015, 'Pop', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U16', 'Bang Bang', 'Ariana Grande', 'Yes', 2015, 'Pop', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U16', 'Bang Bang', 'Nicki Minaj', 'Yes', 2015, 'Pop', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U17', 'Dark Horse', 'Katy Perry', 'Yes', 2015, 'Pop', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U17', 'Dark Horse', 'Juicy J', 'Yes', 2015, 'Pop', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U18', 'Ghost Stories', 'Coldplay', 'No', 2015, 'Pop', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U19', 'Bangerz', 'Miley Cyrus', 'No', 2015, 'Pop', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U20', 'My Everything', 'Ariana Grande', 'No', 2015, 'Pop', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U21', 'Prism', 'Katy Perry', 'No', 2015, 'Pop', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U22', 'Cheek to Cheek', 'Tony Bennett', 'No', 2015, 'Pop', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U22', 'Cheek to Cheek', 'Lady Gaga', 'No', 2015, 'Pop', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U23', 'Nostalgia', 'Annie Lennox', 'No', 2015, 'Pop', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U24', 'Night Songs', 'Barry Manilow', 'No', 2015, 'Pop', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U25', 'Sending You a Little Christmas', 'Johnny Mathis', 'No', 2015, 'Pop', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U26', 'Partners', 'Barbra Streisand', 'No', 2015, 'Pop', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U27', 'Rather Be', 'Clean Bandit', 'Yes', 2015, 'Dance/Electronica', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U27', 'Rather Be', 'Jess Glynne', 'Yes', 2015, 'Dance/Electronica', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U28', 'Never Say Never', 'Basement', 'Yes', 2015, 'Dance/Electronica', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U28', 'Never Say Never', 'ETML', 'Yes', 2015, 'Dance/Electronica', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U29', 'F For You', 'Disclosure', 'Yes', 2015, 'Dance/Electronica', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U29', 'F For You', 'Mary J. Blige', 'Yes', 2015, 'Dance/Electronica', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U30', 'I Got U', 'Duke Dumont', 'Yes', 2015, 'Dance/Electronica', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U30', 'I Got U', 'Jax Jones', 'Yes', 2015, 'Dance/Electronica', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U31', 'Faded', 'Zhu', 'Yes', 2015, 'Dance/Electronica', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U32', 'Syro', 'Aphex Twin', 'No', 2015, 'Dance/Electronica', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U33', 'while(1<2)', 'deadmau5', 'No', 2015, 'Dance/Electronica', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U34', 'Nabuma Rubberband', 'Little Dragon', 'No', 2015, 'Dance/Electronica', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U35', 'Do It Again', 'Royksopp', 'No', 2015, 'Dance/Electronica', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U35', 'Do It Again', 'Robyn', 'No', 2015, 'Dance/Electronica', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U36', 'Damage Control', 'Mat Zo', 'No', 2015, 'Dance/Electronica', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U37', 'Bass & Mandolin', 'Chris Thile', 'No', 2015, 'Contemporary Instrumental', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U37', 'Bass & Mandolin', 'Edgar Meyer', 'No', 2015, 'Contemporary Instrumental', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U38', 'Wild Heart', 'Mindi Abair', 'No', 2015, 'Contemporary Instrumental', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U39', 'Slam Dunk', 'Gerald Albright', 'No', 2015, 'Contemporary Instrumental', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U40', 'Nathan East', 'Nathan East', 'No', 2015, 'Contemporary Instrumental', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U41', 'Jazz Funk Soul', 'Jeff Lorber', 'No', 2015, 'Contemporary Instrumental', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U41', 'Jazz Funk Soul', 'Chuck Loeb', 'No', 2015, 'Contemporary Instrumental', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U41', 'Jazz Funk Soul', 'Everette Harp', 'No', 2015, 'Contemporary Instrumental', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U42', 'Lazaretto', 'Jack White', 'Yes', 2015, 'Rock & Alternative', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U43', 'Gimme Something Good', 'Ryan Adams', 'Yes', 2015, 'Rock', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U44', 'Do I Wanna Know?', 'Arctic Monkeys', 'Yes', 2015, 'Rock', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U45', 'Blue Moon', 'Beck', 'Yes', 2015, 'Rock', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U46', 'Fever', 'The Black Keys', 'Yes', 2015, 'Rock', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U47', 'The Last in Line', 'Tenacious D', 'Yes', 2015, 'Rock', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U48', 'Neon Knights', 'Anthrax', 'Yes', 2015, 'Rock', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U49', 'High Road', 'Mastodon', 'Yes', 2015, 'Rock', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U50', 'Heartbreaker', 'Motorhead', 'Yes', 2015, 'Rock', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U51', 'The Negative One', 'Slipknot', 'Yes', 2015, 'Rock', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U52', 'Ain''t It Fun', 'Paramore', 'Yes', 2015, 'Rock', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U53', 'Fever', 'The Black Keys', 'Yes', 2015, 'Rock', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U54', 'Ryan Adams', 'Ryan Adams', 'No', 2015, 'Rock', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U55', 'Turn Blue', 'The Black Keys', 'No', 2015, 'Rock', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U56', 'Hypnotic Eye', 'Tom Petty', 'No', 2015, 'Rock', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U56', 'Hypnotic Eye', 'The Heartbreakers', 'No', 2015, 'Rock', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U57', 'Songs of Innocence', 'U2', 'No', 2015, 'Rock', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U58', 'St. Vincent', 'St. Vincent', 'No', 2015, 'Alternative', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U59', 'This Is All Yours', 'alt-J', 'No', 2015, 'Alternative', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U60', 'Reflektor', 'Arcade Fire', 'No', 2015, 'Alternative', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U61', 'Melophobia', 'Cage the Elephant', 'No', 2015, 'Alternative', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U62', 'Drunk in Love', 'Beyonce', 'Yes', 2015, 'R&B', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U62', 'Drunk in Love', 'Jay Z', 'Yes', 2015, 'R&B', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U63', 'Good Kisser', 'Usher', 'Yes', 2015, 'R&B', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U64', 'New Flame', 'Chris Brown', 'Yes', 2015, 'R&B', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U64', 'New Flame', 'Usher', 'Yes', 2015, 'R&B', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U64', 'New Flame', 'Rick Ross', 'Yes', 2015, 'R&B', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U65', 'Options', 'Luke James', 'Yes', 2015, 'R&B', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U66', 'The Worst', 'Jhene Aiko', 'Yes', 2015, 'R&B', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U67', 'Sail Out', 'Jhene Aiko', 'No', 2015, 'R&B', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U68', 'Mali is...', 'Mali Music', 'No', 2015, 'R&B', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U69', 'Love, Marriage & Divorce', 'Toni Braxton', 'No', 2015, 'R&B', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U69', 'Love, Marriage & Divorce', 'Babyface', 'No', 2015, 'R&B', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U70', 'Islander', 'Bernhoft', 'No', 2015, 'R&B', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U71', 'Lift Your Spirit', 'Aloe Blacc', 'No', 2015, 'R&B', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U72', 'Black Radio 2', 'Robert Glasper Experiment', 'No', 2015, 'R&B', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U73', 'Give The People What They Want', 'Sharon Jones', 'No', 2015, 'R&B', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U73', 'Give The People What They Want', 'The Dap-Kings', 'No', 2015, 'R&B', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U74', 'i', 'Kendrick Lamar', 'Yes', 2015, 'Rap', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U75', 'Anaconda', 'Nicki Minaj', 'Yes', 2015, 'Rap', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U76', 'Bound 2', 'Kanye West', 'Yes', 2015, 'Rap', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U76', 'Bound 2', 'Charlie Wilson', 'Yes', 2015, 'Rap', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U77', 'Me Dem Boyz', 'Wiz Khalifa', 'Yes', 2015, 'Rap', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U78', '0 to 100 / The Catch Up', 'Drake', 'Yes', 2015, 'Rap', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U79', 'The MArshall Mathers LP 2', 'Eminem', 'No', 2015, 'Rap', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U80', 'The New Classic', 'Iggy Azalea ', 'No', 2015, 'Rap', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U81', 'Because the Internet', 'Childish Gambino', 'No', 2015, 'Rap', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U82', 'Nobody''s Smiling', 'Common', 'No', 2015, 'Rap', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U83', 'Oxymoron', 'ScHoolboy Q', 'No', 2015, 'Rap', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U84', 'Blacc Hollywood', 'Wiz Khalifa', 'No', 2015, 'Rap', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U85', 'I''m Not Gonna Miss You', 'Glen Campbell', 'Yes', 2015, 'Country', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U86', 'American Kids', 'Kenny Chesney', 'Yes', 2015, 'Country', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U87', 'Automatic', 'Miranda Lambert', 'Yes', 2015, 'Country', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U88', 'Give Me Back My Hometown', 'Eric Church', 'Yes', 2015, 'Country', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U89', 'Meanwhile Back at Mama''s', 'Tim McGraw', 'Yes', 2015, 'Country', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U89', 'Meanwhile Back at Mama''s', 'Faith Hill', 'Yes', 2015, 'Country', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U90', 'Platinum', 'Miranda Lambert', 'No', 2015, 'Country', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U91', 'Riser', 'Dierks Bentley', 'No', 2015, 'Country', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U92', 'The Outsiders', 'Eric Church', 'No', 2015, 'Country', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U93', '12 Stories', 'Brandy Clark', 'No', 2015, 'Country', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U94', 'The Way I''m Livin''', 'Lee Ann Womack', 'No', 2015, 'Country', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U95', 'It''s Your World', 'Jennifer Hudson', 'Yes', 2015, 'R&B', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U95', 'It''s Your World', 'R. Kelly', 'Yes', 2015, 'R&B', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U96', 'Like This', 'Ledisi', 'Yes', 2015, 'R&B', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U97', 'Jesus Children', 'Robert Glasper Experiment', 'Yes', 2015, 'R&B', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U97', 'Jesus Children', 'Lalah Hathaway', 'Yes', 2015, 'R&B', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U97', 'Jesus Children', 'Malcolm Jamal Warner', 'Yes', 2015, 'R&B', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U98', 'As', 'Marsha Ambrosius', 'Yes', 2015, 'R&B', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U98', 'As', 'Anthony Hamilton', 'Yes', 2015, 'R&B', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U99', 'I.R.S.', 'Angie Fisher', 'Yes', 2015, 'R&B', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U100', 'Nobody', 'Kem', 'Yes', 2015, 'R&B', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U101', 'Hold Up Wait a Minute (Woo Woo)', 'Antonique Smith', 'Yes', 2015, 'R&B', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U102', 'X', 'Chris Brown', 'No', 2015, 'R&B', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U103', 3005, 'Childish Gambino', 'Yes', 2015, 'Rap', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U104', '0 to 100 / The Catch Up', 'Drake', 'Yes', 2015, 'Rap', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U105', 'Rap God', 'Eminem', 'Yes', 2015, 'Rap', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U106', 'All I Need Is You', 'Lecrae', 'Yes', 2015, 'Rap', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U107', 'The Monster', 'Eminem', 'Yes', 2015, 'Rap', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U107', 'The Monster', 'Rihanna', 'Yes', 2015, 'Rap', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U108', 'Blak Majik', 'Common', 'Yes', 2015, 'Rap', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U108', 'Blak Majik', 'Jhene Aiko', 'Yes', 2015, 'Rap', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U109', 'Tuesday', 'ILoveMakonnen', 'Yes', 2015, 'Rap', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U109', 'Tuesday', 'Drake', 'Yes', 2015, 'Rap', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U110', 'Studio', 'Schoolboy Q', 'Yes', 2015, 'Rap', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U110', 'Studio', 'BJ the Chicago Kid', 'Yes', 2015, 'Rap', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U111', 'Something in the Water', 'Carrie Underwood', 'Yes', 2015, 'Country', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U112', 'Invisible', 'Hunter Hayes', 'Yes', 2015, 'Country', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U113', 'Cop Car', 'Keith Urban', 'Yes', 2015, 'Country', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U114', 'Gentle on My Mind', 'The Band Perry', 'Yes', 2015, 'Country', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U115', 'Somethin'' Bad', 'Miranda Lambert', 'Yes', 2015, 'Country', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U115', 'Somethin'' Bad', 'Carrie Underwood', 'Yes', 2015, 'Country', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U116', 'Day Drinking', 'Little Big Town', 'Yes', 2015, 'Country', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U117', 'Raise ''Em Up', 'Keith Urban', 'Yes', 2015, 'Country', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U117', 'Raise ''Em Up', 'Eric Church', 'Yes', 2015, 'Country', 2014);