CREATE TABLE Music( WorkID VARCHAR(50), Title VARCHAR(2000) NULL, Artist VARCHAR(100), isSingle BIT NOT NULL, EligibilityYear INT NULL, Genre VARCHAR(100) NULL, ReleaseYear INT NULL);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U1', 'Stay with Me (Darkchild Version)', 'Sam Smith', 1, 2015, 'Pop', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U2', 'Fancy', 'Iggy Azalea', 1, 2015, 'Pop', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U2', 'Fancy', 'Charli XCX', 1, 2015, 'Pop', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U3', 'Chandelier', 'Sia', 1, 2015, 'Pop', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U4', 'Shake It Off', 'Taylor Swift', 1, 2015, 'Pop', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U5', 'All About That Bass', 'Meghan Trainor', 1, 2015, 'Pop', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U6', 'Morning Phase', 'Beck', 0, 2015, 'Rock', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U7', 'Beyonce', 'Beyonce', 0, 2015, 'R&B', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U8', 'x', 'Ed Sheeran', 0, 2015, 'Pop', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U9', 'In the Lonely Hour', 'Sam Smith', 0, 2015, 'Pop', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U10', 'G I R L', 'Pharrell Williams', 0, 2015, 'R&B', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U11', 'Take Me to Church', 'Andrew Hozier-Byrne', 1, 2015, 'Rock', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U12', 'Happy (Live)', 'Pharrell Williams', 1, 2015, 'Pop', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U13', 'All of Me (Live)', 'John Legend', 1, 2015, 'R&B', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U14', 'Say Something', 'A Great Big World', 1, 2015, 'Pop', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U14', 'Say Something', 'Christina Aguilera', 1, 2015, 'Pop', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U15', 'A Sky Full of Stars', 'Coldplay', 1, 2015, 'Pop', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U16', 'Bang Bang', 'Jessie J', 1, 2015, 'Pop', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U16', 'Bang Bang', 'Ariana Grande', 1, 2015, 'Pop', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U16', 'Bang Bang', 'Nicki Minaj', 1, 2015, 'Pop', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U17', 'Dark Horse', 'Katy Perry', 1, 2015, 'Pop', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U17', 'Dark Horse', 'Juicy J', 1, 2015, 'Pop', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U18', 'Ghost Stories', 'Coldplay', 0, 2015, 'Pop', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U19', 'Bangerz', 'Miley Cyrus', 0, 2015, 'Pop', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U20', 'My Everything', 'Ariana Grande', 0, 2015, 'Pop', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U21', 'Prism', 'Katy Perry', 0, 2015, 'Pop', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U22', 'Cheek to Cheek', 'Tony Bennett', 0, 2015, 'Pop', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U22', 'Cheek to Cheek', 'Lady Gaga', 0, 2015, 'Pop', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U23', 'Nostalgia', 'Annie Lennox', 0, 2015, 'Pop', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U24', 'Night Songs', 'Barry Manilow', 0, 2015, 'Pop', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U25', 'Sending You a Little Christmas', 'Johnny Mathis', 0, 2015, 'Pop', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U26', 'Partners', 'Barbra Streisand', 0, 2015, 'Pop', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U27', 'Rather Be', 'Clean Bandit', 1, 2015, 'Dance/Electronica', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U27', 'Rather Be', 'Jess Glynne', 1, 2015, 'Dance/Electronica', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U28', 'Never Say Never', 'Basement', 1, 2015, 'Dance/Electronica', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U28', 'Never Say Never', 'ETML', 1, 2015, 'Dance/Electronica', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U29', 'F For You', 'Disclosure', 1, 2015, 'Dance/Electronica', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U29', 'F For You', 'Mary J. Blige', 1, 2015, 'Dance/Electronica', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U30', 'I Got U', 'Duke Dumont', 1, 2015, 'Dance/Electronica', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U30', 'I Got U', 'Jax Jones', 1, 2015, 'Dance/Electronica', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U31', 'Faded', 'Zhu', 1, 2015, 'Dance/Electronica', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U32', 'Syro', 'Aphex Twin', 0, 2015, 'Dance/Electronica', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U33', 'while(1<2)', 'deadmau5', 0, 2015, 'Dance/Electronica', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U34', 'Nabuma Rubberband', 'Little Dragon', 0, 2015, 'Dance/Electronica', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U35', 'Do It Again', 'Royksopp', 0, 2015, 'Dance/Electronica', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U35', 'Do It Again', 'Robyn', 0, 2015, 'Dance/Electronica', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U36', 'Damage Control', 'Mat Zo', 0, 2015, 'Dance/Electronica', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U37', 'Bass & Mandolin', 'Chris Thile', 0, 2015, 'Contemporary Instrumental', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U37', 'Bass & Mandolin', 'Edgar Meyer', 0, 2015, 'Contemporary Instrumental', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U38', 'Wild Heart', 'Mindi Abair', 0, 2015, 'Contemporary Instrumental', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U39', 'Slam Dunk', 'Gerald Albright', 0, 2015, 'Contemporary Instrumental', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U40', 'Nathan East', 'Nathan East', 0, 2015, 'Contemporary Instrumental', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U41', 'Jazz Funk Soul', 'Jeff Lorber', 0, 2015, 'Contemporary Instrumental', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U41', 'Jazz Funk Soul', 'Chuck Loeb', 0, 2015, 'Contemporary Instrumental', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U41', 'Jazz Funk Soul', 'Everette Harp', 0, 2015, 'Contemporary Instrumental', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U42', 'Lazaretto', 'Jack White', 1, 2015, 'Rock & Alternative', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U43', 'Gimme Something Good', 'Ryan Adams', 1, 2015, 'Rock', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U44', 'Do I Wanna Know?', 'Arctic Monkeys', 1, 2015, 'Rock', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U45', 'Blue Moon', 'Beck', 1, 2015, 'Rock', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U46', 'Fever', 'The Black Keys', 1, 2015, 'Rock', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U47', 'The Last in Line', 'Tenacious D', 1, 2015, 'Rock', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U48', 'Neon Knights', 'Anthrax', 1, 2015, 'Rock', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U49', 'High Road', 'Mastodon', 1, 2015, 'Rock', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U50', 'Heartbreaker', 'Motorhead', 1, 2015, 'Rock', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U51', 'The Negative One', 'Slipknot', 1, 2015, 'Rock', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U52', 'Ain''t It Fun', 'Paramore', 1, 2015, 'Rock', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U53', 'Fever', 'The Black Keys', 1, 2015, 'Rock', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U54', 'Ryan Adams', 'Ryan Adams', 0, 2015, 'Rock', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U55', 'Turn Blue', 'The Black Keys', 0, 2015, 'Rock', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U56', 'Hypnotic Eye', 'Tom Petty', 0, 2015, 'Rock', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U56', 'Hypnotic Eye', 'The Heartbreakers', 0, 2015, 'Rock', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U57', 'Songs of Innocence', 'U2', 0, 2015, 'Rock', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U58', 'St. Vincent', 'St. Vincent', 0, 2015, 'Alternative', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U59', 'This Is All Yours', 'alt-J', 0, 2015, 'Alternative', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U60', 'Reflektor', 'Arcade Fire', 0, 2015, 'Alternative', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U61', 'Melophobia', 'Cage the Elephant', 0, 2015, 'Alternative', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U62', 'Drunk in Love', 'Beyonce', 1, 2015, 'R&B', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U62', 'Drunk in Love', 'Jay Z', 1, 2015, 'R&B', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U63', 'Good Kisser', 'Usher', 1, 2015, 'R&B', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U64', 'New Flame', 'Chris Brown', 1, 2015, 'R&B', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U64', 'New Flame', 'Usher', 1, 2015, 'R&B', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U64', 'New Flame', 'Rick Ross', 1, 2015, 'R&B', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U65', 'Options', 'Luke James', 1, 2015, 'R&B', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U66', 'The Worst', 'Jhene Aiko', 1, 2015, 'R&B', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U67', 'Sail Out', 'Jhene Aiko', 0, 2015, 'R&B', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U68', 'Mali is...', 'Mali Music', 0, 2015, 'R&B', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U69', 'Love, Marriage & Divorce', 'Toni Braxton', 0, 2015, 'R&B', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U69', 'Love, Marriage & Divorce', 'Babyface', 0, 2015, 'R&B', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U70', 'Islander', 'Bernhoft', 0, 2015, 'R&B', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U71', 'Lift Your Spirit', 'Aloe Blacc', 0, 2015, 'R&B', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U72', 'Black Radio 2', 'Robert Glasper Experiment', 0, 2015, 'R&B', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U73', 'Give The People What They Want', 'Sharon Jones', 0, 2015, 'R&B', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U73', 'Give The People What They Want', 'The Dap-Kings', 0, 2015, 'R&B', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U74', 'i', 'Kendrick Lamar', 1, 2015, 'Rap', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U75', 'Anaconda', 'Nicki Minaj', 1, 2015, 'Rap', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U76', 'Bound 2', 'Kanye West', 1, 2015, 'Rap', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U76', 'Bound 2', 'Charlie Wilson', 1, 2015, 'Rap', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U77', 'Me Dem Boyz', 'Wiz Khalifa', 1, 2015, 'Rap', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U78', '0 to 100 / The Catch Up', 'Drake', 1, 2015, 'Rap', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U79', 'The MArshall Mathers LP 2', 'Eminem', 0, 2015, 'Rap', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U80', 'The New Classic', 'Iggy Azalea ', 0, 2015, 'Rap', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U81', 'Because the Internet', 'Childish Gambino', 0, 2015, 'Rap', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U82', 'Nobody''s Smiling', 'Common', 0, 2015, 'Rap', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U83', 'Oxymoron', 'ScHoolboy Q', 0, 2015, 'Rap', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U84', 'Blacc Hollywood', 'Wiz Khalifa', 0, 2015, 'Rap', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U85', 'I''m Not Gonna Miss You', 'Glen Campbell', 1, 2015, 'Country', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U86', 'American Kids', 'Kenny Chesney', 1, 2015, 'Country', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U87', 'Automatic', 'Miranda Lambert', 1, 2015, 'Country', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U88', 'Give Me Back My Hometown', 'Eric Church', 1, 2015, 'Country', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U89', 'Meanwhile Back at Mama''s', 'Tim McGraw', 1, 2015, 'Country', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U89', 'Meanwhile Back at Mama''s', 'Faith Hill', 1, 2015, 'Country', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U90', 'Platinum', 'Miranda Lambert', 0, 2015, 'Country', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U91', 'Riser', 'Dierks Bentley', 0, 2015, 'Country', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U92', 'The Outsiders', 'Eric Church', 0, 2015, 'Country', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U93', '12 Stories', 'Brandy Clark', 0, 2015, 'Country', 2014);
INSERT INTO Music (WorkID, Title, Artist, isSingle, EligibilityYear, Genre, ReleaseYear) VALUES ('U94', 'The Way I''m Livin''', 'Lee Ann Womack', 0, 2015, 'Country', 2014);