CREATE TABLE People(Name VARCHAR(200) PRIMARY KEY, PlaceOrigin VARCHAR(100) NULL, Occupation VARCHAR(100) NULL, Gender VARCHAR(50) NULL, Birthdate DATETIME NULL);
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Alejandro G. Inarritu', 'Mexico', 'Director', 'Male', '8/15/1963');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('John Lesher', 'America', 'Producer', 'Male', '5/12/1966');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('James W. Skotchdopole', 'America', 'Producer', 'Male', NULL);
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Sam Smith', 'England', 'Musician', 'Male', '5/19/1992');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Iggy Azalea', 'Australia', 'Musician', 'Female', '6/7/1990');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Charli XCX', 'England', 'Musician', 'Female', '8/2/1992');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Sia', 'Australia', 'Musician', 'Female', '12/18/1975');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Taylor Swift', 'America', 'Musician', 'Female', '12/13/1989');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Meghan Trainor', 'America', 'Musician', 'Female', '12/22/1993');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Beck', 'America', 'Musician', 'Male', '7/8/1970');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Beyonce', 'America', 'Musician', 'Female', '9/4/1981');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Ed Sheeran', 'England', 'Musician', 'Male', '2/17/1991');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Pharrell Williams', 'America', 'Musician', 'Male', '4/5/1973');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Andrew Hozier-Byrne', 'Ireland', 'Musician', 'Male', '3/17/1990');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('John Legend', 'America', 'Musician', 'Male', '12/28/1978');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('A Great Big World', 'America', 'Musical Group', NULL, NULL);
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Christina Aguilera', 'America', 'Musician', 'Female', '12/18/1980');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Coldplay', 'United Kingdom', 'Musical Group', NULL, NULL);
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Jessie J', 'England', 'Musician', 'Female', '3/27/1988');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Katy Perry', 'America', 'Musician', 'Female', '10/25/1984');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Juicy J', 'America', 'Musician', 'Male', '4/5/1975');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Miley Cyrus', 'America', 'Musician', 'Female', '11/23/1992');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Ariana Grande', 'America', 'Musician', 'Female', '6/26/1993');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Tony Bennett', 'America', 'Musician', 'Male', '8/3/1926');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Lady Gaga', 'America', 'Musician', 'Female', '3/28/1986');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Annie Lennox', 'Scotland', 'Musician', 'Female', '12/25/1954');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Barry Manilow', 'America', 'Musician', 'Male', '6/17/1943');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Johnny Mathis', 'America', 'Musician', 'Male', '9/30/1935');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Barbra Streisand', 'America', 'Musician', 'Female', '4/24/1942');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Clean Bandit', 'England', 'Musical Group', NULL, NULL);
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Jess Glynne', 'United Kingdom', 'Musician', 'Female', '10/20/1989');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Basement Jaxx', 'England', 'Musical Group', NULL, NULL);
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Clint Eastwood', 'America', 'Actor', 'Male', '5/31/1930');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Robert Lorenz', 'America', 'Producer', 'Male', NULL);
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Andrew Lazar', 'America', 'Producer', 'Male', 1966);
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Bradley Cooper', 'America', 'Actor', 'Male', '1/5/1975');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Peter Morgan', 'America', 'Producer', 'Male', NULL);
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Richard Linklater', 'America', 'Director', 'Male', '7/30/1960');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Cathleen Sutherland', 'America', 'Producer', 'Female', NULL);
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Wes Anderson', 'America', 'Director', 'Male', '5/1/1969');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Scott Rudin', 'America', 'Producer', 'Male', '7/14/1958');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Steven M. Rales', 'America', 'Producer', 'Male', 1951);
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Jeremy Dawson', 'America', 'Producer', 'Male', NULL);
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Nora Grossman', 'America', 'Producer', 'Female', NULL);
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Ido Ostrowsky', 'America', 'Producer', 'Male', NULL);
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Teddy Schwarzman', 'America', 'Producer', 'Male', '5/29/1979');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Christian Colson', 'Britain', 'Producer', 'Male', '9/15/1968');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Oprah Winfrey', 'America', 'Talk Show Host', 'Female', '1/29/1954');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Dede Gardner', 'America', 'Producer', 'Female', NULL);
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Jeremy Kleiner', 'America', 'Producer', 'Male', 1976);
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Tim Bevan', 'Britain', 'Producer', 'Male', 1958);
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Eric Fellner', 'Britain', 'Producer', 'Male', 1959);
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Lisa Bruce', 'America', 'Producer', 'Female', NULL);
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Anthony McCarten', 'New Zealand', 'Writer', 'Male', 1961);
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Jason Blum', 'America', 'Producer', 'Male', '1/20/1969');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Bennett Miller', 'America', 'Director', 'Male', '1/30/1966');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Morten Tyldum', 'Norway', 'Director', 'Male', '5/19/1967');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Eddie Redmayne', 'Britain', 'Actor', 'Male', '1/6/1982');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Steve Carell', 'America', 'Actor', 'Male', '8/16/1962');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Benedict Cumberbatch', 'Britain', 'Actor', 'Male', '7/19/1976');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Michael Keaton', 'America', 'Actor', 'Male', '9/5/1951');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Julianne Moore', 'America', 'Actor', 'Female', '12/3/1960');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Marion Cotillard', 'France', 'Actor', 'Female', '9/30/1975');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Felicity Jones', 'Britain', 'Actor', 'Female', '10/17/1983');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Rosamund Pike', 'Britain', 'Actor', 'Female', '1/27/1979');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Reese Witherspoon', 'America', 'Actor', 'Female', '3/22/1976');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('J.K. Simmons', 'America', 'Actor', 'Male', '1/9/1955');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Robert Duvall', 'America', 'Actor', 'Male', '1/5/1931');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Ethan Hawke', 'America', 'Actor', 'Male', '11/6/1970');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Edward Norton', 'America', 'Actor', 'Male', '8/18/1969');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Mark Ruffalo', 'America', 'Actor', 'Male', '11/22/1967');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Patricia Arquette', 'America', 'Actor', 'Female', '4/8/1968');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Laura Dern', 'America', 'Actor', 'Female', '2/10/1967');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Keira Knightley', 'Britain', 'Actor', 'Female', '3/26/1985');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Emma Stone', 'America', 'Actor', 'Female', '11/6/1988');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Meryl Streep', 'America', 'Actor', 'Female', '6/22/1949');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Nicolas Giacobone', 'Argentina', 'Writer', 'Male', NULL);
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Alexander Dinelaris Jr.', NULL, 'Writer', 'Male', NULL);
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Armando Bo Jr', 'Argentina', 'Writer', 'Male', NULL);
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('E. Max Frye', 'America', 'Writer', 'Male', 1956);
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Dan Futterman', 'America', 'Writer', 'Male', 1967);
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Hugo Guinness', 'Britain', 'Writer', 'Male', '9/12/1959');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Dan Gilroy', 'America', 'Writer', 'Male', '6/24/1959');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Graham Moore', 'America', 'Writer', 'Male', 1981);
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Jason Hall', 'America', 'Writer', 'Male', 1972);
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Paul Thomas Anderson', 'America', 'Writer', 'Male', '6/26/1970');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Damnien Chazelle', 'America', 'Writer', 'Male', '1/19/1985');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Don Hall', 'America', 'Director', 'Male', NULL);
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Chris Williams', 'America', 'Director', 'Male', 1968);
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Roy Conli', 'America', 'Producer', 'Male', NULL);
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Anthony Stacchi', 'America', 'Animator', 'Male', NULL);
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Graham Annable', 'America', 'Animator', 'Male', '6/1/1970');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Travis Knight', 'America', 'Animator', 'Male', 1973);
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Dean DeBlois', 'Canada', 'Director', 'Male', '6/7/1970');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Bonnie Arnold', 'America', 'Producer', 'Female', 1955);
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Tomm Moore', 'Ireland', 'Illustrator', 'Male', '1/7/1977');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Isao Takahata', 'Japan', 'Director', 'Male', '10/29/1935');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Pawel Pawlikowski', 'Poland', 'Fimmaker', 'Male', '9/15/1957');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Andrey Zvyagintsev', 'Russia', 'Director', 'Male', '2/6/1964');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Zaza Urushadze', 'Georgia', 'Director', 'Male', '10/30/1965');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Abderrahmane Sissako', 'Mauritania', 'Director', 'Male', '10/13/1961');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Damian Szifron', 'Argentina', 'Director', 'Male', '7/9/1975');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Alexandre Desplat', 'France', 'Composer', 'Male', '8/23/1961');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Hans Zimmer', 'Germany', 'Composer', 'Male', '9/12/1957');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Gary Yershon', 'Britain', 'Composer', 'Male', '11/2/1954');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Johann Johannsson', 'Iceland', 'Composer', 'Male', '9/19/1969');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Common', 'America', 'Musician', 'Male', '3/13/1972');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Shawn Patterson', 'America', 'Composer', 'Male', '9/14/1965');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Diane Warren', 'America', 'Musician', 'Female', '9/7/1956');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Glen Campbell', 'America', 'Musician', 'Male', '4/22/1936');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Gregg Alexander', 'America', 'Musician', 'Male', '5/4/1970');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Danielle Brisebois', 'America', 'Musician', 'Female', '6/28/1969');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Bryan Cranston', 'America', 'Actor', 'Male', '3/7/1956');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Samuel Barnett', 'Britain', 'Actor', 'Male', '4/25/1980');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Chris O''Dowd', 'Ireland', 'Actor', 'Male', '10/8/1979');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Mark Rylance', 'Britain', 'Actor', 'Male', '1/18/1960');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Tony Shalhoub', 'America', 'Actor', 'Male', '10/9/1953');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Audra McDonald', 'America', 'Actor', 'Female', '7/3/1970');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Tyne Daly', 'America', 'Actor', 'Female', '2/21/1946');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('LaTanya Richardson', 'America', 'Actor', 'Female', '10/21/1949');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Cherry Jones', 'America', 'Actor', 'Female', '11/21/1956');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Estelle Parsons', 'America', 'Actor', 'Female', '11/20/1927');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Neil Patrick Harris', 'America', 'Actor', 'Male', '6/15/1973');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Ramin Karimloo', 'Canada', 'Actor', 'Male', '9/19/1978');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Andy Karl', 'America', 'Actor', 'Male', NULL);
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Jefferson Mays', 'America', 'Actor', 'Male', '6/8/1965');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Bryce Pinkham', 'America', 'Actor', 'Male', NULL);
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Jessie Mueller', 'America', 'Actor', 'Female', '2/20/1983');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Mary Bridget Davies', 'America', 'Actor', 'Female', '8/30/1978');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Sutton Foster', 'America', 'Actor', 'Female', '3/18/1975');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Idina Menzel', 'America', 'Actor', 'Female', '5/30/1971');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Kelli O''Hara', 'America', 'Actor', 'Female', '4/16/1976');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Reed Birney', 'America', 'Actor', 'Male', '9/11/1954');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Paul Chahidi', 'America', 'Actor', 'Male', NULL);
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Stephen Fry', 'Britain', 'Actor', 'Male', '8/24/1957');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Brian J. Smith', 'America', 'Actor', 'Male', '10/12/1981');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Sophie Okonedo', 'Britain', 'Actor', 'Female', '8/11/1968');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Sarah Greene', 'Ireland', 'Actor', 'Female', NULL);
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Celia Keenan-Bolger', 'America', 'Actor', 'Female', '1/26/1978');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Anika Noni Rose', 'America', 'Actor', 'Female', '9/6/1972');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Mare Winningham', 'America', 'Actor', 'Female', '5/16/1959');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('James Monroe Iglehart', 'America', 'Actor', 'Male', '9/4/1974');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Danny Burstein', 'America', 'Actor', 'Male', '6/16/1964');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Nick Cordero', 'Canada', 'Actor', 'Male', NULL);
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Joshua Henry', 'America', 'Actor', 'Male', '9/2/1984');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Jarrod Spector', 'America', 'Actor', 'Male', 1981);
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Lena Hall', 'America', 'Actor', 'Female', '1/30/1980');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Linda Emond', 'America', 'Actor', 'Female', '5/22/1959');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Anika Larsen', 'America', 'Actor', 'Female', '12/19/1973');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Adriane Lenox', 'America', 'Actor', 'Female', '9/11/1956');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Lauren Worsham', 'America', 'Actor', 'Female', '4/4/1982');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Jim Parsons', 'America', 'Actor', 'Male', '3/24/1973');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Louis C.K.', 'America', 'Comedian', 'Male', '9/12/1967');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Don Cheadle', 'America', 'Actor', 'Male', '11/29/1964');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Ricky Gervais', 'Britain', 'Comedian', 'Male', '6/25/1961');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Matt LeBlanc', 'America', 'Actor', 'Male', '7/25/1967');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('William H. Macy', 'America', 'Actor', 'Male', '3/13/1950');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Julia Louis-Dreyfus', 'America', 'Actor', 'Female', '1/13/1961');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Lena Dunham', 'America', 'Actor', 'Female', '5/13/1986');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Edie Falco', 'America', 'Actor', 'Female', '7/5/1963');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Melissa McCarthy', 'America', 'Actor', 'Female', '8/26/1970');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Amy Poehler', 'America', 'Actor', 'Female', '9/16/1971');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Taylor Schilling', 'America', 'Actor', 'Female', '7/27/1984');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Jeff Daniels', 'America', 'Actor', 'Male', '2/19/1955');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Jon Hamm', 'America', 'Actor', 'Male', '3/10/1971');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Woody Harrelson', 'America', 'Actor', 'Male', '7/23/1961');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Matthew McConaughey', 'America', 'Actor', 'Male', '11/4/1969');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Kevin Spacey', 'America', 'Actor', 'Male', '7/26/1959');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Julianna Margulies', 'America', 'Actor', 'Female', '6/8/1966');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Lizzy Caplan', 'America', 'Actor', 'Female', '6/30/1982');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Claire Danes', 'America', 'Actor', 'Female', '4/12/1979');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Michelle Dockery', 'Britain', 'Actor', 'Female', '12/15/1981');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Kerry Washington', 'America', 'Actor', 'Female', '1/31/1977');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Robin Wright', 'America', 'Actor', 'Female', '4/8/1966');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Chiwetel Ejiofor', 'Britain', 'Actor', 'Male', '7/10/1977');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Idris Elba', 'Britain', 'Actor', 'Male', '9/6/1972');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Martin Freeman', 'Britain', 'Actor', 'Male', '9/8/1971');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Billy Bob Thornton', 'America', 'Actor', 'Male', '8/4/1955');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Jessica Lange', 'America', 'Actor', 'Female', '4/20/1949');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Helena Bonham Carter', 'Britain', 'Actor', 'Female', '5/26/1966');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Minnie Driver', 'Britain', 'Actor', 'Female', '1/31/1970');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Sarah Paulson', 'America', 'Actor', 'Female', '12/17/1974');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Cicely Tyson', 'America', 'Actor', 'Female', '12/18/1924');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Kristen Wiig', 'America', 'Actor', 'Female', '8/22/1973');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Ty Burrell', 'America', 'Actor', 'Male', '8/22/1967');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Fred Armisen', 'America', 'Actor', 'Male', '12/4/1966');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Andre Braugher', 'America', 'Actor', 'Male', '7/1/1962');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Adam Driver', 'America', 'Actor', 'Male', '11/19/1983');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Jesse Tyler Ferguson', 'America', 'Actor', 'Male', '10/22/1975');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Tony Hale', 'America', 'Actor', 'Male', '9/30/1970');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Allison Janney', 'America', 'Actor', 'Female', '11/19/1959');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Mayim Bialik', 'America', 'Actor', 'Female', '12/12/1975');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Julie Bowen', 'America', 'Actor', 'Female', '3/3/1970');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Anna Chlumsky', 'America', 'Actor', 'Female', '12/3/1980');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Kate McKinnon', 'America', 'Actor', 'Female', '1/6/1984');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Kate Mulgrew', 'America', 'Actor', 'Female', '4/29/1955');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Aaron Paul', 'America', 'Actor', 'Male', '8/27/1979');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Jim Carter', 'Britain', 'Actor', 'Male', '8/19/1947');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Josh Charles', 'America', 'Actor', 'Male', '9/15/1971');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Peter Dinklage', 'America', 'Actor', 'Male', '6/11/1969');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Mandy Patinkin', 'America', 'Actor', 'Male', '11/30/1952');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Jon Voight', 'America', 'Actor', 'Male', '12/29/1938');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Anna Gunn', 'America', 'Actor', 'Female', '8/11/1968');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Christine Baranski', 'America', 'Actor', 'Female', '5/2/1952');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Joanne Froggatt', 'Britain', 'Actor', 'Female', '8/23/1980');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Lena Headey', 'Britain', 'Actor', 'Female', '10/3/1973');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Christina Hendricks', 'America', 'Actor', 'Female', '5/3/1975');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Maggie Smith', 'Britain', 'Actor', 'Female', '12/28/1934');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Matt Bomer', 'America', 'Actor', 'Male', '10/11/1977');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Colin Hanks', 'America', 'Actor', 'Male', '11/24/1977');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Kathy Bates', 'America', 'Actor', 'Female', '6/28/1948');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Joe Mantello', 'America', 'Actor', 'Male', '12/27/1962');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Alfred Molina', 'Britain', 'Actor', 'Male', '5/24/1953');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Angela Bassett', 'America', 'Actor', 'Female', '8/16/1958');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Frances Conroy', 'America', 'Actor', 'Female', '11/13/1953');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Julia Roberts', 'America', 'Actor', 'Female', '10/28/1967');
INSERT INTO People (Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('Allison Tolman', 'America', 'Actor', 'Female', '11/18/1981');

