CREATE TABLE People(WorkID VARCHAR(50) PRIMARY KEY, Name VARCHAR(200), PlaceOrigin VARCHAR(100) NULL, Occupation VARCHAR(100) NULL, Gender VARCHAR(50) NULL, Birthdate DATETIME NULL);
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P1', 'Alejandro G. Inarritu', 'Mexico', 'Director', 'Male', STR_TO_DATE('8/15/1963', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P2', 'John Lesher', 'America', 'Producer', 'Male', STR_TO_DATE('5/12/1966', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P3', 'James W. Skotchdopole', 'America', 'Producer', 'Male', 'Unknown');
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P4', 'Sam Smith', 'England', 'Musician', 'Male', STR_TO_DATE('5/19/1992', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P5', 'Iggy Azalea', 'Australia', 'Musician', 'Female', STR_TO_DATE('6/7/1990', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P6', 'Charli XCX', 'England', 'Musician', 'Female', STR_TO_DATE('8/2/1992', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P7', 'Sia', 'Australia', 'Musician', 'Female', STR_TO_DATE('12/18/1975', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P8', 'Taylor Swift', 'America', 'Musician', 'Female', STR_TO_DATE('12/13/1989', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P9', 'Meghan Trainor', 'America', 'Musician', 'Female', STR_TO_DATE('12/22/1993', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P10', 'Beck', 'America', 'Musician', 'Male', STR_TO_DATE('7/8/1970', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P11', 'Beyonce', 'America', 'Musician', 'Female', STR_TO_DATE('9/4/1981', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P12', 'Ed Sheeran', 'England', 'Musician', 'Male', STR_TO_DATE('2/17/1991', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P13', 'Pharrell Williams', 'America', 'Musician', 'Male', STR_TO_DATE('4/5/1973', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P14', 'Andrew Hozier-Byrne', 'Ireland', 'Musician', 'Male', STR_TO_DATE('3/17/1990', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P15', 'John Legend', 'America', 'Musician', 'Male', STR_TO_DATE('12/28/1978', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P16', 'A Great Big World', 'America', 'Musical Group', NULL, NULL);
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P17', 'Christina Aguilera', 'America', 'Musician', 'Female', STR_TO_DATE('12/18/1980', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P18', 'Coldplay', 'United Kingdom', 'Musical Group', NULL, NULL);
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P19', 'Jessie J', 'England', 'Musician', 'Female', STR_TO_DATE('3/27/1988', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P20', 'Katy Perry', 'America', 'Musician', 'Female', STR_TO_DATE('10/25/1984', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P21', 'Juicy J', 'America', 'Musician', 'Male', STR_TO_DATE('4/5/1975', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P22', 'Miley Cyrus', 'America', 'Musician', 'Female', STR_TO_DATE('11/23/1992', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P23', 'Ariana Grande', 'America', 'Musician', 'Female', STR_TO_DATE('6/26/1993', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P24', 'Tony Bennett', 'America', 'Musician', 'Male', STR_TO_DATE('8/3/1926', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P25', 'Lady Gaga', 'America', 'Musician', 'Female', STR_TO_DATE('3/28/1986', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P26', 'Annie Lennox', 'Scotland', 'Musician', 'Female', STR_TO_DATE('12/25/1954', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P27', 'Barry Manilow', 'America', 'Musician', 'Male', STR_TO_DATE('6/17/1943', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P28', 'Johnny Mathis', 'America', 'Musician', 'Male', STR_TO_DATE('9/30/1935', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P29', 'Barbra Streisand', 'America', 'Musician', 'Female', STR_TO_DATE('4/24/1942', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P30', 'Clean Bandit', 'England', 'Musical Group', NULL, NULL);
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P31', 'Jess Glynne', 'United Kingdom', 'Musician', 'Female', STR_TO_DATE('10/20/1989', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P32', 'Basement Jaxx', 'England', 'Musical Group', NULL, NULL);
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P33', 'ETML', '', '', '', '');
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P34', 'Disclosure', 'England', 'Musical Group', NULL, NULL);
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P35', 'Mary J. Blige', 'America', 'Musician', 'Female', STR_TO_DATE('1/11/1971', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P36', 'Duke Dumont', 'United Kingdom', 'Musician', 'Male', STR_TO_DATE('8/27/1982', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P37', 'Jax Jones', 'United Kingdom', 'Musician', 'Male', 'Unknown');
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P38', 'Zhu', NULL, 'Musician', 'Male', 1989);
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P39', 'Aphex Twin', 'Ireland', 'Musician', 'Male', STR_TO_DATE('8/18/1971', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P40', 'deadmau5', 'Canada', 'Musician', 'Male', STR_TO_DATE('1/5/1981', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P41', 'Little Dragon', 'Sweden', 'Musical Group', NULL, NULL);
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P42', 'Royksopp', 'Norway', 'Musical Group', NULL, NULL);
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P43', 'Robyn', 'Sweden', 'Musician', 'Female', STR_TO_DATE('6/12/1979', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P44', 'Mat Zo', 'England', 'Musician', 'Male', STR_TO_DATE('4/30/1990', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P45', 'Chris Thile', 'America', 'Musician', 'Male', STR_TO_DATE('2/20/1981', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P46', 'Edgar Meyer', 'America', 'Musician', 'Male', STR_TO_DATE('11/24/1960', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P47', 'Mindi Abair', 'America', 'Musician', 'Female', STR_TO_DATE('5/23/1969', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P48', 'Gerald Albright', 'America', 'Musician', 'Male', STR_TO_DATE('8/30/1957', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P49', 'Nathan East', 'America', 'Musician', 'Male', STR_TO_DATE('12/8/1955', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P50', 'Jeff Lorber', 'America', 'Musician', 'Male', STR_TO_DATE('11/4/1952', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P51', 'Chuck Loeb', 'America', 'Musician', 'Male', STR_TO_DATE('12/7/1955', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P52', 'Everette Harp', 'America', 'Musician', 'Male', STR_TO_DATE('8/17/1961', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P53', 'Jack White', 'America', 'Musician', 'Male', STR_TO_DATE('7/9/1975', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P54', 'Ryan Adams', 'America', 'Musician', 'Male', STR_TO_DATE('11/5/1974', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P55', 'Arctic Monkeys', 'England', 'Musical Group', NULL, NULL);
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P56', 'The Black Keys', 'America', 'Musical Group', NULL, NULL);
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P57', 'Tenacious D', 'America', 'Musical Group', NULL, NULL);
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P58', 'Anthrax', 'America', 'Musical Group', NULL, NULL);
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P59', 'Mastodon', 'America', 'Musical Group', NULL, NULL);
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P60', 'Motorhead', 'England', 'Musical Group', NULL, NULL);
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P61', 'Slipknot', 'America', 'Musical Group', NULL, NULL);
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P62', 'Paramore', 'America', 'Musical Group', NULL, NULL);
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P63', 'Tom Petty and the Heartbreakers', 'America', 'Musical Group', NULL, NULL);
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P64', 'U2', 'Ireland', 'Musical Group', NULL, NULL);
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P65', 'St. Vincent', 'America', 'Musician', 'Female', STR_TO_DATE('9/28/1982', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P66', 'alt-J', 'England', 'Musical Group', NULL, NULL);
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P67', 'Arcade Fire', 'Canada', 'Musical Group', NULL, NULL);
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P68', 'Cage the Elephant', 'America', 'Musical Group', NULL, NULL);
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P69', 'Jay Z', 'America', 'Musician', 'Male', STR_TO_DATE('12/4/1969', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P70', 'Usher', 'America', 'Musician', 'Male', STR_TO_DATE('10/14/1978', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P71', 'Chris Brown', 'America', 'Musician', 'Male', STR_TO_DATE('5/5/1989', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P72', 'Rick Ross', 'America', 'Musician', 'Male', STR_TO_DATE('1/28/1976', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P73', 'Luke James', 'America', 'Musician', 'Male', 'Unknown');
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P74', 'Jhene Aiko', 'America', 'Musician', 'Female', STR_TO_DATE('3/16/1988', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P75', 'Mali Music', 'America', 'Musician', 'Male', STR_TO_DATE('1/12/1988', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P76', 'Toni Braxton', 'America', 'Musician', 'Female', STR_TO_DATE('10/7/1967', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P77', 'Babyface', 'America', 'Musician', 'Male', STR_TO_DATE('4/10/1959', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P78', 'Bernhoft', 'Norway', 'Musician', 'Male', STR_TO_DATE('6/21/1976', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P79', 'Aloe Blacc', 'America', 'Musician', 'Male', STR_TO_DATE('1/7/1979', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P80', 'Robert Glasper Experiment', 'America', 'Musician', 'Male', STR_TO_DATE('4/6/1978', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P81', 'Sharon Jones', 'America', 'Musician', 'Female', STR_TO_DATE('5/4/1956', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P82', 'The Dap-Kings', 'America', 'Musical Group', NULL, NULL);
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P83', 'Kendrick Lamar', 'America', 'Musician', 'Male', STR_TO_DATE('6/17/1987', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P84', 'Nicki Minaj', 'America', 'Musician', 'Female', STR_TO_DATE('12/8/1982', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P85', 'Kanye West', 'America', 'Musician', 'Male', STR_TO_DATE('6/8/1977', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P86', 'Charlie Wilson', 'America', 'Musician', 'Male', STR_TO_DATE('1/29/1953', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P87', 'Wiz Khalifa', 'America', 'Musician', 'Male', STR_TO_DATE('9/8/1987', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P88', 'Drake', 'Canada', 'Musician', 'Male', STR_TO_DATE('10/24/1986', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P89', 'Eminem', 'America', 'Musician', 'Male', STR_TO_DATE('10/17/1972', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P90', 'Childish Gambino', 'America', 'Musician', 'Male', STR_TO_DATE('9/25/1983', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P91', 'Common', 'America', 'Musician', 'Male', STR_TO_DATE('3/13/1972', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P92', 'ScHoolboy Q', 'Germany', 'Musician', 'Male', STR_TO_DATE('10/26/1986', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P93', 'Glen Campbell', 'America', 'Musician', 'Male', STR_TO_DATE('4/22/1936', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P94', 'Kenny Chesney', 'America', 'Musician', 'Male', STR_TO_DATE('3/26/1968', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P95', 'Miranda Lambert', 'America', 'Musician', 'Female', STR_TO_DATE('11/10/1983', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P96', 'Eric Church', 'America', 'Musician', 'Male', STR_TO_DATE('5/3/1977', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P97', 'Tim McGraw', 'America', 'Musician', 'Male', STR_TO_DATE('5/1/1967', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P98', 'Faith Hill', 'America', 'Musician', 'Female', STR_TO_DATE('9/21/1967', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P99', 'Dierks Bentley', 'America', 'Musician', 'Male', STR_TO_DATE('11/20/1975', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P100', 'Brandy Clark', 'America', 'Musician', 'Female', 1977);
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P101', 'Lee Ann Womack', 'America', 'Musician', 'Female', STR_TO_DATE('8/19/1966', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P102', 'Clint Eastwood', 'America', 'Actor', 'Male', STR_TO_DATE('5/31/1930', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P103', 'Robert Lorenz', 'America', 'Producer', 'Male', NULL);
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P104', 'Andrew Lazar', 'America', 'Producer', 'Male', 1966);
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P105', 'Bradley Cooper', 'America', 'Actor', 'Male', STR_TO_DATE('1/5/1975', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P106', 'Peter Morgan', 'America', 'Producer', 'Male', NULL);
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P107', 'Richard Linklater', 'America', 'Director', 'Male', STR_TO_DATE('7/30/1960', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P108', 'Cathleen Sutherland', 'America', 'Producer', 'Female', NULL);
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P109', 'Wes Anderson', 'America', 'Director', 'Male', STR_TO_DATE('5/1/1969', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P110', 'Scott Rudin', 'America', 'Producer', 'Male', STR_TO_DATE('7/14/1958', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P111', 'Steven M. Rales', 'America', 'Producer', 'Male', 1951);
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P112', 'Jeremy Dawson', 'America', 'Producer', 'Male', NULL);
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P113', 'Nora Grossman', 'America', 'Producer', 'Female', NULL);
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P114', 'Ido Ostrowsky', 'America', 'Producer', 'Male', NULL);
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P115', 'Teddy Schwarzman', 'America', 'Producer', 'Male', STR_TO_DATE('5/29/1979', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P116', 'Christian Colson', 'Britain', 'Producer', 'Male', STR_TO_DATE('9/15/1968', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P117', 'Oprah Winfrey', 'America', 'Talk Show Host', 'Female', STR_TO_DATE('1/29/1954', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P118', 'Dede Gardner', 'America', 'Producer', 'Female', NULL);
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P119', 'Jeremy Kleiner', 'America', 'Producer', 'Male', 1976);
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P120', 'Tim Bevan', 'Britain', 'Producer', 'Male', 1958);
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P121', 'Eric Fellner', 'Britain', 'Producer', 'Male', 1959);
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P122', 'Lisa Bruce', 'America', 'Producer', 'Female', NULL);
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P123', 'Anthony McCarten', 'New Zealand', 'Writer', 'Male', 1961);
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P124', 'Jason Blum', 'America', 'Producer', 'Male', STR_TO_DATE('1/20/1969', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P125', 'Bennett Miller', 'America', 'Director', 'Male', STR_TO_DATE('1/30/1966', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P126', 'Morten Tyldum', 'Norway', 'Director', 'Male', STR_TO_DATE('5/19/1967', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P127', 'Eddie Redmayne', 'Britain', 'Actor', 'Male', STR_TO_DATE('1/6/1982', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P128', 'Steve Carell', 'America', 'Actor', 'Male', STR_TO_DATE('8/16/1962', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P129', 'Benedict Cumberbatch', 'Britain', 'Actor', 'Male', STR_TO_DATE('7/19/1976', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P130', 'Michael Keaton', 'America', 'Actor', 'Male', STR_TO_DATE('9/5/1951', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P131', 'Julianne Moore', 'America', 'Actor', 'Female', STR_TO_DATE('12/3/1960', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P132', 'Marion Cotillard', 'France', 'Actor', 'Female', STR_TO_DATE('9/30/1975', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P133', 'Felicity Jones', 'Britain', 'Actor', 'Female', STR_TO_DATE('10/17/1983', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P134', 'Rosamund Pike', 'Britain', 'Actor', 'Female', STR_TO_DATE('1/27/1979', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P135', 'Reese Witherspoon', 'America', 'Actor', 'Female', STR_TO_DATE('3/22/1976', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P136', 'J.K. Simmons', 'America', 'Actor', 'Male', STR_TO_DATE('1/9/1955', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P137', 'Robert Duvall', 'America', 'Actor', 'Male', STR_TO_DATE('1/5/1931', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P138', 'Ethan Hawke', 'America', 'Actor', 'Male', STR_TO_DATE('11/6/1970', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P139', 'Edward Norton', 'America', 'Actor', 'Male', STR_TO_DATE('8/18/1969', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P140', 'Mark Ruffalo', 'America', 'Actor', 'Male', STR_TO_DATE('11/22/1967', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P141', 'Patricia Arquette', 'America', 'Actor', 'Female', STR_TO_DATE('4/8/1968', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P142', 'Laura Dern', 'America', 'Actor', 'Female', STR_TO_DATE('2/10/1967', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P143', 'Keira Knightley', 'Britain', 'Actor', 'Female', STR_TO_DATE('3/26/1985', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P144', 'Emma Stone', 'America', 'Actor', 'Female', STR_TO_DATE('11/6/1988', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P145', 'Meryl Streep', 'America', 'Actor', 'Female', STR_TO_DATE('6/22/1949', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P146', 'Nicolas Giacobone', 'Argentina', 'Writer', 'Male', NULL);
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P147', 'Alexander Dinelaris Jr.', NULL, 'Writer', 'Male', NULL);
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P148', 'Armando Bo Jr', 'Argentina', 'Writer', 'Male', NULL);
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P149', 'E. Max Frye', 'America', 'Writer', 'Male', 1956);
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P150', 'Dan Futterman', 'America', 'Writer', 'Male', 1967);
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P151', 'Hugo Guinness', 'Britain', 'Writer', 'Male', STR_TO_DATE('9/12/1959', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P152', 'Dan Gilroy', 'America', 'Writer', 'Male', STR_TO_DATE('6/24/1959', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P153', 'Graham Moore', 'America', 'Writer', 'Male', 1981);
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P154', 'Jason Hall', 'America', 'Writer', 'Male', 1972);
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P155', 'Paul Thomas Anderson', 'America', 'Writer', 'Male', STR_TO_DATE('6/26/1970', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P156', 'Damnien Chazelle', 'America', 'Writer', 'Male', STR_TO_DATE('1/19/1985', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P157', 'Don Hall', 'America', 'Director', 'Male', NULL);
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P158', 'Chris Williams', 'America', 'Director', 'Male', 1968);
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P159', 'Roy Conli', 'America', 'Producer', 'Male', NULL);
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P160', 'Anthony Stacchi', 'America', 'Animator', 'Male', NULL);
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P161', 'Graham Annable', 'America', 'Animator', 'Male', STR_TO_DATE('6/1/1970', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P162', 'Travis Knight', 'America', 'Animator', 'Male', 1973);
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P163', 'Dean DeBlois', 'Canada', 'Director', 'Male', STR_TO_DATE('6/7/1970', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P164', 'Bonnie Arnold', 'America', 'Producer', 'Female', 1955);
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P165', 'Tomm Moore', 'Ireland', 'Illustrator', 'Male', STR_TO_DATE('1/7/1977', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P166', 'Isao Takahata', 'Japan', 'Director', 'Male', STR_TO_DATE('10/29/1935', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P167', 'Pawel Pawlikowski', 'Poland', 'Fimmaker', 'Male', STR_TO_DATE('9/15/1957', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P168', 'Andrey Zvyagintsev', 'Russia', 'Director', 'Male', STR_TO_DATE('2/6/1964', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P169', 'Zaza Urushadze', 'Georgia', 'Director', 'Male', STR_TO_DATE('10/30/1965', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P170', 'Abderrahmane Sissako', 'Mauritania', 'Director', 'Male', STR_TO_DATE('10/13/1961', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P171', 'Damian Szifron', 'Argentina', 'Director', 'Male', STR_TO_DATE('7/9/1975', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P172', 'Alexandre Desplat', 'France', 'Composer', 'Male', STR_TO_DATE('8/23/1961', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P173', 'Hans Zimmer', 'Germany', 'Composer', 'Male', STR_TO_DATE('9/12/1957', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P174', 'Gary Yershon', 'Britain', 'Composer', 'Male', STR_TO_DATE('11/2/1954', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P175', 'Johann Johannsson', 'Iceland', 'Composer', 'Male', STR_TO_DATE('9/19/1969', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P176', 'Common', 'America', 'Musician', 'Male', STR_TO_DATE('3/13/1972', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P177', 'Shawn Patterson', 'America', 'Composer', 'Male', STR_TO_DATE('9/14/1965', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P178', 'Diane Warren', 'America', 'Musician', 'Female', STR_TO_DATE('9/7/1956', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P179', 'Glen Campbell', 'America', 'Musician', 'Male', STR_TO_DATE('4/22/1936', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P180', 'Gregg Alexander', 'America', 'Musician', 'Male', STR_TO_DATE('5/4/1970', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P181', 'Danielle Brisebois', 'America', 'Musician', 'Female', STR_TO_DATE('6/28/1969', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P182', 'Bryan Cranston', 'America', 'Actor', 'Male', STR_TO_DATE('3/7/1956', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P183', 'Samuel Barnett', 'Britain', 'Actor', 'Male', STR_TO_DATE('4/25/1980', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P184', 'Chris O''Dowd', 'Ireland', 'Actor', 'Male', STR_TO_DATE('10/8/1979', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P185', 'Mark Rylance', 'Britain', 'Actor', 'Male', STR_TO_DATE('1/18/1960', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P186', 'Tony Shalhoub', 'America', 'Actor', 'Male', STR_TO_DATE('10/9/1953', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P187', 'Audra McDonald', 'America', 'Actor', 'Female', STR_TO_DATE('7/3/1970', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P188', 'Tyne Daly', 'America', 'Actor', 'Female', STR_TO_DATE('2/21/1946', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P189', 'LaTanya Richardson', 'America', 'Actor', 'Female', STR_TO_DATE('10/21/1949', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P190', 'Cherry Jones', 'America', 'Actor', 'Female', STR_TO_DATE('11/21/1956', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P191', 'Estelle Parsons', 'America', 'Actor', 'Female', STR_TO_DATE('11/20/1927', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P192', 'Neil Patrick Harris', 'America', 'Actor', 'Male', STR_TO_DATE('6/15/1973', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P193', 'Ramin Karimloo', 'Canada', 'Actor', 'Male', STR_TO_DATE('9/19/1978', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P194', 'Andy Karl', 'America', 'Actor', 'Male', NULL);
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P195', 'Jefferson Mays', 'America', 'Actor', 'Male', STR_TO_DATE('6/8/1965', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P196', 'Bryce Pinkham', 'America', 'Actor', 'Male', NULL);
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P197', 'Jessie Mueller', 'America', 'Actor', 'Female', STR_TO_DATE('2/20/1983', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P198', 'Mary Bridget Davies', 'America', 'Actor', 'Female', STR_TO_DATE('8/30/1978', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P199', 'Sutton Foster', 'America', 'Actor', 'Female', STR_TO_DATE('3/18/1975', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P200', 'Idina Menzel', 'America', 'Actor', 'Female', STR_TO_DATE('5/30/1971', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P201', 'Kelli O''Hara', 'America', 'Actor', 'Female', STR_TO_DATE('4/16/1976', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P202', 'Reed Birney', 'America', 'Actor', 'Male', STR_TO_DATE('9/11/1954', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P203', 'Paul Chahidi', 'America', 'Actor', 'Male', NULL);
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P204', 'Stephen Fry', 'Britain', 'Actor', 'Male', STR_TO_DATE('8/24/1957', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P205', 'Brian J. Smith', 'America', 'Actor', 'Male', STR_TO_DATE('10/12/1981', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P206', 'Sophie Okonedo', 'Britain', 'Actor', 'Female', STR_TO_DATE('8/11/1968', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P207', 'Sarah Greene', 'Ireland', 'Actor', 'Female', NULL);
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P208', 'Celia Keenan-Bolger', 'America', 'Actor', 'Female', STR_TO_DATE('1/26/1978', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P209', 'Anika Noni Rose', 'America', 'Actor', 'Female', STR_TO_DATE('9/6/1972', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P210', 'Mare Winningham', 'America', 'Actor', 'Female', STR_TO_DATE('5/16/1959', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P211', 'James Monroe Iglehart', 'America', 'Actor', 'Male', STR_TO_DATE('9/4/1974', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P212', 'Danny Burstein', 'America', 'Actor', 'Male', STR_TO_DATE('6/16/1964', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P213', 'Nick Cordero', 'Canada', 'Actor', 'Male', NULL);
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P214', 'Joshua Henry', 'America', 'Actor', 'Male', STR_TO_DATE('9/2/1984', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P215', 'Jarrod Spector', 'America', 'Actor', 'Male', 1981);
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P216', 'Lena Hall', 'America', 'Actor', 'Female', STR_TO_DATE('1/30/1980', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P217', 'Linda Emond', 'America', 'Actor', 'Female', STR_TO_DATE('5/22/1959', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P218', 'Anika Larsen', 'America', 'Actor', 'Female', STR_TO_DATE('12/19/1973', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P219', 'Adriane Lenox', 'America', 'Actor', 'Female', STR_TO_DATE('9/11/1956', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P220', 'Lauren Worsham', 'America', 'Actor', 'Female', STR_TO_DATE('4/4/1982', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P221', 'Jim Parsons', 'America', 'Actor', 'Male', STR_TO_DATE('3/24/1973', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P222', 'Louis C.K.', 'America', 'Comedian', 'Male', STR_TO_DATE('9/12/1967', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P223', 'Don Cheadle', 'America', 'Actor', 'Male', STR_TO_DATE('11/29/1964', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P224', 'Ricky Gervais', 'Britain', 'Comedian', 'Male', STR_TO_DATE('6/25/1961', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P225', 'Matt LeBlanc', 'America', 'Actor', 'Male', STR_TO_DATE('7/25/1967', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P226', 'William H. Macy', 'America', 'Actor', 'Male', STR_TO_DATE('3/13/1950', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P227', 'Julia Louis-Dreyfus', 'America', 'Actor', 'Female', STR_TO_DATE('1/13/1961', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P228', 'Lena Dunham', 'America', 'Actor', 'Female', STR_TO_DATE('5/13/1986', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P229', 'Edie Falco', 'America', 'Actor', 'Female', STR_TO_DATE('7/5/1963', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P230', 'Melissa McCarthy', 'America', 'Actor', 'Female', STR_TO_DATE('8/26/1970', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P231', 'Amy Poehler', 'America', 'Actor', 'Female', STR_TO_DATE('9/16/1971', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P232', 'Taylor Schilling', 'America', 'Actor', 'Female', STR_TO_DATE('7/27/1984', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P233', 'Jeff Daniels', 'America', 'Actor', 'Male', STR_TO_DATE('2/19/1955', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P234', 'Jon Hamm', 'America', 'Actor', 'Male', STR_TO_DATE('3/10/1971', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P235', 'Woody Harrelson', 'America', 'Actor', 'Male', STR_TO_DATE('7/23/1961', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P236', 'Matthew McConaughey', 'America', 'Actor', 'Male', STR_TO_DATE('11/4/1969', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P237', 'Kevin Spacey', 'America', 'Actor', 'Male', STR_TO_DATE('7/26/1959', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P238', 'Julianna Margulies', 'America', 'Actor', 'Female', STR_TO_DATE('6/8/1966', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P239', 'Lizzy Caplan', 'America', 'Actor', 'Female', STR_TO_DATE('6/30/1982', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P240', 'Claire Danes', 'America', 'Actor', 'Female', STR_TO_DATE('4/12/1979', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P241', 'Michelle Dockery', 'Britain', 'Actor', 'Female', STR_TO_DATE('12/15/1981', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P242', 'Kerry Washington', 'America', 'Actor', 'Female', STR_TO_DATE('1/31/1977', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P243', 'Robin Wright', 'America', 'Actor', 'Female', STR_TO_DATE('4/8/1966', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P244', 'Chiwetel Ejiofor', 'Britain', 'Actor', 'Male', STR_TO_DATE('7/10/1977', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P245', 'Idris Elba', 'Britain', 'Actor', 'Male', STR_TO_DATE('9/6/1972', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P246', 'Martin Freeman', 'Britain', 'Actor', 'Male', STR_TO_DATE('9/8/1971', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P247', 'Billy Bob Thornton', 'America', 'Actor', 'Male', STR_TO_DATE('8/4/1955', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P248', 'Jessica Lange', 'America', 'Actor', 'Female', STR_TO_DATE('4/20/1949', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P249', 'Helena Bonham Carter', 'Britain', 'Actor', 'Female', STR_TO_DATE('5/26/1966', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P250', 'Minnie Driver', 'Britain', 'Actor', 'Female', STR_TO_DATE('1/31/1970', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P251', 'Sarah Paulson', 'America', 'Actor', 'Female', STR_TO_DATE('12/17/1974', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P252', 'Cicely Tyson', 'America', 'Actor', 'Female', STR_TO_DATE('12/18/1924', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P253', 'Kristen Wiig', 'America', 'Actor', 'Female', STR_TO_DATE('8/22/1973', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P254', 'Ty Burrell', 'America', 'Actor', 'Male', STR_TO_DATE('8/22/1967', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P255', 'Fred Armisen', 'America', 'Actor', 'Male', STR_TO_DATE('12/4/1966', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P256', 'Andre Braugher', 'America', 'Actor', 'Male', STR_TO_DATE('7/1/1962', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P257', 'Adam Driver', 'America', 'Actor', 'Male', STR_TO_DATE('11/19/1983', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P258', 'Jesse Tyler Ferguson', 'America', 'Actor', 'Male', STR_TO_DATE('10/22/1975', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P259', 'Tony Hale', 'America', 'Actor', 'Male', STR_TO_DATE('9/30/1970', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P260', 'Allison Janney', 'America', 'Actor', 'Female', STR_TO_DATE('11/19/1959', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P261', 'Mayim Bialik', 'America', 'Actor', 'Female', STR_TO_DATE('12/12/1975', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P262', 'Julie Bowen', 'America', 'Actor', 'Female', STR_TO_DATE('3/3/1970', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P263', 'Anna Chlumsky', 'America', 'Actor', 'Female', STR_TO_DATE('12/3/1980', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P264', 'Kate McKinnon', 'America', 'Actor', 'Female', STR_TO_DATE('1/6/1984', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P265', 'Kate Mulgrew', 'America', 'Actor', 'Female', STR_TO_DATE('4/29/1955', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P266', 'Aaron Paul', 'America', 'Actor', 'Male', STR_TO_DATE('8/27/1979', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P267', 'Jim Carter', 'Britain', 'Actor', 'Male', STR_TO_DATE('8/19/1947', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P268', 'Josh Charles', 'America', 'Actor', 'Male', STR_TO_DATE('9/15/1971', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P269', 'Peter Dinklage', 'America', 'Actor', 'Male', STR_TO_DATE('6/11/1969', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P270', 'Mandy Patinkin', 'America', 'Actor', 'Male', STR_TO_DATE('11/30/1952', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P271', 'Jon Voight', 'America', 'Actor', 'Male', STR_TO_DATE('12/29/1938', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P272', 'Anna Gunn', 'America', 'Actor', 'Female', STR_TO_DATE('8/11/1968', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P273', 'Christine Baranski', 'America', 'Actor', 'Female', STR_TO_DATE('5/2/1952', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P274', 'Joanne Froggatt', 'Britain', 'Actor', 'Female', STR_TO_DATE('8/23/1980', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P275', 'Lena Headey', 'Britain', 'Actor', 'Female', STR_TO_DATE('10/3/1973', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P276', 'Christina Hendricks', 'America', 'Actor', 'Female', STR_TO_DATE('5/3/1975', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P277', 'Maggie Smith', 'Britain', 'Actor', 'Female', STR_TO_DATE('12/28/1934', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P278', 'Matt Bomer', 'America', 'Actor', 'Male', STR_TO_DATE('10/11/1977', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P279', 'Colin Hanks', 'America', 'Actor', 'Male', STR_TO_DATE('11/24/1977', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P280', 'Kathy Bates', 'America', 'Actor', 'Female', STR_TO_DATE('6/28/1948', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P281', 'Joe Mantello', 'America', 'Actor', 'Male', STR_TO_DATE('12/27/1962', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P282', 'Alfred Molina', 'Britain', 'Actor', 'Male', STR_TO_DATE('5/24/1953', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P283', 'Angela Bassett', 'America', 'Actor', 'Female', STR_TO_DATE('8/16/1958', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P284', 'Frances Conroy', 'America', 'Actor', 'Female', STR_TO_DATE('11/13/1953', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P285', 'Julia Roberts', 'America', 'Actor', 'Female', STR_TO_DATE('10/28/1967', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P286', 'Allison Tolman', 'America', 'Actor', 'Female', STR_TO_DATE('11/18/1981', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P287', 'Bastille', 'England', 'Musical Group', NULL, NULL);
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P288', 'HAIM', 'America', 'Musical Group', NULL, NULL);
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P289', 'Jennifer Hudson', 'America', 'Musician', 'Female', STR_TO_DATE('9/12/1981', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P290', 'R. Kelly', 'America', 'Musician', 'Male', STR_TO_DATE('1/8/1967', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P291', 'Ledisi', 'America', 'Musician', 'Female', STR_TO_DATE('3/28/1972', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P292', 'Lalah Hathaway', 'America', 'Musician', 'Female', STR_TO_DATE('12/16/1968', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P293', 'Malcolm Jamal Warner', 'America', 'Musician', 'Male', STR_TO_DATE('8/18/1970', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P294', 'Marsha Ambrosius', 'England', 'Musician', 'Female', STR_TO_DATE('8/8/1977', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P295', 'Anthony Hamilton', 'America', 'Musician', 'Male', STR_TO_DATE('1/28/1971', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P296', 'Angie Fisher', 'Unknown', 'Musician', 'Female', 'Unknown');
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P297', 'Kem', 'America', 'Musician', 'Male', 'Unknown');
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P298', 'Antonique Smith', 'America', 'Musician', 'Female', 'Unknown');
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P299', 'Lecrae', 'America', 'Musician', 'Male', STR_TO_DATE('10/9/1979', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P300', 'Rihanna', 'Barbados', 'Musician', 'Female', STR_TO_DATE('2/20/1988', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P301', 'ILoveMakonnen', 'America', 'Musician', 'Male', STR_TO_DATE('4/12/1989', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P302', 'BJ the Chicago Kid', 'America', 'Musician', 'Male', 'Unknown');
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P303', 'Carrie Underwood', 'America', 'Musician', 'Female', STR_TO_DATE('3/10/1983', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P304', 'Hunter Hayes', 'America', 'Musician', 'Male', STR_TO_DATE('9/9/1991', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P305', 'Keith Urban', 'New Zealand', 'Musician', 'Male', STR_TO_DATE('10/26/1967', '%m/%d/%Y'));
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P306', 'The Band Perry', 'America', 'Musical Group', NULL, NULL);
INSERT INTO People (WorkID, Name, PlaceOrigin, Occupation, Gender, Birthdate) VALUES ('P307', 'Little Big Town', 'America', 'Musical Group', NULL, NULL);