CREATE TABLE Works(WorkID VARCHAR(200), TitleName VARCHAR(500));
INSERT INTO Works (WorkID, TitleName) VALUES ('S1', 'Act One');
INSERT INTO Works (WorkID, TitleName) VALUES ('S2', 'All the Way');
INSERT INTO Works (WorkID, TitleName) VALUES ('S3', 'Casa Valentina');
INSERT INTO Works (WorkID, TitleName) VALUES ('S4', 'Mothers and Sons');
INSERT INTO Works (WorkID, TitleName) VALUES ('S5', 'Outside Mullingar');
INSERT INTO Works (WorkID, TitleName) VALUES ('S6', 'A Gentleman''s Guide to Love and Murder');
INSERT INTO Works (WorkID, TitleName) VALUES ('S7', 'After Midnight');
INSERT INTO Works (WorkID, TitleName) VALUES ('S8', 'Aladdin');
INSERT INTO Works (WorkID, TitleName) VALUES ('S9', 'Beautiful: The Carole King Musical');
INSERT INTO Works (WorkID, TitleName) VALUES ('S10', 'A Raisin in the Sun');
INSERT INTO Works (WorkID, TitleName) VALUES ('S11', 'The Cripple of Inishmaan');
INSERT INTO Works (WorkID, TitleName) VALUES ('S12', 'The Glass Menagerie');
INSERT INTO Works (WorkID, TitleName) VALUES ('S13', 'Twelfth Night');
INSERT INTO Works (WorkID, TitleName) VALUES ('S14', 'Hedwig and the Angry Inch');
INSERT INTO Works (WorkID, TitleName) VALUES ('S15', 'Les Miserables');
INSERT INTO Works (WorkID, TitleName) VALUES ('S16', 'Violet');
INSERT INTO Works (WorkID, TitleName) VALUES ('S17', 'Of Mice and Men');
INSERT INTO Works (WorkID, TitleName) VALUES ('S18', 'Richard III');
INSERT INTO Works (WorkID, TitleName) VALUES ('S19', 'Lady Day at Emerson''s Bar & Grill');
INSERT INTO Works (WorkID, TitleName) VALUES ('S20', 'The Velocity of Autumn');
INSERT INTO Works (WorkID, TitleName) VALUES ('S21', 'Rocky');
INSERT INTO Works (WorkID, TitleName) VALUES ('S22', 'A Night with Janis Joplin');
INSERT INTO Works (WorkID, TitleName) VALUES ('S23', 'If/Then');
INSERT INTO Works (WorkID, TitleName) VALUES ('S24', 'The Bridges of Madison County');
INSERT INTO Works (WorkID, TitleName) VALUES ('S25', 'Cabaret');
INSERT INTO Works (WorkID, TitleName) VALUES ('S26', 'Bullets Over Broadway');
INSERT INTO Works (WorkID, TitleName) VALUES ('S27', 'Machinal');
INSERT INTO Works (WorkID, TitleName) VALUES ('U1', 'Stay with Me (Darkchild Version)');
INSERT INTO Works (WorkID, TitleName) VALUES ('U2', 'Fancy');
INSERT INTO Works (WorkID, TitleName) VALUES ('U3', 'Chandelier');
INSERT INTO Works (WorkID, TitleName) VALUES ('U4', 'Shake It Off');
INSERT INTO Works (WorkID, TitleName) VALUES ('U5', 'All About That Bass');
INSERT INTO Works (WorkID, TitleName) VALUES ('U6', 'Morning Phase');
INSERT INTO Works (WorkID, TitleName) VALUES ('U7', 'Beyonce');
INSERT INTO Works (WorkID, TitleName) VALUES ('U8', 'x');
INSERT INTO Works (WorkID, TitleName) VALUES ('U9', 'In the Lonely Hour');
INSERT INTO Works (WorkID, TitleName) VALUES ('U10', 'G I R L');
INSERT INTO Works (WorkID, TitleName) VALUES ('U11', 'Take Me to Church');
INSERT INTO Works (WorkID, TitleName) VALUES ('U12', 'Happy (Live)');
INSERT INTO Works (WorkID, TitleName) VALUES ('U13', 'All of Me (Live)');
INSERT INTO Works (WorkID, TitleName) VALUES ('U14', 'Say Something');
INSERT INTO Works (WorkID, TitleName) VALUES ('U15', 'A Sky Full of Stars');
INSERT INTO Works (WorkID, TitleName) VALUES ('U16', 'Bang Bang');
INSERT INTO Works (WorkID, TitleName) VALUES ('U17', 'Dark Horse');
INSERT INTO Works (WorkID, TitleName) VALUES ('U18', 'Ghost Stories');
INSERT INTO Works (WorkID, TitleName) VALUES ('U19', 'Bangerz');
INSERT INTO Works (WorkID, TitleName) VALUES ('U20', 'My Everything');
INSERT INTO Works (WorkID, TitleName) VALUES ('U21', 'Prism');
INSERT INTO Works (WorkID, TitleName) VALUES ('U22', 'Cheek to Cheek');
INSERT INTO Works (WorkID, TitleName) VALUES ('U23', 'Nostalgia');
INSERT INTO Works (WorkID, TitleName) VALUES ('U24', 'Night Songs');
INSERT INTO Works (WorkID, TitleName) VALUES ('U25', 'Sending You a Little Christmas');
INSERT INTO Works (WorkID, TitleName) VALUES ('U26', 'Partners');
INSERT INTO Works (WorkID, TitleName) VALUES ('U27', 'Rather Be');
INSERT INTO Works (WorkID, TitleName) VALUES ('U28', 'Never Say Never');
INSERT INTO Works (WorkID, TitleName) VALUES ('U29', 'F For You');
INSERT INTO Works (WorkID, TitleName) VALUES ('U30', 'I Got U');
INSERT INTO Works (WorkID, TitleName) VALUES ('U31', 'Faded');
INSERT INTO Works (WorkID, TitleName) VALUES ('U32', 'Syro');
INSERT INTO Works (WorkID, TitleName) VALUES ('U33', 'while(1<2)');
INSERT INTO Works (WorkID, TitleName) VALUES ('U34', 'Nabuma Rubberband');
INSERT INTO Works (WorkID, TitleName) VALUES ('U35', 'Do It Again');
INSERT INTO Works (WorkID, TitleName) VALUES ('U36', 'Damage Control');
INSERT INTO Works (WorkID, TitleName) VALUES ('U37', 'Bass & Mandolin');
INSERT INTO Works (WorkID, TitleName) VALUES ('U38', 'Wild Heart');
INSERT INTO Works (WorkID, TitleName) VALUES ('U39', 'Slam Dunk');
INSERT INTO Works (WorkID, TitleName) VALUES ('U40', 'Nathan East');
INSERT INTO Works (WorkID, TitleName) VALUES ('U41', 'Jazz Funk Soul');
INSERT INTO Works (WorkID, TitleName) VALUES ('U42', 'Lazaretto');
INSERT INTO Works (WorkID, TitleName) VALUES ('U43', 'Gimme Something Good');
INSERT INTO Works (WorkID, TitleName) VALUES ('U44', 'Do I Wanna Know?');
INSERT INTO Works (WorkID, TitleName) VALUES ('U45', 'Blue Moon');
INSERT INTO Works (WorkID, TitleName) VALUES ('U46', 'Fever');
INSERT INTO Works (WorkID, TitleName) VALUES ('U47', 'The Last in Line');
INSERT INTO Works (WorkID, TitleName) VALUES ('U48', 'Neon Knights');
INSERT INTO Works (WorkID, TitleName) VALUES ('U49', 'High Road');
INSERT INTO Works (WorkID, TitleName) VALUES ('U50', 'Heartbreaker');
INSERT INTO Works (WorkID, TitleName) VALUES ('U51', 'The Negative One');
INSERT INTO Works (WorkID, TitleName) VALUES ('U52', 'Ain''t It Fun');
INSERT INTO Works (WorkID, TitleName) VALUES ('U53', 'Fever');
INSERT INTO Works (WorkID, TitleName) VALUES ('U54', 'Ryan Adams');
INSERT INTO Works (WorkID, TitleName) VALUES ('U55', 'Turn Blue');
INSERT INTO Works (WorkID, TitleName) VALUES ('U56', 'Hypnotic Eye');
INSERT INTO Works (WorkID, TitleName) VALUES ('U57', 'Songs of Innocence');
INSERT INTO Works (WorkID, TitleName) VALUES ('U58', 'St. Vincent');
INSERT INTO Works (WorkID, TitleName) VALUES ('U59', 'This Is All Yours');
INSERT INTO Works (WorkID, TitleName) VALUES ('U60', 'Reflektor');
INSERT INTO Works (WorkID, TitleName) VALUES ('U61', 'Melophobia');
INSERT INTO Works (WorkID, TitleName) VALUES ('U62', 'Drunk in Love');
INSERT INTO Works (WorkID, TitleName) VALUES ('U63', 'Good Kisser');
INSERT INTO Works (WorkID, TitleName) VALUES ('U64', 'New Flame');
INSERT INTO Works (WorkID, TitleName) VALUES ('U65', 'Options');
INSERT INTO Works (WorkID, TitleName) VALUES ('U66', 'The Worst');
INSERT INTO Works (WorkID, TitleName) VALUES ('U67', 'Sail Out');
INSERT INTO Works (WorkID, TitleName) VALUES ('U68', 'Mali is...');
INSERT INTO Works (WorkID, TitleName) VALUES ('U69', 'Love, Marriage & Divorce');
INSERT INTO Works (WorkID, TitleName) VALUES ('U70', 'Islander');
INSERT INTO Works (WorkID, TitleName) VALUES ('U71', 'Lift Your Spirit');
INSERT INTO Works (WorkID, TitleName) VALUES ('U72', 'Black Radio 2');
INSERT INTO Works (WorkID, TitleName) VALUES ('U73', 'Give The People What They Want');
INSERT INTO Works (WorkID, TitleName) VALUES ('U74', 'i');
INSERT INTO Works (WorkID, TitleName) VALUES ('U75', 'Anaconda');
INSERT INTO Works (WorkID, TitleName) VALUES ('U76', 'Bound 2');
INSERT INTO Works (WorkID, TitleName) VALUES ('U77', 'Me Dem Boyz');
INSERT INTO Works (WorkID, TitleName) VALUES ('U78', '0 to 100 / The Catch Up');
INSERT INTO Works (WorkID, TitleName) VALUES ('U79', 'The MArshall Mathers LP 2');
INSERT INTO Works (WorkID, TitleName) VALUES ('U80', 'The New Classic');
INSERT INTO Works (WorkID, TitleName) VALUES ('U81', 'Because the Internet');
INSERT INTO Works (WorkID, TitleName) VALUES ('U82', 'Nobody''s Smiling');
INSERT INTO Works (WorkID, TitleName) VALUES ('U83', 'Oxymoron');
INSERT INTO Works (WorkID, TitleName) VALUES ('U84', 'Blacc Hollywood');
INSERT INTO Works (WorkID, TitleName) VALUES ('U85', 'I''m Not Gonna Miss You');
INSERT INTO Works (WorkID, TitleName) VALUES ('U86', 'American Kids');
INSERT INTO Works (WorkID, TitleName) VALUES ('U87', 'Automatic');
INSERT INTO Works (WorkID, TitleName) VALUES ('U88', 'Give Me Back My Hometown');
INSERT INTO Works (WorkID, TitleName) VALUES ('U89', 'Meanwhile Back at Mama''s');
INSERT INTO Works (WorkID, TitleName) VALUES ('U90', 'Platinum');
INSERT INTO Works (WorkID, TitleName) VALUES ('U91', 'Riser');
INSERT INTO Works (WorkID, TitleName) VALUES ('U92', 'The Outsiders');
INSERT INTO Works (WorkID, TitleName) VALUES ('U93', '12 Stories');
INSERT INTO Works (WorkID, TitleName) VALUES ('U94', 'The Way I''m Livin''');
INSERT INTO Works (WorkID, TitleName) VALUES ('T1', 'Modern Family');
INSERT INTO Works (WorkID, TitleName) VALUES ('T2', 'The Big Bang Theory');
INSERT INTO Works (WorkID, TitleName) VALUES ('T3', 'Louie');
INSERT INTO Works (WorkID, TitleName) VALUES ('T4', 'Orange is the New Black');
INSERT INTO Works (WorkID, TitleName) VALUES ('T5', 'Silicon Valley');
INSERT INTO Works (WorkID, TitleName) VALUES ('T6', 'Veep');
INSERT INTO Works (WorkID, TitleName) VALUES ('T7', 'Breaking Bad');
INSERT INTO Works (WorkID, TitleName) VALUES ('T8', 'Downton Abbey');
INSERT INTO Works (WorkID, TitleName) VALUES ('T9', 'Game of Thrones');
INSERT INTO Works (WorkID, TitleName) VALUES ('T10', 'House of Cards');
INSERT INTO Works (WorkID, TitleName) VALUES ('T11', 'Mad Men');
INSERT INTO Works (WorkID, TitleName) VALUES ('T12', 'True Detective');
INSERT INTO Works (WorkID, TitleName) VALUES ('T13', 'The Colbert Report');
INSERT INTO Works (WorkID, TitleName) VALUES ('T14', 'The Daily Show with Jon Stewart');
INSERT INTO Works (WorkID, TitleName) VALUES ('T15', 'Jimmy Kimmel Live!');
INSERT INTO Works (WorkID, TitleName) VALUES ('T16', 'Real Time with Bill Maher');
INSERT INTO Works (WorkID, TitleName) VALUES ('T17', 'Saturday Night Live');
INSERT INTO Works (WorkID, TitleName) VALUES ('T18', 'The Tonight Show Starring Jimmy Fallon');
INSERT INTO Works (WorkID, TitleName) VALUES ('T19', 'Fargo');
INSERT INTO Works (WorkID, TitleName) VALUES ('T20', 'American Horror Story: Coven');
INSERT INTO Works (WorkID, TitleName) VALUES ('T21', 'Bonnie & Clyde');
INSERT INTO Works (WorkID, TitleName) VALUES ('T22', 'Luther');
INSERT INTO Works (WorkID, TitleName) VALUES ('T23', 'Treme');
INSERT INTO Works (WorkID, TitleName) VALUES ('T24', 'The White Queen');
INSERT INTO Works (WorkID, TitleName) VALUES ('T25', 'The Normal Heart');
INSERT INTO Works (WorkID, TitleName) VALUES ('T26', 'Killing Kennedy');
INSERT INTO Works (WorkID, TitleName) VALUES ('T27', 'Muhammad Ali''s Greatest Fight');
INSERT INTO Works (WorkID, TitleName) VALUES ('T28', 'Sherlock: "His Last Vow"');
INSERT INTO Works (WorkID, TitleName) VALUES ('T29', 'The Trip to Bountiful');
INSERT INTO Works (WorkID, TitleName) VALUES ('T30', 'The Amazing Race');
INSERT INTO Works (WorkID, TitleName) VALUES ('T31', 'Dancing with the Stars');
INSERT INTO Works (WorkID, TitleName) VALUES ('T32', 'Project Runway');
INSERT INTO Works (WorkID, TitleName) VALUES ('T33', 'So You Think You Can Dance');
INSERT INTO Works (WorkID, TitleName) VALUES ('T34', 'Top Chef');
INSERT INTO Works (WorkID, TitleName) VALUES ('T35', 'The Voice');
INSERT INTO Works (WorkID, TitleName) VALUES ('T36', 'House of Lies');
INSERT INTO Works (WorkID, TitleName) VALUES ('T37', 'Derek');
INSERT INTO Works (WorkID, TitleName) VALUES ('T38', 'Episodes');
INSERT INTO Works (WorkID, TitleName) VALUES ('T39', 'Shameless');
INSERT INTO Works (WorkID, TitleName) VALUES ('T40', 'Girls');
INSERT INTO Works (WorkID, TitleName) VALUES ('T41', 'Nurse Jackie');
INSERT INTO Works (WorkID, TitleName) VALUES ('T42', 'Mike & Molly');
INSERT INTO Works (WorkID, TitleName) VALUES ('T43', 'Parks and Recreation');
INSERT INTO Works (WorkID, TitleName) VALUES ('T44', 'The Newsroom');
INSERT INTO Works (WorkID, TitleName) VALUES ('T45', 'The Good Wife');
INSERT INTO Works (WorkID, TitleName) VALUES ('T47', 'Masters of Sex');
INSERT INTO Works (WorkID, TitleName) VALUES ('T48', 'Homeland');
INSERT INTO Works (WorkID, TitleName) VALUES ('T49', 'Scandal');
INSERT INTO Works (WorkID, TitleName) VALUES ('T50', 'Dancing on the Edge');
INSERT INTO Works (WorkID, TitleName) VALUES ('T51', 'Burton & Taylor');
INSERT INTO Works (WorkID, TitleName) VALUES ('T52', 'Return to Zero');
INSERT INTO Works (WorkID, TitleName) VALUES ('T53', 'The Spoils of Babylon');
INSERT INTO Works (WorkID, TitleName) VALUES ('T54', 'Portandia');
INSERT INTO Works (WorkID, TitleName) VALUES ('T55', 'Brooklyn Nine-Nine');
INSERT INTO Works (WorkID, TitleName) VALUES ('T56', 'Mom');
INSERT INTO Works (WorkID, TitleName) VALUES ('T57', 'Ray Donovan');
INSERT INTO Works (WorkID, TitleName) VALUES ('T58', 'Flowers in the Attic');
INSERT INTO Works (WorkID, TitleName) VALUES ('M1', 'Birdman or (The Unexpected Virtue of Ignorance)');
INSERT INTO Works (WorkID, TitleName) VALUES ('M2', 'American Sniper');
INSERT INTO Works (WorkID, TitleName) VALUES ('M3', 'Boyhood');
INSERT INTO Works (WorkID, TitleName) VALUES ('M4', 'The Grand Budapest Hotel');
INSERT INTO Works (WorkID, TitleName) VALUES ('M5', 'The Imitation Game');
INSERT INTO Works (WorkID, TitleName) VALUES ('M6', 'Selma');
INSERT INTO Works (WorkID, TitleName) VALUES ('M7', 'The Theory of Everything');
INSERT INTO Works (WorkID, TitleName) VALUES ('M8', 'Whiplash');
INSERT INTO Works (WorkID, TitleName) VALUES ('M9', 'Foxcatcher');
INSERT INTO Works (WorkID, TitleName) VALUES ('M10', 'Still Alice');
INSERT INTO Works (WorkID, TitleName) VALUES ('M11', 'Two Days, One Night');
INSERT INTO Works (WorkID, TitleName) VALUES ('M12', 'Gone Girl');
INSERT INTO Works (WorkID, TitleName) VALUES ('M13', 'Wild');
INSERT INTO Works (WorkID, TitleName) VALUES ('M14', 'The Judge');
INSERT INTO Works (WorkID, TitleName) VALUES ('M15', 'Into the Woods');
INSERT INTO Works (WorkID, TitleName) VALUES ('M16', 'Nightcrawler');
INSERT INTO Works (WorkID, TitleName) VALUES ('M17', 'Inherent Vice');
INSERT INTO Works (WorkID, TitleName) VALUES ('M18', 'Big Hero 6');
INSERT INTO Works (WorkID, TitleName) VALUES ('M19', 'The Boxtrolls');
INSERT INTO Works (WorkID, TitleName) VALUES ('M20', 'How to Train Your Dragon 2');
INSERT INTO Works (WorkID, TitleName) VALUES ('M21', 'Song of the Sea');
INSERT INTO Works (WorkID, TitleName) VALUES ('M22', 'The Tale of Princess Kaguya');
INSERT INTO Works (WorkID, TitleName) VALUES ('M23', 'Ida');
INSERT INTO Works (WorkID, TitleName) VALUES ('M24', 'Leviathan');
INSERT INTO Works (WorkID, TitleName) VALUES ('M25', 'Tanagerines');
INSERT INTO Works (WorkID, TitleName) VALUES ('M26', 'Timbuktu');
INSERT INTO Works (WorkID, TitleName) VALUES ('M27', 'Wild Tales');
INSERT INTO Works (WorkID, TitleName) VALUES ('M28', 'Citizenfour');
INSERT INTO Works (WorkID, TitleName) VALUES ('M29', 'Finding Vivian Maier');
INSERT INTO Works (WorkID, TitleName) VALUES ('M30', 'Last Days in Vietnam');
INSERT INTO Works (WorkID, TitleName) VALUES ('M31', 'The Salt of the Earth');
INSERT INTO Works (WorkID, TitleName) VALUES ('M32', 'Virunga');
INSERT INTO Works (WorkID, TitleName) VALUES ('M33', 'Crisis Hotline: Veterans Press 1');
INSERT INTO Works (WorkID, TitleName) VALUES ('M34', 'Joanna');
INSERT INTO Works (WorkID, TitleName) VALUES ('M35', 'Our Curse');
INSERT INTO Works (WorkID, TitleName) VALUES ('M36', 'The Reaper');
INSERT INTO Works (WorkID, TitleName) VALUES ('M37', 'White Earth');
INSERT INTO Works (WorkID, TitleName) VALUES ('M38', 'The Phone Call');
INSERT INTO Works (WorkID, TitleName) VALUES ('M39', 'Aya');
INSERT INTO Works (WorkID, TitleName) VALUES ('M40', 'Boogaloo and Graham');
INSERT INTO Works (WorkID, TitleName) VALUES ('M41', 'Butter Lamp');
INSERT INTO Works (WorkID, TitleName) VALUES ('M42', 'Parvaneh');
INSERT INTO Works (WorkID, TitleName) VALUES ('M43', 'Feast');
INSERT INTO Works (WorkID, TitleName) VALUES ('M44', 'The Bigger Picture');
INSERT INTO Works (WorkID, TitleName) VALUES ('M45', '12 Years a Slave');
INSERT INTO Works (WorkID, TitleName) VALUES ('M46', 'American Hustle');
INSERT INTO Works (WorkID, TitleName) VALUES ('M47', 'Captain Phillips');
INSERT INTO Works (WorkID, TitleName) VALUES ('M48', 'Dallas Buyers Club');
INSERT INTO Works (WorkID, TitleName) VALUES ('M49', 'Gravity');
INSERT INTO Works (WorkID, TitleName) VALUES ('M50', 'Her');
INSERT INTO Works (WorkID, TitleName) VALUES ('M51', 'Nebraska');
INSERT INTO Works (WorkID, TitleName) VALUES ('M52', 'Philomena');
INSERT INTO Works (WorkID, TitleName) VALUES ('M53', 'The Wolf of Wall Street');
INSERT INTO Works (WorkID, TitleName) VALUES ('M54', 'Blue Jasmine');
INSERT INTO Works (WorkID, TitleName) VALUES ('M55', 'August: Osage County');
INSERT INTO Works (WorkID, TitleName) VALUES ('M56', 'Before Midnight');
INSERT INTO Works (WorkID, TitleName) VALUES ('M57', 'Frozen');
INSERT INTO Works (WorkID, TitleName) VALUES ('M58', 'The Croods');
INSERT INTO Works (WorkID, TitleName) VALUES ('M59', 'Despicable Me 2');
INSERT INTO Works (WorkID, TitleName) VALUES ('M60', 'Ernest & Celestine');
INSERT INTO Works (WorkID, TitleName) VALUES ('M61', 'The Wind Rises');
INSERT INTO Works (WorkID, TitleName) VALUES ('M62', 'Saving Mr. Banks');
INSERT INTO Works (WorkID, TitleName) VALUES ('M63', 'Mandela: Long Walk to Freedom');
INSERT INTO Works (WorkID, TitleName) VALUES ('M64', 'All is Lost');
INSERT INTO Works (WorkID, TitleName) VALUES ('M65', 'The Hobbit: The Desolation of Smaug');
INSERT INTO Works (WorkID, TitleName) VALUES ('M66', 'Lone Survivor');
INSERT INTO Works (WorkID, TitleName) VALUES ('M67', 'Inside Llewyn Davis');
INSERT INTO Works (WorkID, TitleName) VALUES ('M68', 'The Great Gatsby');
INSERT INTO Works (WorkID, TitleName) VALUES ('M69', 'The Dam Keeper');
INSERT INTO Works (WorkID, TitleName) VALUES ('M70', 'Me and My Moulton');
INSERT INTO Works (WorkID, TitleName) VALUES ('M71', 'A Single Life');
INSERT INTO Works (WorkID, TitleName) VALUES ('M72', 'Interstellar');
INSERT INTO Works (WorkID, TitleName) VALUES ('M73', 'Mr. Turner');
INSERT INTO Works (WorkID, TitleName) VALUES ('M74', 'The Lego Movie');
INSERT INTO Works (WorkID, TitleName) VALUES ('M75', 'Beyond the Lights');
INSERT INTO Works (WorkID, TitleName) VALUES ('M76', 'Glen Campbell: I''ll Be Me');
INSERT INTO Works (WorkID, TitleName) VALUES ('M77', 'Begin Again');
INSERT INTO Works (WorkID, TitleName) VALUES ('M78', 'The Hobbit: The Battle of the Five Armies');
INSERT INTO Works (WorkID, TitleName) VALUES ('M79', 'Unbroken');
INSERT INTO Works (WorkID, TitleName) VALUES ('M80', 'Guardians of the Galaxy');
INSERT INTO Works (WorkID, TitleName) VALUES ('M81', 'Maleficent');
INSERT INTO Works (WorkID, TitleName) VALUES ('M82', 'Captain America: The Winter Soldier');
INSERT INTO Works (WorkID, TitleName) VALUES ('M83', 'Dawn of the Planet of the Apes');
INSERT INTO Works (WorkID, TitleName) VALUES ('M84', 'X-Men: Days of Future Past');
INSERT INTO Works (WorkID, TitleName) VALUES ('P1', 'Alejandro G. Inarritu');
INSERT INTO Works (WorkID, TitleName) VALUES ('P2', 'John Lesher');
INSERT INTO Works (WorkID, TitleName) VALUES ('P3', 'James W. Skotchdopole');
INSERT INTO Works (WorkID, TitleName) VALUES ('P4', 'Sam Smith');
INSERT INTO Works (WorkID, TitleName) VALUES ('P5', 'Iggy Azalea');
INSERT INTO Works (WorkID, TitleName) VALUES ('P6', 'Charli XCX');
INSERT INTO Works (WorkID, TitleName) VALUES ('P7', 'Sia');
INSERT INTO Works (WorkID, TitleName) VALUES ('P8', 'Taylor Swift');
INSERT INTO Works (WorkID, TitleName) VALUES ('P9', 'Meghan Trainor');
INSERT INTO Works (WorkID, TitleName) VALUES ('P10', 'Beck');
INSERT INTO Works (WorkID, TitleName) VALUES ('P11', 'Beyonce');
INSERT INTO Works (WorkID, TitleName) VALUES ('P12', 'Ed Sheeran');
INSERT INTO Works (WorkID, TitleName) VALUES ('P13', 'Pharrell Williams');
INSERT INTO Works (WorkID, TitleName) VALUES ('P14', 'Andrew Hozier-Byrne');
INSERT INTO Works (WorkID, TitleName) VALUES ('P15', 'John Legend');
INSERT INTO Works (WorkID, TitleName) VALUES ('P16', 'A Great Big World');
INSERT INTO Works (WorkID, TitleName) VALUES ('P17', 'Christina Aguilera');
INSERT INTO Works (WorkID, TitleName) VALUES ('P18', 'Coldplay');
INSERT INTO Works (WorkID, TitleName) VALUES ('P19', 'Jessie J');
INSERT INTO Works (WorkID, TitleName) VALUES ('P20', 'Katy Perry');
INSERT INTO Works (WorkID, TitleName) VALUES ('P21', 'Juicy J');
INSERT INTO Works (WorkID, TitleName) VALUES ('P22', 'Miley Cyrus');
INSERT INTO Works (WorkID, TitleName) VALUES ('P23', 'Ariana Grande');
INSERT INTO Works (WorkID, TitleName) VALUES ('P24', 'Tony Bennett');
INSERT INTO Works (WorkID, TitleName) VALUES ('P25', 'Lady Gaga');
INSERT INTO Works (WorkID, TitleName) VALUES ('P26', 'Annie Lennox');
INSERT INTO Works (WorkID, TitleName) VALUES ('P27', 'Barry Manilow');
INSERT INTO Works (WorkID, TitleName) VALUES ('P28', 'Johnny Mathis');
INSERT INTO Works (WorkID, TitleName) VALUES ('P29', 'Barbra Streisand');
INSERT INTO Works (WorkID, TitleName) VALUES ('P30', 'Clean Bandit');
INSERT INTO Works (WorkID, TitleName) VALUES ('P31', 'Jess Glynne');
INSERT INTO Works (WorkID, TitleName) VALUES ('P32', 'Basement Jaxx');
INSERT INTO Works (WorkID, TitleName) VALUES ('P33', 'ETML');
INSERT INTO Works (WorkID, TitleName) VALUES ('P34', 'Disclosure');
INSERT INTO Works (WorkID, TitleName) VALUES ('P35', 'Mary J. Blige');
INSERT INTO Works (WorkID, TitleName) VALUES ('P36', 'Duke Dumont');
INSERT INTO Works (WorkID, TitleName) VALUES ('P37', 'Jax Jones');
INSERT INTO Works (WorkID, TitleName) VALUES ('P38', 'Zhu');
INSERT INTO Works (WorkID, TitleName) VALUES ('P39', 'Aphex Twin');
INSERT INTO Works (WorkID, TitleName) VALUES ('P40', 'deadmau5');
INSERT INTO Works (WorkID, TitleName) VALUES ('P41', 'Little Dragon');
INSERT INTO Works (WorkID, TitleName) VALUES ('P42', 'Royksopp');
INSERT INTO Works (WorkID, TitleName) VALUES ('P43', 'Robyn');
INSERT INTO Works (WorkID, TitleName) VALUES ('P44', 'Mat Zo');
INSERT INTO Works (WorkID, TitleName) VALUES ('P45', 'Chris Thile');
INSERT INTO Works (WorkID, TitleName) VALUES ('P46', 'Edgar Meyer');
INSERT INTO Works (WorkID, TitleName) VALUES ('P47', 'Mindi Abair');
INSERT INTO Works (WorkID, TitleName) VALUES ('P48', 'Gerald Albright');
INSERT INTO Works (WorkID, TitleName) VALUES ('P49', 'Nathan East');
INSERT INTO Works (WorkID, TitleName) VALUES ('P50', 'Jeff Lorber');
INSERT INTO Works (WorkID, TitleName) VALUES ('P51', 'Chuck Loeb');
INSERT INTO Works (WorkID, TitleName) VALUES ('P52', 'Everette Harp');
INSERT INTO Works (WorkID, TitleName) VALUES ('P53', 'Jack White');
INSERT INTO Works (WorkID, TitleName) VALUES ('P54', 'Ryan Adams');
INSERT INTO Works (WorkID, TitleName) VALUES ('P55', 'Arctic Monkeys');
INSERT INTO Works (WorkID, TitleName) VALUES ('P56', 'The Black Keys');
INSERT INTO Works (WorkID, TitleName) VALUES ('P57', 'Tenacious D');
INSERT INTO Works (WorkID, TitleName) VALUES ('P58', 'Anthrax');
INSERT INTO Works (WorkID, TitleName) VALUES ('P59', 'Mastodon');
INSERT INTO Works (WorkID, TitleName) VALUES ('P60', 'Motorhead');
INSERT INTO Works (WorkID, TitleName) VALUES ('P61', 'Slipknot');
INSERT INTO Works (WorkID, TitleName) VALUES ('P62', 'Paramore');
INSERT INTO Works (WorkID, TitleName) VALUES ('P63', 'Tom Petty and the Heartbreakers');
INSERT INTO Works (WorkID, TitleName) VALUES ('P64', 'U2');
INSERT INTO Works (WorkID, TitleName) VALUES ('P65', 'St. Vincent');
INSERT INTO Works (WorkID, TitleName) VALUES ('P66', 'alt-J');
INSERT INTO Works (WorkID, TitleName) VALUES ('P67', 'Arcade Fire');
INSERT INTO Works (WorkID, TitleName) VALUES ('P68', 'Cage the Elephant');
INSERT INTO Works (WorkID, TitleName) VALUES ('P69', 'Jay Z');
INSERT INTO Works (WorkID, TitleName) VALUES ('P70', 'Usher');
INSERT INTO Works (WorkID, TitleName) VALUES ('P71', 'Chris Brown');
INSERT INTO Works (WorkID, TitleName) VALUES ('P72', 'Rick Ross');
INSERT INTO Works (WorkID, TitleName) VALUES ('P73', 'Luke James');
INSERT INTO Works (WorkID, TitleName) VALUES ('P74', 'Jhene Aiko');
INSERT INTO Works (WorkID, TitleName) VALUES ('P75', 'Mali Music');
INSERT INTO Works (WorkID, TitleName) VALUES ('P76', 'Toni Braxton');
INSERT INTO Works (WorkID, TitleName) VALUES ('P77', 'Babyface');
INSERT INTO Works (WorkID, TitleName) VALUES ('P78', 'Bernhoft');
INSERT INTO Works (WorkID, TitleName) VALUES ('P79', 'Aloe Blacc');
INSERT INTO Works (WorkID, TitleName) VALUES ('P80', 'Robert Glasper Experiment');
INSERT INTO Works (WorkID, TitleName) VALUES ('P81', 'Sharon Jones');
INSERT INTO Works (WorkID, TitleName) VALUES ('P82', 'The Dap-Kings');
INSERT INTO Works (WorkID, TitleName) VALUES ('P83', 'Kendrick Lamar');
INSERT INTO Works (WorkID, TitleName) VALUES ('P84', 'Nicki Minaj');
INSERT INTO Works (WorkID, TitleName) VALUES ('P85', 'Kanye West');
INSERT INTO Works (WorkID, TitleName) VALUES ('P86', 'Charlie Wilson');
INSERT INTO Works (WorkID, TitleName) VALUES ('P87', 'Wiz Khalifa');
INSERT INTO Works (WorkID, TitleName) VALUES ('P88', 'Drake');
INSERT INTO Works (WorkID, TitleName) VALUES ('P89', 'Eminem');
INSERT INTO Works (WorkID, TitleName) VALUES ('P90', 'Childish Gambino');
INSERT INTO Works (WorkID, TitleName) VALUES ('P91', 'Common');
INSERT INTO Works (WorkID, TitleName) VALUES ('P92', 'ScHoolboy Q');
INSERT INTO Works (WorkID, TitleName) VALUES ('P93', 'Glen Campbell');
INSERT INTO Works (WorkID, TitleName) VALUES ('P94', 'Kenny Chesney');
INSERT INTO Works (WorkID, TitleName) VALUES ('P95', 'Miranda Lambert');
INSERT INTO Works (WorkID, TitleName) VALUES ('P96', 'Eric Church');
INSERT INTO Works (WorkID, TitleName) VALUES ('P97', 'Tim McGraw');
INSERT INTO Works (WorkID, TitleName) VALUES ('P98', 'Faith Hill');
INSERT INTO Works (WorkID, TitleName) VALUES ('P99', 'Dierks Bentley');
INSERT INTO Works (WorkID, TitleName) VALUES ('P100', 'Brandy Clark');
INSERT INTO Works (WorkID, TitleName) VALUES ('P101', 'Lee Ann Womack');
INSERT INTO Works (WorkID, TitleName) VALUES ('P102', 'Clint Eastwood');
INSERT INTO Works (WorkID, TitleName) VALUES ('P103', 'Robert Lorenz');
INSERT INTO Works (WorkID, TitleName) VALUES ('P104', 'Andrew Lazar');
INSERT INTO Works (WorkID, TitleName) VALUES ('P105', 'Bradley Cooper');
INSERT INTO Works (WorkID, TitleName) VALUES ('P106', 'Peter Morgan');
INSERT INTO Works (WorkID, TitleName) VALUES ('P107', 'Richard Linklater');
INSERT INTO Works (WorkID, TitleName) VALUES ('P108', 'Cathleen Sutherland');
INSERT INTO Works (WorkID, TitleName) VALUES ('P109', 'Wes Anderson');
INSERT INTO Works (WorkID, TitleName) VALUES ('P110', 'Scott Rudin');
INSERT INTO Works (WorkID, TitleName) VALUES ('P111', 'Steven M. Rales');
INSERT INTO Works (WorkID, TitleName) VALUES ('P112', 'Jeremy Dawson');
INSERT INTO Works (WorkID, TitleName) VALUES ('P113', 'Nora Grossman');
INSERT INTO Works (WorkID, TitleName) VALUES ('P114', 'Ido Ostrowsky');
INSERT INTO Works (WorkID, TitleName) VALUES ('P115', 'Teddy Schwarzman');
INSERT INTO Works (WorkID, TitleName) VALUES ('P116', 'Christian Colson');
INSERT INTO Works (WorkID, TitleName) VALUES ('P117', 'Oprah Winfrey');
INSERT INTO Works (WorkID, TitleName) VALUES ('P118', 'Dede Gardner');
INSERT INTO Works (WorkID, TitleName) VALUES ('P119', 'Jeremy Kleiner');
INSERT INTO Works (WorkID, TitleName) VALUES ('P120', 'Tim Bevan');
INSERT INTO Works (WorkID, TitleName) VALUES ('P121', 'Eric Fellner');
INSERT INTO Works (WorkID, TitleName) VALUES ('P122', 'Lisa Bruce');
INSERT INTO Works (WorkID, TitleName) VALUES ('P123', 'Anthony McCarten');
INSERT INTO Works (WorkID, TitleName) VALUES ('P124', 'Jason Blum');
INSERT INTO Works (WorkID, TitleName) VALUES ('P125', 'Bennett Miller');
INSERT INTO Works (WorkID, TitleName) VALUES ('P126', 'Morten Tyldum');
INSERT INTO Works (WorkID, TitleName) VALUES ('P127', 'Eddie Redmayne');
INSERT INTO Works (WorkID, TitleName) VALUES ('P128', 'Steve Carell');
INSERT INTO Works (WorkID, TitleName) VALUES ('P129', 'Benedict Cumberbatch');
INSERT INTO Works (WorkID, TitleName) VALUES ('P130', 'Michael Keaton');
INSERT INTO Works (WorkID, TitleName) VALUES ('P131', 'Julianne Moore');
INSERT INTO Works (WorkID, TitleName) VALUES ('P132', 'Marion Cotillard');
INSERT INTO Works (WorkID, TitleName) VALUES ('P133', 'Felicity Jones');
INSERT INTO Works (WorkID, TitleName) VALUES ('P134', 'Rosamund Pike');
INSERT INTO Works (WorkID, TitleName) VALUES ('P135', 'Reese Witherspoon');
INSERT INTO Works (WorkID, TitleName) VALUES ('P136', 'J.K. Simmons');
INSERT INTO Works (WorkID, TitleName) VALUES ('P137', 'Robert Duvall');
INSERT INTO Works (WorkID, TitleName) VALUES ('P138', 'Ethan Hawke');
INSERT INTO Works (WorkID, TitleName) VALUES ('P139', 'Edward Norton');
INSERT INTO Works (WorkID, TitleName) VALUES ('P140', 'Mark Ruffalo');
INSERT INTO Works (WorkID, TitleName) VALUES ('P141', 'Patricia Arquette');
INSERT INTO Works (WorkID, TitleName) VALUES ('P142', 'Laura Dern');
INSERT INTO Works (WorkID, TitleName) VALUES ('P143', 'Keira Knightley');
INSERT INTO Works (WorkID, TitleName) VALUES ('P144', 'Emma Stone');
INSERT INTO Works (WorkID, TitleName) VALUES ('P145', 'Meryl Streep');
INSERT INTO Works (WorkID, TitleName) VALUES ('P146', 'Nicolas Giacobone');
INSERT INTO Works (WorkID, TitleName) VALUES ('P147', 'Alexander Dinelaris Jr.');
INSERT INTO Works (WorkID, TitleName) VALUES ('P148', 'Armando Bo Jr');
INSERT INTO Works (WorkID, TitleName) VALUES ('P149', 'E. Max Frye');
INSERT INTO Works (WorkID, TitleName) VALUES ('P150', 'Dan Futterman');
INSERT INTO Works (WorkID, TitleName) VALUES ('P151', 'Hugo Guinness');
INSERT INTO Works (WorkID, TitleName) VALUES ('P152', 'Dan Gilroy');
INSERT INTO Works (WorkID, TitleName) VALUES ('P153', 'Graham Moore');
INSERT INTO Works (WorkID, TitleName) VALUES ('P154', 'Jason Hall');
INSERT INTO Works (WorkID, TitleName) VALUES ('P155', 'Paul Thomas Anderson');
INSERT INTO Works (WorkID, TitleName) VALUES ('P156', 'Damnien Chazelle');
INSERT INTO Works (WorkID, TitleName) VALUES ('P157', 'Don Hall');
INSERT INTO Works (WorkID, TitleName) VALUES ('P158', 'Chris Williams');
INSERT INTO Works (WorkID, TitleName) VALUES ('P159', 'Roy Conli');
INSERT INTO Works (WorkID, TitleName) VALUES ('P160', 'Anthony Stacchi');
INSERT INTO Works (WorkID, TitleName) VALUES ('P161', 'Graham Annable');
INSERT INTO Works (WorkID, TitleName) VALUES ('P162', 'Travis Knight');
INSERT INTO Works (WorkID, TitleName) VALUES ('P163', 'Dean DeBlois');
INSERT INTO Works (WorkID, TitleName) VALUES ('P164', 'Bonnie Arnold');
INSERT INTO Works (WorkID, TitleName) VALUES ('P165', 'Tomm Moore');
INSERT INTO Works (WorkID, TitleName) VALUES ('P166', 'Isao Takahata');
INSERT INTO Works (WorkID, TitleName) VALUES ('P167', 'Pawel Pawlikowski');
INSERT INTO Works (WorkID, TitleName) VALUES ('P168', 'Andrey Zvyagintsev');
INSERT INTO Works (WorkID, TitleName) VALUES ('P169', 'Zaza Urushadze');
INSERT INTO Works (WorkID, TitleName) VALUES ('P170', 'Abderrahmane Sissako');
INSERT INTO Works (WorkID, TitleName) VALUES ('P171', 'Damian Szifron');
INSERT INTO Works (WorkID, TitleName) VALUES ('P172', 'Alexandre Desplat');
INSERT INTO Works (WorkID, TitleName) VALUES ('P173', 'Hans Zimmer');
INSERT INTO Works (WorkID, TitleName) VALUES ('P174', 'Gary Yershon');
INSERT INTO Works (WorkID, TitleName) VALUES ('P175', 'Johann Johannsson');
INSERT INTO Works (WorkID, TitleName) VALUES ('P176', 'Common');
INSERT INTO Works (WorkID, TitleName) VALUES ('P177', 'Shawn Patterson');
INSERT INTO Works (WorkID, TitleName) VALUES ('P178', 'Diane Warren');
INSERT INTO Works (WorkID, TitleName) VALUES ('P179', 'Glen Campbell');
INSERT INTO Works (WorkID, TitleName) VALUES ('P180', 'Gregg Alexander');
INSERT INTO Works (WorkID, TitleName) VALUES ('P181', 'Danielle Brisebois');
INSERT INTO Works (WorkID, TitleName) VALUES ('P182', 'Bryan Cranston');
INSERT INTO Works (WorkID, TitleName) VALUES ('P183', 'Samuel Barnett');
INSERT INTO Works (WorkID, TitleName) VALUES ('P184', 'Chris O''Dowd');
INSERT INTO Works (WorkID, TitleName) VALUES ('P185', 'Mark Rylance');
INSERT INTO Works (WorkID, TitleName) VALUES ('P186', 'Tony Shalhoub');
INSERT INTO Works (WorkID, TitleName) VALUES ('P187', 'Audra McDonald');
INSERT INTO Works (WorkID, TitleName) VALUES ('P188', 'Tyne Daly');
INSERT INTO Works (WorkID, TitleName) VALUES ('P189', 'LaTanya Richardson');
INSERT INTO Works (WorkID, TitleName) VALUES ('P190', 'Cherry Jones');
INSERT INTO Works (WorkID, TitleName) VALUES ('P191', 'Estelle Parsons');
INSERT INTO Works (WorkID, TitleName) VALUES ('P192', 'Neil Patrick Harris');
INSERT INTO Works (WorkID, TitleName) VALUES ('P193', 'Ramin Karimloo');
INSERT INTO Works (WorkID, TitleName) VALUES ('P194', 'Andy Karl');
INSERT INTO Works (WorkID, TitleName) VALUES ('P195', 'Jefferson Mays');
INSERT INTO Works (WorkID, TitleName) VALUES ('P196', 'Bryce Pinkham');
INSERT INTO Works (WorkID, TitleName) VALUES ('P197', 'Jessie Mueller');
INSERT INTO Works (WorkID, TitleName) VALUES ('P198', 'Mary Bridget Davies');
INSERT INTO Works (WorkID, TitleName) VALUES ('P199', 'Sutton Foster');
INSERT INTO Works (WorkID, TitleName) VALUES ('P200', 'Idina Menzel');
INSERT INTO Works (WorkID, TitleName) VALUES ('P201', 'Kelli O''Hara');
INSERT INTO Works (WorkID, TitleName) VALUES ('P202', 'Reed Birney');
INSERT INTO Works (WorkID, TitleName) VALUES ('P203', 'Paul Chahidi');
INSERT INTO Works (WorkID, TitleName) VALUES ('P204', 'Stephen Fry');
INSERT INTO Works (WorkID, TitleName) VALUES ('P205', 'Brian J. Smith');
INSERT INTO Works (WorkID, TitleName) VALUES ('P206', 'Sophie Okonedo');
INSERT INTO Works (WorkID, TitleName) VALUES ('P207', 'Sarah Greene');
INSERT INTO Works (WorkID, TitleName) VALUES ('P208', 'Celia Keenan-Bolger');
INSERT INTO Works (WorkID, TitleName) VALUES ('P209', 'Anika Noni Rose');
INSERT INTO Works (WorkID, TitleName) VALUES ('P210', 'Mare Winningham');
INSERT INTO Works (WorkID, TitleName) VALUES ('P211', 'James Monroe Iglehart');
INSERT INTO Works (WorkID, TitleName) VALUES ('P212', 'Danny Burstein');
INSERT INTO Works (WorkID, TitleName) VALUES ('P213', 'Nick Cordero');
INSERT INTO Works (WorkID, TitleName) VALUES ('P214', 'Joshua Henry');
INSERT INTO Works (WorkID, TitleName) VALUES ('P215', 'Jarrod Spector');
INSERT INTO Works (WorkID, TitleName) VALUES ('P216', 'Lena Hall');
INSERT INTO Works (WorkID, TitleName) VALUES ('P217', 'Linda Emond');
INSERT INTO Works (WorkID, TitleName) VALUES ('P218', 'Anika Larsen');
INSERT INTO Works (WorkID, TitleName) VALUES ('P219', 'Adriane Lenox');
INSERT INTO Works (WorkID, TitleName) VALUES ('P220', 'Lauren Worsham');
INSERT INTO Works (WorkID, TitleName) VALUES ('P221', 'Jim Parsons');
INSERT INTO Works (WorkID, TitleName) VALUES ('P222', 'Louis C.K.');
INSERT INTO Works (WorkID, TitleName) VALUES ('P223', 'Don Cheadle');
INSERT INTO Works (WorkID, TitleName) VALUES ('P224', 'Ricky Gervais');
INSERT INTO Works (WorkID, TitleName) VALUES ('P225', 'Matt LeBlanc');
INSERT INTO Works (WorkID, TitleName) VALUES ('P226', 'William H. Macy');
INSERT INTO Works (WorkID, TitleName) VALUES ('P227', 'Julia Louis-Dreyfus');
INSERT INTO Works (WorkID, TitleName) VALUES ('P228', 'Lena Dunham');
INSERT INTO Works (WorkID, TitleName) VALUES ('P229', 'Edie Falco');
INSERT INTO Works (WorkID, TitleName) VALUES ('P230', 'Melissa McCarthy');
INSERT INTO Works (WorkID, TitleName) VALUES ('P231', 'Amy Poehler');
INSERT INTO Works (WorkID, TitleName) VALUES ('P232', 'Taylor Schilling');
INSERT INTO Works (WorkID, TitleName) VALUES ('P233', 'Jeff Daniels');
INSERT INTO Works (WorkID, TitleName) VALUES ('P234', 'Jon Hamm');
INSERT INTO Works (WorkID, TitleName) VALUES ('P235', 'Woody Harrelson');
INSERT INTO Works (WorkID, TitleName) VALUES ('P236', 'Matthew McConaughey');
INSERT INTO Works (WorkID, TitleName) VALUES ('P237', 'Kevin Spacey');
INSERT INTO Works (WorkID, TitleName) VALUES ('P238', 'Julianna Margulies');
INSERT INTO Works (WorkID, TitleName) VALUES ('P239', 'Lizzy Caplan');
INSERT INTO Works (WorkID, TitleName) VALUES ('P240', 'Claire Danes');
INSERT INTO Works (WorkID, TitleName) VALUES ('P241', 'Michelle Dockery');
INSERT INTO Works (WorkID, TitleName) VALUES ('P242', 'Kerry Washington');
INSERT INTO Works (WorkID, TitleName) VALUES ('P243', 'Robin Wright');
INSERT INTO Works (WorkID, TitleName) VALUES ('P244', 'Chiwetel Ejiofor');
INSERT INTO Works (WorkID, TitleName) VALUES ('P245', 'Idris Elba');
INSERT INTO Works (WorkID, TitleName) VALUES ('P246', 'Martin Freeman');
INSERT INTO Works (WorkID, TitleName) VALUES ('P247', 'Billy Bob Thornton');
INSERT INTO Works (WorkID, TitleName) VALUES ('P248', 'Jessica Lange');
INSERT INTO Works (WorkID, TitleName) VALUES ('P249', 'Helena Bonham Carter');
INSERT INTO Works (WorkID, TitleName) VALUES ('P250', 'Minnie Driver');
INSERT INTO Works (WorkID, TitleName) VALUES ('P251', 'Sarah Paulson');
INSERT INTO Works (WorkID, TitleName) VALUES ('P252', 'Cicely Tyson');
INSERT INTO Works (WorkID, TitleName) VALUES ('P253', 'Kristen Wiig');
INSERT INTO Works (WorkID, TitleName) VALUES ('P254', 'Ty Burrell');
INSERT INTO Works (WorkID, TitleName) VALUES ('P255', 'Fred Armisen');
INSERT INTO Works (WorkID, TitleName) VALUES ('P256', 'Andre Braugher');
INSERT INTO Works (WorkID, TitleName) VALUES ('P257', 'Adam Driver');
INSERT INTO Works (WorkID, TitleName) VALUES ('P258', 'Jesse Tyler Ferguson');
INSERT INTO Works (WorkID, TitleName) VALUES ('P259', 'Tony Hale');
INSERT INTO Works (WorkID, TitleName) VALUES ('P260', 'Allison Janney');
INSERT INTO Works (WorkID, TitleName) VALUES ('P261', 'Mayim Bialik');
INSERT INTO Works (WorkID, TitleName) VALUES ('P262', 'Julie Bowen');
INSERT INTO Works (WorkID, TitleName) VALUES ('P263', 'Anna Chlumsky');
INSERT INTO Works (WorkID, TitleName) VALUES ('P264', 'Kate McKinnon');
INSERT INTO Works (WorkID, TitleName) VALUES ('P265', 'Kate Mulgrew');
INSERT INTO Works (WorkID, TitleName) VALUES ('P266', 'Aaron Paul');
INSERT INTO Works (WorkID, TitleName) VALUES ('P267', 'Jim Carter');
INSERT INTO Works (WorkID, TitleName) VALUES ('P268', 'Josh Charles');
INSERT INTO Works (WorkID, TitleName) VALUES ('P269', 'Peter Dinklage');
INSERT INTO Works (WorkID, TitleName) VALUES ('P270', 'Mandy Patinkin');
INSERT INTO Works (WorkID, TitleName) VALUES ('P271', 'Jon Voight');
INSERT INTO Works (WorkID, TitleName) VALUES ('P272', 'Anna Gunn');
INSERT INTO Works (WorkID, TitleName) VALUES ('P273', 'Christine Baranski');
INSERT INTO Works (WorkID, TitleName) VALUES ('P274', 'Joanne Froggatt');
INSERT INTO Works (WorkID, TitleName) VALUES ('P275', 'Lena Headey');
INSERT INTO Works (WorkID, TitleName) VALUES ('P276', 'Christina Hendricks');
INSERT INTO Works (WorkID, TitleName) VALUES ('P277', 'Maggie Smith');
INSERT INTO Works (WorkID, TitleName) VALUES ('P278', 'Matt Bomer');
INSERT INTO Works (WorkID, TitleName) VALUES ('P279', 'Colin Hanks');
INSERT INTO Works (WorkID, TitleName) VALUES ('P280', 'Kathy Bates');
INSERT INTO Works (WorkID, TitleName) VALUES ('P281', 'Joe Mantello');
INSERT INTO Works (WorkID, TitleName) VALUES ('P282', 'Alfred Molina');
INSERT INTO Works (WorkID, TitleName) VALUES ('P283', 'Angela Bassett');
INSERT INTO Works (WorkID, TitleName) VALUES ('P284', 'Frances Conroy');
INSERT INTO Works (WorkID, TitleName) VALUES ('P285', 'Julia Roberts');
INSERT INTO Works (WorkID, TitleName) VALUES ('P286', 'Allison Tolman');
INSERT INTO Works (WorkID, TitleName) VALUES ('P287', 'Bastille');
INSERT INTO Works (WorkID, TitleName) VALUES ('P288', 'HAIM');
INSERT INTO Works (WorkID, TitleName) VALUES ('U95', 'It''s Your World');
INSERT INTO Works (WorkID, TitleName) VALUES ('U96', 'Like This');
INSERT INTO Works (WorkID, TitleName) VALUES ('U97', 'Jesus Children');
INSERT INTO Works (WorkID, TitleName) VALUES ('U98', 'As');
INSERT INTO Works (WorkID, TitleName) VALUES ('U99', 'I.R.S.');
INSERT INTO Works (WorkID, TitleName) VALUES ('U100', 'Nobody');
INSERT INTO Works (WorkID, TitleName) VALUES ('U101', 'Hold Up Wait a Minute (Woo Woo)');
INSERT INTO Works (WorkID, TitleName) VALUES ('U102', 'X');
INSERT INTO Works (WorkID, TitleName) VALUES ('U103', 3005);
INSERT INTO Works (WorkID, TitleName) VALUES ('U104', '0 to 100 / The Catch Up');
INSERT INTO Works (WorkID, TitleName) VALUES ('U105', 'Rap God');
INSERT INTO Works (WorkID, TitleName) VALUES ('U106', 'All I Need Is You');
INSERT INTO Works (WorkID, TitleName) VALUES ('U107', 'The Monster');
INSERT INTO Works (WorkID, TitleName) VALUES ('U108', 'Blak Majik');
INSERT INTO Works (WorkID, TitleName) VALUES ('U109', 'Tuesday');
INSERT INTO Works (WorkID, TitleName) VALUES ('U110', 'Studio');
INSERT INTO Works (WorkID, TitleName) VALUES ('U111', 'Something in the Water');
INSERT INTO Works (WorkID, TitleName) VALUES ('U112', 'Invisible');
INSERT INTO Works (WorkID, TitleName) VALUES ('U113', 'Cop Car');
INSERT INTO Works (WorkID, TitleName) VALUES ('U114', 'Gentle on My Mind');
INSERT INTO Works (WorkID, TitleName) VALUES ('U115', 'Somethin'' Bad');
INSERT INTO Works (WorkID, TitleName) VALUES ('U116', 'Day Drinking');
INSERT INTO Works (WorkID, TitleName) VALUES ('U117', 'Raise ''Em Up');
INSERT INTO Works (WorkID, TitleName) VALUES ('P289', 'Jennifer Hudson');
INSERT INTO Works (WorkID, TitleName) VALUES ('P290', 'R. Kelly');
INSERT INTO Works (WorkID, TitleName) VALUES ('P291', 'Ledisi');
INSERT INTO Works (WorkID, TitleName) VALUES ('P292', 'Lalah Hathaway');
INSERT INTO Works (WorkID, TitleName) VALUES ('P293', 'Malcolm Jamal Warner');
INSERT INTO Works (WorkID, TitleName) VALUES ('P294', 'Marsha Ambrosius');
INSERT INTO Works (WorkID, TitleName) VALUES ('P295', 'Anthony Hamilton');
INSERT INTO Works (WorkID, TitleName) VALUES ('P296', 'Angie Fisher');
INSERT INTO Works (WorkID, TitleName) VALUES ('P297', 'Kem');
INSERT INTO Works (WorkID, TitleName) VALUES ('P298', 'Antonique Smith');
INSERT INTO Works (WorkID, TitleName) VALUES ('P299', 'Lecrae');
INSERT INTO Works (WorkID, TitleName) VALUES ('P300', 'Rihanna');
INSERT INTO Works (WorkID, TitleName) VALUES ('P301', 'ILoveMakonnen');
INSERT INTO Works (WorkID, TitleName) VALUES ('P302', 'BJ the Chicago Kid');
INSERT INTO Works (WorkID, TitleName) VALUES ('P303', 'Carrie Underwood');
INSERT INTO Works (WorkID, TitleName) VALUES ('P304', 'Hunter Hayes');
INSERT INTO Works (WorkID, TitleName) VALUES ('P305', 'Keith Urban');
INSERT INTO Works (WorkID, TitleName) VALUES ('P306', 'The Band Perry');
INSERT INTO Works (WorkID, TitleName) VALUES ('P307', 'Little Big Town');