CREATE TABLE Works(WorkID VARCHAR(200), TitleName VARCHAR(500));
INSERT INTO Works (WorkID, TitleName) VALUES ('S1', 'Act One');
INSERT INTO Works (WorkID, TitleName) VALUES ('S2', 'All the Way');
INSERT INTO Works (WorkID, TitleName) VALUES ('S3', 'Casa Valentina');
INSERT INTO Works (WorkID, TitleName) VALUES ('S4', 'Mothers and Sons');
INSERT INTO Works (WorkID, TitleName) VALUES ('S5', 'Outside Mullingar');
INSERT INTO Works (WorkID, TitleName) VALUES ('S6', 'A Gentleman''s Guide to Love and Murder');
INSERT INTO Works (WorkID, TitleName) VALUES ('S7', 'After Midnight');
INSERT INTO Works (WorkID, TitleName) VALUES ('S8', 'Aladdin');
INSERT INTO Works (WorkID, TitleName) VALUES ('S9', 'Beautiful: The Carole King Musical');
INSERT INTO Works (WorkID, TitleName) VALUES ('S10', 'A Raisin in the Sun');
INSERT INTO Works (WorkID, TitleName) VALUES ('S11', 'The Cripple of Inishmaan');
INSERT INTO Works (WorkID, TitleName) VALUES ('S12', 'The Glass Menagerie');
INSERT INTO Works (WorkID, TitleName) VALUES ('S13', 'Twelfth Night');
INSERT INTO Works (WorkID, TitleName) VALUES ('S14', 'Hedwig and the Angry Inch');
INSERT INTO Works (WorkID, TitleName) VALUES ('S15', 'Les Miserables');
INSERT INTO Works (WorkID, TitleName) VALUES ('S16', 'Violet');
INSERT INTO Works (WorkID, TitleName) VALUES ('S17', 'Of Mice and Men');
INSERT INTO Works (WorkID, TitleName) VALUES ('S18', 'Richard III');
INSERT INTO Works (WorkID, TitleName) VALUES ('S19', 'Lady Day at Emerson''s Bar & Grill');
INSERT INTO Works (WorkID, TitleName) VALUES ('S20', 'The Velocity of Autumn');
INSERT INTO Works (WorkID, TitleName) VALUES ('S21', 'Rocky');
INSERT INTO Works (WorkID, TitleName) VALUES ('S22', 'A Night with Janis Joplin');
INSERT INTO Works (WorkID, TitleName) VALUES ('S23', 'If/Then');
INSERT INTO Works (WorkID, TitleName) VALUES ('S24', 'The Bridges of Madison County');
INSERT INTO Works (WorkID, TitleName) VALUES ('S25', 'Cabaret');
INSERT INTO Works (WorkID, TitleName) VALUES ('S26', 'Bullets Over Broadway');
INSERT INTO Works (WorkID, TitleName) VALUES ('S27', 'Machinal');
INSERT INTO Works (WorkID, TitleName) VALUES ('U1', 'Stay with Me (Darkchild Version)');
INSERT INTO Works (WorkID, TitleName) VALUES ('U2', 'Fancy');
INSERT INTO Works (WorkID, TitleName) VALUES ('U3', 'Chandelier');
INSERT INTO Works (WorkID, TitleName) VALUES ('U4', 'Shake It Off');
INSERT INTO Works (WorkID, TitleName) VALUES ('U5', 'All About That Bass');
INSERT INTO Works (WorkID, TitleName) VALUES ('U6', 'Morning Phase');
INSERT INTO Works (WorkID, TitleName) VALUES ('U7', 'Beyonce');
INSERT INTO Works (WorkID, TitleName) VALUES ('U8', 'x');
INSERT INTO Works (WorkID, TitleName) VALUES ('U9', 'In the Lonely Hour');
INSERT INTO Works (WorkID, TitleName) VALUES ('U10', 'G I R L');
INSERT INTO Works (WorkID, TitleName) VALUES ('U11', 'Take Me to Church');
INSERT INTO Works (WorkID, TitleName) VALUES ('U12', 'Happy (Live)');
INSERT INTO Works (WorkID, TitleName) VALUES ('U13', 'All of Me (Live)');
INSERT INTO Works (WorkID, TitleName) VALUES ('U14', 'Say Something');
INSERT INTO Works (WorkID, TitleName) VALUES ('U15', 'A Sky Full of Stars');
INSERT INTO Works (WorkID, TitleName) VALUES ('U16', 'Bang Bang');
INSERT INTO Works (WorkID, TitleName) VALUES ('U17', 'Dark Horse');
INSERT INTO Works (WorkID, TitleName) VALUES ('U18', 'Ghost Stories');
INSERT INTO Works (WorkID, TitleName) VALUES ('U19', 'Bangerz');
INSERT INTO Works (WorkID, TitleName) VALUES ('U20', 'My Everything');
INSERT INTO Works (WorkID, TitleName) VALUES ('U21', 'Prism');
INSERT INTO Works (WorkID, TitleName) VALUES ('U22', 'Cheek to Cheek');
INSERT INTO Works (WorkID, TitleName) VALUES ('U23', 'Nostalgia');
INSERT INTO Works (WorkID, TitleName) VALUES ('U24', 'Night Songs');
INSERT INTO Works (WorkID, TitleName) VALUES ('U25', 'Sending You a Little Christmas');
INSERT INTO Works (WorkID, TitleName) VALUES ('U26', 'Partners');
INSERT INTO Works (WorkID, TitleName) VALUES ('U27', 'Rather Be');
INSERT INTO Works (WorkID, TitleName) VALUES ('U28', 'Never Say Never');
INSERT INTO Works (WorkID, TitleName) VALUES ('U29', 'F For You');
INSERT INTO Works (WorkID, TitleName) VALUES ('U30', 'I Got U');
INSERT INTO Works (WorkID, TitleName) VALUES ('U31', 'Faded');
INSERT INTO Works (WorkID, TitleName) VALUES ('U32', 'Syro');
INSERT INTO Works (WorkID, TitleName) VALUES ('U33', 'while(1<2)');
INSERT INTO Works (WorkID, TitleName) VALUES ('U34', 'Nabuma Rubberband');
INSERT INTO Works (WorkID, TitleName) VALUES ('U35', 'Do It Again');
INSERT INTO Works (WorkID, TitleName) VALUES ('U36', 'Damage Control');
INSERT INTO Works (WorkID, TitleName) VALUES ('U37', 'Bass & Mandolin');
INSERT INTO Works (WorkID, TitleName) VALUES ('U38', 'Wild Heart');
INSERT INTO Works (WorkID, TitleName) VALUES ('U39', 'Slam Dunk');
INSERT INTO Works (WorkID, TitleName) VALUES ('U40', 'Nathan East');
INSERT INTO Works (WorkID, TitleName) VALUES ('U41', 'Jazz Funk Soul');
INSERT INTO Works (WorkID, TitleName) VALUES ('U42', 'Lazaretto');
INSERT INTO Works (WorkID, TitleName) VALUES ('U43', 'Gimme Something Good');
INSERT INTO Works (WorkID, TitleName) VALUES ('U44', 'Do I Wanna Know?');
INSERT INTO Works (WorkID, TitleName) VALUES ('U45', 'Blue Moon');
INSERT INTO Works (WorkID, TitleName) VALUES ('U46', 'Fever');
INSERT INTO Works (WorkID, TitleName) VALUES ('U47', 'The Last in Line');
INSERT INTO Works (WorkID, TitleName) VALUES ('U48', 'Neon Knights');
INSERT INTO Works (WorkID, TitleName) VALUES ('U49', 'High Road');
INSERT INTO Works (WorkID, TitleName) VALUES ('U50', 'Heartbreaker');
INSERT INTO Works (WorkID, TitleName) VALUES ('U51', 'The Negative One');
INSERT INTO Works (WorkID, TitleName) VALUES ('U52', 'Ain''t It Fun');
INSERT INTO Works (WorkID, TitleName) VALUES ('U53', 'Fever');
INSERT INTO Works (WorkID, TitleName) VALUES ('U54', 'Ryan Adams');
INSERT INTO Works (WorkID, TitleName) VALUES ('U55', 'Turn Blue');
INSERT INTO Works (WorkID, TitleName) VALUES ('U56', 'Hypnotic Eye');
INSERT INTO Works (WorkID, TitleName) VALUES ('U57', 'Songs of Innocence');
INSERT INTO Works (WorkID, TitleName) VALUES ('U58', 'St. Vincent');
INSERT INTO Works (WorkID, TitleName) VALUES ('U59', 'This Is All Yours');
INSERT INTO Works (WorkID, TitleName) VALUES ('U60', 'Reflektor');
INSERT INTO Works (WorkID, TitleName) VALUES ('U61', 'Melophobia');
INSERT INTO Works (WorkID, TitleName) VALUES ('U62', 'Drunk in Love');
INSERT INTO Works (WorkID, TitleName) VALUES ('U63', 'Good Kisser');
INSERT INTO Works (WorkID, TitleName) VALUES ('U64', 'New Flame');
INSERT INTO Works (WorkID, TitleName) VALUES ('U65', 'Options');
INSERT INTO Works (WorkID, TitleName) VALUES ('U66', 'The Worst');
INSERT INTO Works (WorkID, TitleName) VALUES ('U67', 'Sail Out');
INSERT INTO Works (WorkID, TitleName) VALUES ('U68', 'Mali is...');
INSERT INTO Works (WorkID, TitleName) VALUES ('U69', 'Love, Marriage & Divorce');
INSERT INTO Works (WorkID, TitleName) VALUES ('U70', 'Islander');
INSERT INTO Works (WorkID, TitleName) VALUES ('U71', 'Lift Your Spirit');
INSERT INTO Works (WorkID, TitleName) VALUES ('U72', 'Black Radio 2');
INSERT INTO Works (WorkID, TitleName) VALUES ('U73', 'Give The People What They Want');
INSERT INTO Works (WorkID, TitleName) VALUES ('U74', 'i');
INSERT INTO Works (WorkID, TitleName) VALUES ('U75', 'Anaconda');
INSERT INTO Works (WorkID, TitleName) VALUES ('U76', 'Bound 2');
INSERT INTO Works (WorkID, TitleName) VALUES ('U77', 'Me Dem Boyz');
INSERT INTO Works (WorkID, TitleName) VALUES ('U78', '0 to 100 / The Catch Up');
INSERT INTO Works (WorkID, TitleName) VALUES ('U79', 'The MArshall Mathers LP 2');
INSERT INTO Works (WorkID, TitleName) VALUES ('U80', 'The New Classic');
INSERT INTO Works (WorkID, TitleName) VALUES ('U81', 'Because the Internet');
INSERT INTO Works (WorkID, TitleName) VALUES ('U82', 'Nobody''s Smiling');
INSERT INTO Works (WorkID, TitleName) VALUES ('U83', 'Oxymoron');
INSERT INTO Works (WorkID, TitleName) VALUES ('U84', 'Blacc Hollywood');
INSERT INTO Works (WorkID, TitleName) VALUES ('U85', 'I''m Not Gonna Miss You');
INSERT INTO Works (WorkID, TitleName) VALUES ('U86', 'American Kids');
INSERT INTO Works (WorkID, TitleName) VALUES ('U87', 'Automatic');
INSERT INTO Works (WorkID, TitleName) VALUES ('U88', 'Give Me Back My Hometown');
INSERT INTO Works (WorkID, TitleName) VALUES ('U89', 'Meanwhile Back at Mama''s');
INSERT INTO Works (WorkID, TitleName) VALUES ('U90', 'Platinum');
INSERT INTO Works (WorkID, TitleName) VALUES ('U91', 'Riser');
INSERT INTO Works (WorkID, TitleName) VALUES ('U92', 'The Outsiders');
INSERT INTO Works (WorkID, TitleName) VALUES ('U93', '12 Stories');
INSERT INTO Works (WorkID, TitleName) VALUES ('U94', 'The Way I''m Livin''');
INSERT INTO Works (WorkID, TitleName) VALUES ('T1', 'Modern Family');
INSERT INTO Works (WorkID, TitleName) VALUES ('T2', 'The Big Bang Theory');
INSERT INTO Works (WorkID, TitleName) VALUES ('T3', 'Louie');
INSERT INTO Works (WorkID, TitleName) VALUES ('T4', 'Orange is the New Black');
INSERT INTO Works (WorkID, TitleName) VALUES ('T5', 'Silicon Valley');
INSERT INTO Works (WorkID, TitleName) VALUES ('T6', 'Veep');
INSERT INTO Works (WorkID, TitleName) VALUES ('T7', 'Breaking Bad');
INSERT INTO Works (WorkID, TitleName) VALUES ('T8', 'Downton Abbey');
INSERT INTO Works (WorkID, TitleName) VALUES ('T9', 'Game of Thrones');
INSERT INTO Works (WorkID, TitleName) VALUES ('T10', 'House of Cards');
INSERT INTO Works (WorkID, TitleName) VALUES ('T11', 'Mad Men');
INSERT INTO Works (WorkID, TitleName) VALUES ('T12', 'True Detective');
INSERT INTO Works (WorkID, TitleName) VALUES ('T13', 'The Colbert Report');
INSERT INTO Works (WorkID, TitleName) VALUES ('T14', 'The Daily Show with Jon Stewart');
INSERT INTO Works (WorkID, TitleName) VALUES ('T15', 'Jimmy Kimmel Live!');
INSERT INTO Works (WorkID, TitleName) VALUES ('T16', 'Real Time with Bill Maher');
INSERT INTO Works (WorkID, TitleName) VALUES ('T17', 'Saturday Night Live');
INSERT INTO Works (WorkID, TitleName) VALUES ('T18', 'The Tonight Show Starring Jimmy Fallon');
INSERT INTO Works (WorkID, TitleName) VALUES ('T19', 'Fargo');
INSERT INTO Works (WorkID, TitleName) VALUES ('T20', 'American Horror Story: Coven');
INSERT INTO Works (WorkID, TitleName) VALUES ('T21', 'Bonnie & Clyde');
INSERT INTO Works (WorkID, TitleName) VALUES ('T22', 'Luther');
INSERT INTO Works (WorkID, TitleName) VALUES ('T23', 'Treme');
INSERT INTO Works (WorkID, TitleName) VALUES ('T24', 'The White Queen');
INSERT INTO Works (WorkID, TitleName) VALUES ('T25', 'The Normal Heart');
INSERT INTO Works (WorkID, TitleName) VALUES ('T26', 'Killing Kennedy');
INSERT INTO Works (WorkID, TitleName) VALUES ('T27', 'Muhammad Ali''s Greatest Fight');
INSERT INTO Works (WorkID, TitleName) VALUES ('T28', 'Sherlock: "His Last Vow"');
INSERT INTO Works (WorkID, TitleName) VALUES ('T29', 'The Trip to Bountiful');
INSERT INTO Works (WorkID, TitleName) VALUES ('T30', 'The Amazing Race');
INSERT INTO Works (WorkID, TitleName) VALUES ('T31', 'Dancing with the Stars');
INSERT INTO Works (WorkID, TitleName) VALUES ('T32', 'Project Runway');
INSERT INTO Works (WorkID, TitleName) VALUES ('T33', 'So You Think You Can Dance');
INSERT INTO Works (WorkID, TitleName) VALUES ('T34', 'Top Chef');
INSERT INTO Works (WorkID, TitleName) VALUES ('T35', 'The Voice');
INSERT INTO Works (WorkID, TitleName) VALUES ('T36', 'House of Lies');
INSERT INTO Works (WorkID, TitleName) VALUES ('T37', 'Derek');
INSERT INTO Works (WorkID, TitleName) VALUES ('T38', 'Episodes');
INSERT INTO Works (WorkID, TitleName) VALUES ('T39', 'Shameless');
INSERT INTO Works (WorkID, TitleName) VALUES ('T40', 'Girls');
INSERT INTO Works (WorkID, TitleName) VALUES ('T41', 'Nurse Jackie');
INSERT INTO Works (WorkID, TitleName) VALUES ('T42', 'Mike & Molly');
INSERT INTO Works (WorkID, TitleName) VALUES ('T43', 'Parks and Recreation');
INSERT INTO Works (WorkID, TitleName) VALUES ('T44', 'The Newsroom');
INSERT INTO Works (WorkID, TitleName) VALUES ('T45', 'The Good Wife');
INSERT INTO Works (WorkID, TitleName) VALUES ('T47', 'Masters of Sex');
INSERT INTO Works (WorkID, TitleName) VALUES ('T48', 'Homeland');
INSERT INTO Works (WorkID, TitleName) VALUES ('T49', 'Scandal');
INSERT INTO Works (WorkID, TitleName) VALUES ('T50', 'Dancing on the Edge');
INSERT INTO Works (WorkID, TitleName) VALUES ('T51', 'Burton & Taylor');
INSERT INTO Works (WorkID, TitleName) VALUES ('T52', 'Return to Zero');
INSERT INTO Works (WorkID, TitleName) VALUES ('T53', 'The Spoils of Babylon');
INSERT INTO Works (WorkID, TitleName) VALUES ('T54', 'Portandia');
INSERT INTO Works (WorkID, TitleName) VALUES ('T55', 'Brooklyn Nine-Nine');
INSERT INTO Works (WorkID, TitleName) VALUES ('T56', 'Mom');
INSERT INTO Works (WorkID, TitleName) VALUES ('T57', 'Ray Donovan');
INSERT INTO Works (WorkID, TitleName) VALUES ('T58', 'Flowers in the Attic');
INSERT INTO Works (WorkID, TitleName) VALUES ('M1', 'Birdman or (The Unexpected Virtue of Ignorance)');
INSERT INTO Works (WorkID, TitleName) VALUES ('M2', 'American Sniper');
INSERT INTO Works (WorkID, TitleName) VALUES ('M3', 'Boyhood');
INSERT INTO Works (WorkID, TitleName) VALUES ('M4', 'The Grand Budapest Hotel');
INSERT INTO Works (WorkID, TitleName) VALUES ('M5', 'The Imitation Game');
INSERT INTO Works (WorkID, TitleName) VALUES ('M6', 'Selma');
INSERT INTO Works (WorkID, TitleName) VALUES ('M7', 'The Theory of Everything');
INSERT INTO Works (WorkID, TitleName) VALUES ('M8', 'Whiplash');
INSERT INTO Works (WorkID, TitleName) VALUES ('M9', 'Foxcatcher');
INSERT INTO Works (WorkID, TitleName) VALUES ('M10', 'Still Alice');
INSERT INTO Works (WorkID, TitleName) VALUES ('M11', 'Two Days, One Night');
INSERT INTO Works (WorkID, TitleName) VALUES ('M12', 'Gone Girl');
INSERT INTO Works (WorkID, TitleName) VALUES ('M13', 'Wild');
INSERT INTO Works (WorkID, TitleName) VALUES ('M14', 'The Judge');
INSERT INTO Works (WorkID, TitleName) VALUES ('M15', 'Into the Woods');
INSERT INTO Works (WorkID, TitleName) VALUES ('M16', 'Nightcrawler');
INSERT INTO Works (WorkID, TitleName) VALUES ('M17', 'Inherent Vice');
INSERT INTO Works (WorkID, TitleName) VALUES ('M18', 'Big Hero 6');
INSERT INTO Works (WorkID, TitleName) VALUES ('M19', 'The Boxtrolls');
INSERT INTO Works (WorkID, TitleName) VALUES ('M20', 'How to Train Your Dragon 2');
INSERT INTO Works (WorkID, TitleName) VALUES ('M21', 'Song of the Sea');
INSERT INTO Works (WorkID, TitleName) VALUES ('M22', 'The Tale of Princess Kaguya');
INSERT INTO Works (WorkID, TitleName) VALUES ('M23', 'Ida');
INSERT INTO Works (WorkID, TitleName) VALUES ('M24', 'Leviathan');
INSERT INTO Works (WorkID, TitleName) VALUES ('M25', 'Tanagerines');
INSERT INTO Works (WorkID, TitleName) VALUES ('M26', 'Timbuktu');
INSERT INTO Works (WorkID, TitleName) VALUES ('M27', 'Wild Tales');
INSERT INTO Works (WorkID, TitleName) VALUES ('M28', 'Citizenfour');
INSERT INTO Works (WorkID, TitleName) VALUES ('M29', 'Finding Vivian Maier');
INSERT INTO Works (WorkID, TitleName) VALUES ('M30', 'Last Days in Vietnam');
INSERT INTO Works (WorkID, TitleName) VALUES ('M31', 'The Salt of the Earth');
INSERT INTO Works (WorkID, TitleName) VALUES ('M32', 'Virunga');
INSERT INTO Works (WorkID, TitleName) VALUES ('M33', 'Crisis Hotline: Veterans Press 1');
INSERT INTO Works (WorkID, TitleName) VALUES ('M34', 'Joanna');
INSERT INTO Works (WorkID, TitleName) VALUES ('M35', 'Our Curse');
INSERT INTO Works (WorkID, TitleName) VALUES ('M36', 'The Reaper');
INSERT INTO Works (WorkID, TitleName) VALUES ('M37', 'White Earth');
INSERT INTO Works (WorkID, TitleName) VALUES ('M38', 'The Phone Call');
INSERT INTO Works (WorkID, TitleName) VALUES ('M39', 'Aya');
INSERT INTO Works (WorkID, TitleName) VALUES ('M40', 'Boogaloo and Graham');
INSERT INTO Works (WorkID, TitleName) VALUES ('M41', 'Butter Lamp');
INSERT INTO Works (WorkID, TitleName) VALUES ('M42', 'Parvaneh');
INSERT INTO Works (WorkID, TitleName) VALUES ('M43', 'Feast');
INSERT INTO Works (WorkID, TitleName) VALUES ('M44', 'The Bigger Picture');
INSERT INTO Works (WorkID, TitleName) VALUES ('M45', '12 Years a Slave');
INSERT INTO Works (WorkID, TitleName) VALUES ('M46', 'American Hustle');
INSERT INTO Works (WorkID, TitleName) VALUES ('M47', 'Captain Phillips');
INSERT INTO Works (WorkID, TitleName) VALUES ('M48', 'Dallas Buyers Club');
INSERT INTO Works (WorkID, TitleName) VALUES ('M49', 'Gravity');
INSERT INTO Works (WorkID, TitleName) VALUES ('M50', 'Her');
INSERT INTO Works (WorkID, TitleName) VALUES ('M51', 'Nebraska');
INSERT INTO Works (WorkID, TitleName) VALUES ('M52', 'Philomena');
INSERT INTO Works (WorkID, TitleName) VALUES ('M53', 'The Wolf of Wall Street');
INSERT INTO Works (WorkID, TitleName) VALUES ('M54', 'Blue Jasmine');
INSERT INTO Works (WorkID, TitleName) VALUES ('M55', 'August: Osage County');
INSERT INTO Works (WorkID, TitleName) VALUES ('M56', 'Before Midnight');
INSERT INTO Works (WorkID, TitleName) VALUES ('M57', 'Frozen');
INSERT INTO Works (WorkID, TitleName) VALUES ('M58', 'The Croods');
INSERT INTO Works (WorkID, TitleName) VALUES ('M59', 'Despicable Me 2');
INSERT INTO Works (WorkID, TitleName) VALUES ('M60', 'Ernest & Celestine');
INSERT INTO Works (WorkID, TitleName) VALUES ('M61', 'The Wind Rises');
INSERT INTO Works (WorkID, TitleName) VALUES ('M62', 'Saving Mr. Banks');
INSERT INTO Works (WorkID, TitleName) VALUES ('M63', 'Mandela: Long Walk to Freedom');
INSERT INTO Works (WorkID, TitleName) VALUES ('M64', 'All is Lost');
INSERT INTO Works (WorkID, TitleName) VALUES ('M65', 'The Hobbit: The Desolation of Smaug');
INSERT INTO Works (WorkID, TitleName) VALUES ('M66', 'Lone Survivor');
INSERT INTO Works (WorkID, TitleName) VALUES ('M67', 'Inside Llewyn Davis');
INSERT INTO Works (WorkID, TitleName) VALUES ('M68', 'The Great Gatsby');
INSERT INTO Works (WorkID, TitleName) VALUES ('M69', 'The Dam Keeper');
INSERT INTO Works (WorkID, TitleName) VALUES ('M70', 'Me and My Moulton');
INSERT INTO Works (WorkID, TitleName) VALUES ('M71', 'A Single Life');
INSERT INTO Works (WorkID, TitleName) VALUES ('M72', 'Interstellar');
INSERT INTO Works (WorkID, TitleName) VALUES ('M73', 'Mr. Turner');
INSERT INTO Works (WorkID, TitleName) VALUES ('M74', 'The Lego Movie');
INSERT INTO Works (WorkID, TitleName) VALUES ('M75', 'Beyond the Lights');
INSERT INTO Works (WorkID, TitleName) VALUES ('M76', 'Glen Campbell: I''ll Be Me');
INSERT INTO Works (WorkID, TitleName) VALUES ('M77', 'Begin Again');
INSERT INTO Works (WorkID, TitleName) VALUES ('M78', 'The Hobbit: The Battle of the Five Armies');
INSERT INTO Works (WorkID, TitleName) VALUES ('M79', 'Unbroken');
INSERT INTO Works (WorkID, TitleName) VALUES ('M80', 'Guardians of the Galaxy');
INSERT INTO Works (WorkID, TitleName) VALUES ('M81', 'Maleficent');
INSERT INTO Works (WorkID, TitleName) VALUES ('M82', 'Captain America: The Winter Soldier');
INSERT INTO Works (WorkID, TitleName) VALUES ('M83', 'Dawn of the Planet of the Apes');
INSERT INTO Works (WorkID, TitleName) VALUES ('M84', 'X-Men: Days of Future Past');